//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface ABAnimationUtil : NSObject
{
}

+ (void)startImageViewGif:(id)arg1 withGifPath:(id)arg2 withDuration:(double)arg3;
+ (void)stopRotate:(id)arg1;
+ (void)rotate:(id)arg1 clockDirection:(_Bool)arg2;

@end

