//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "ALBBRegisterProtocol-Protocol.h"

@class ALBBApplyAsoTokenHandler, NSArray, NSLock, NSString;
@protocol IDynamicDataStoreComponent;

@interface ALBBLoginCenter : NSObject <ALBBRegisterProtocol>
{
    _Bool _isLogining;
    _Bool _needLoginView;
    ALBBApplyAsoTokenHandler *_applyAsoTokenHandler;
    NSArray *_loginUrls;
    NSArray *_logoutUrls;
    NSLock *_loginLock;
    id <IDynamicDataStoreComponent> _securityStorage;
}

+ (id)sharedInstance;
@property(retain, nonatomic) id <IDynamicDataStoreComponent> securityStorage; // @synthesize securityStorage=_securityStorage;
@property _Bool needLoginView; // @synthesize needLoginView=_needLoginView;
@property _Bool isLogining; // @synthesize isLogining=_isLogining;
@property(retain) NSLock *loginLock; // @synthesize loginLock=_loginLock;
@property(retain, nonatomic) NSArray *logoutUrls; // @synthesize logoutUrls=_logoutUrls;
@property(retain, nonatomic) NSArray *loginUrls; // @synthesize loginUrls=_loginUrls;
@property(retain) ALBBApplyAsoTokenHandler *applyAsoTokenHandler; // @synthesize applyAsoTokenHandler=_applyAsoTokenHandler;
- (void).cxx_destruct;
- (void)doRegister;
- (void)loginBySsoTokenUrl:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (_Bool)isProcessingLogin;
- (void)changeIsLogining:(id)arg1;
- (void)storeLoginResult:(id)arg1 loginType:(int)arg2;
- (void)bindAlipayAsync:(id)arg1 bizScene:(id)arg2 signData:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (void)mockEasyLoginCompletionHandler:(CDUnknownBlockType)arg1 useName:(id)arg2 userPwd:(id)arg3;
- (void)checkNickModifiable:(CDUnknownBlockType)arg1;
- (void)changeNick:(id)arg1 callBack:(CDUnknownBlockType)arg2;
- (void)openAccountCenterPage:(id)arg1 controller:(id)arg2 callBack:(CDUnknownBlockType)arg3;
- (void)changePhoneNum:(id)arg1 callBack:(CDUnknownBlockType)arg2;
- (void)bindPhoneNum:(id)arg1 callBack:(CDUnknownBlockType)arg2;
- (void)retrievePassword:(id)arg1 extParams:(id)arg2 callBack:(CDUnknownBlockType)arg3;
- (void)retrievePassword:(id)arg1 callBack:(CDUnknownBlockType)arg2;
- (void)modifyPassword:(id)arg1 callBack:(CDUnknownBlockType)arg2;
- (_Bool)isHavanaSsoTokenValid;
- (id)dictionaryToJson:(id)arg1;
- (void)getHavanaSsoToken:(CDUnknownBlockType)arg1;
- (void)implantationLocalCookies;
- (_Bool)judgeURL:(id)arg1 withArray:(id)arg2;
- (_Bool)isLogoutURL:(id)arg1;
- (_Bool)isLoginURL:(id)arg1;
- (void)logoutAllAccounts;
- (void)logout:(id)arg1;
- (void)logout;
- (void)makeSessionInvalidLocally:(CDUnknownBlockType)arg1;
- (void)makeSessionInvalidLocally;
- (void)clearSession;
- (id)currentSession;
- (_Bool)isValidLogin;
- (void)doRegister:(id)arg1 completionHandler:(CDUnknownBlockType)arg2 cancelationHandler:(CDUnknownBlockType)arg3;
- (_Bool)canShowSSOpage;
- (void)afterLoginIfSuccess:(_Bool)arg1 resultInfo:(id)arg2 isCanceledByUser:(_Bool)arg3;
- (void)doOpenLoginView:(id)arg1 needClearSession:(_Bool)arg2;
- (void)tryToOpenLoginViewWithCompletionHandler:(CDUnknownBlockType)arg1 cancelationHandler:(CDUnknownBlockType)arg2 params:(id)arg3 needLoginView:(_Bool)arg4 needClearSession:(_Bool)arg5;
- (void)compatibleLogin:(id)arg1 userId:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)dealICBUOldTokenWithOption:(int)arg1 handler:(CDUnknownBlockType)arg2;
- (_Bool)isVaildString:(id)arg1;
- (void)_loginWithLoginOption:(int)arg1 params:(id)arg2 completionHandler:(CDUnknownBlockType)arg3 cancelationHandler:(CDUnknownBlockType)arg4;
- (void)loginWithLoginOption:(int)arg1 params:(id)arg2 completionHandler:(CDUnknownBlockType)arg3 cancelationHandler:(CDUnknownBlockType)arg4;
- (void)loginWithLoginOption:(int)arg1 completionHandler:(CDUnknownBlockType)arg2 cancelationHandler:(CDUnknownBlockType)arg3;
- (void)checkAndLogin:(int)arg1 completionHandler:(CDUnknownBlockType)arg2 cancelationHandler:(CDUnknownBlockType)arg3;
- (void)updateUrls;
- (void)initLoginUrls;
- (void)forceChangeIsLogining;
- (void)dealloc;
- (void)initLoginCenter;
- (void)initTaobaoEnv;
- (_Bool)isTaobao4iPhone;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

