//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray;

@interface ALBBAddressDataManager : NSObject
{
    _Bool _addressHasUpdateAreaData;
    NSMutableArray *_areaArray;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSMutableArray *areaArray; // @synthesize areaArray=_areaArray;
@property(nonatomic) _Bool addressHasUpdateAreaData; // @synthesize addressHasUpdateAreaData=_addressHasUpdateAreaData;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)saveAreaToFile:(id)arg1;
- (void)updateCityArea:(id)arg1 children:(id)arg2;
- (void)requestRegionsOfCity:(id)arg1 endBlock:(CDUnknownBlockType)arg2;
- (void)updateProvinceArea:(id)arg1 children:(id)arg2;
- (void)requestCitiesOfProvince:(id)arg1 endBlock:(CDUnknownBlockType)arg2;
- (void)requestProvinces:(CDUnknownBlockType)arg1;
- (void)updateTownOfCity:(id)arg1 endBlock:(CDUnknownBlockType)arg2;
- (void)updateCityInfo:(id)arg1 endBlock:(CDUnknownBlockType)arg2;
- (void)updateProvinceInfo:(id)arg1 endBlock:(CDUnknownBlockType)arg2;
- (id)init;

@end

