//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "AliBPageTransitionEventHandling-Protocol.h"

@class NSString;
@protocol AliBPageTransitionEventHandling;

@interface AliBPageTransitionEventHandlerWrapper : NSObject <AliBPageTransitionEventHandling>
{
    CDUnknownBlockType _lifeCycleListener;
    id <AliBPageTransitionEventHandling> _handler;
}

@property(retain, nonatomic) id <AliBPageTransitionEventHandling> handler; // @synthesize handler=_handler;
@property(copy, nonatomic) CDUnknownBlockType lifeCycleListener; // @synthesize lifeCycleListener=_lifeCycleListener;
- (void).cxx_destruct;
- (_Bool)executeWithComplete:(CDUnknownBlockType)arg1;
- (_Bool)canExecute;
- (double)executeDuration;
- (id)initWithHandler:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

