//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

#import "UITextFieldDelegate-Protocol.h"

@class AliCartStepperButton, AliCartStepperTextField, NSString, StyleKitContext;

@interface AliCartStepper : UIControl <UITextFieldDelegate>
{
    _Bool _autoRepeatFlag;
    _Bool _allowLessThanMinQuantityInput;
    _Bool _allowMultipleItemInput;
    _Bool _valueChangedFlag;
    AliCartStepperTextField *_editField;
    AliCartStepperButton *_increaseButton;
    AliCartStepperButton *_decreaseButton;
    CDUnknownBlockType _keyboardPopUpBlock;
    CDUnknownBlockType _keyboardPopDownBlock;
    CDUnknownBlockType _shouldBegineEditBlock;
    CDUnknownBlockType _shouldEndEditBlock;
    CDUnknownBlockType _valueChangedBlock;
    CDUnknownBlockType _lessThanMinQuantityInputBlock;
    long long _currentChange;
    long long _currentValue;
    long long _minimumValue;
    long long _maximumValue;
    long long _stepValue;
    double _autoRepeatInterval;
    double _operateButtonWidth;
    double _spaceBetweenOpertionAndEditionView;
    StyleKitContext *_styleKitContext;
}

@property(retain, nonatomic) StyleKitContext *styleKitContext; // @synthesize styleKitContext=_styleKitContext;
@property(nonatomic) _Bool valueChangedFlag; // @synthesize valueChangedFlag=_valueChangedFlag;
@property(nonatomic) double spaceBetweenOpertionAndEditionView; // @synthesize spaceBetweenOpertionAndEditionView=_spaceBetweenOpertionAndEditionView;
@property(nonatomic) double operateButtonWidth; // @synthesize operateButtonWidth=_operateButtonWidth;
@property(nonatomic) double autoRepeatInterval; // @synthesize autoRepeatInterval=_autoRepeatInterval;
@property(nonatomic) _Bool allowMultipleItemInput; // @synthesize allowMultipleItemInput=_allowMultipleItemInput;
@property(nonatomic) _Bool allowLessThanMinQuantityInput; // @synthesize allowLessThanMinQuantityInput=_allowLessThanMinQuantityInput;
@property(nonatomic) _Bool autoRepeatFlag; // @synthesize autoRepeatFlag=_autoRepeatFlag;
@property(nonatomic) long long stepValue; // @synthesize stepValue=_stepValue;
@property(nonatomic) long long maximumValue; // @synthesize maximumValue=_maximumValue;
@property(nonatomic) long long minimumValue; // @synthesize minimumValue=_minimumValue;
@property(nonatomic) long long currentValue; // @synthesize currentValue=_currentValue;
@property(nonatomic) long long currentChange; // @synthesize currentChange=_currentChange;
@property(copy, nonatomic) CDUnknownBlockType lessThanMinQuantityInputBlock; // @synthesize lessThanMinQuantityInputBlock=_lessThanMinQuantityInputBlock;
@property(copy, nonatomic) CDUnknownBlockType valueChangedBlock; // @synthesize valueChangedBlock=_valueChangedBlock;
@property(copy, nonatomic) CDUnknownBlockType shouldEndEditBlock; // @synthesize shouldEndEditBlock=_shouldEndEditBlock;
@property(copy, nonatomic) CDUnknownBlockType shouldBegineEditBlock; // @synthesize shouldBegineEditBlock=_shouldBegineEditBlock;
@property(copy, nonatomic) CDUnknownBlockType keyboardPopDownBlock; // @synthesize keyboardPopDownBlock=_keyboardPopDownBlock;
@property(copy, nonatomic) CDUnknownBlockType keyboardPopUpBlock; // @synthesize keyboardPopUpBlock=_keyboardPopUpBlock;
@property(retain, nonatomic) AliCartStepperButton *decreaseButton; // @synthesize decreaseButton=_decreaseButton;
@property(retain, nonatomic) AliCartStepperButton *increaseButton; // @synthesize increaseButton=_increaseButton;
@property(retain, nonatomic) AliCartStepperTextField *editField; // @synthesize editField=_editField;
- (void).cxx_destruct;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)didEndEditValue:(long long)arg1;
- (void)editDidDone:(id)arg1;
- (void)decreaseClickEnd:(id)arg1;
- (void)decreaseClickBegin:(id)arg1;
- (void)buttonActionEvent:(id)arg1;
- (void)increaseClickEnd:(id)arg1;
- (void)increaseClickBegin:(id)arg1;
- (_Bool)endEditing:(_Bool)arg1;
- (void)dealloc;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

