//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewController.h>

#import "AliDetailVideoBaseControlDelegate-Protocol.h"

@class AliDetailMultimediaBrowserModel, AliDetailMultimediaModel, AliDetailSegmentControlBase, AliDetailVideoBaseControl, NSArray, NSMutableDictionary, NSString, TBDetailNumberPageControl, TBDetailPhotoBounceTipView, TBDetailPhotoCaptionControl, UIImageView, UIPageControl, UIView;
@protocol AliDetailMultimediaBrowserViewControllerBaseDelegate, TBMagicCubeLifeCycleProtocol;

@interface AliDetailMultimediaBrowserViewControllerBase : UICollectionViewController <AliDetailVideoBaseControlDelegate>
{
    AliDetailSegmentControlBase *_segmentControl;
    _Bool _supportRotationMode;
    _Bool _firstEnter;
    _Bool _isBigShow;
    _Bool _isLayouting;
    id <AliDetailMultimediaBrowserViewControllerBaseDelegate> _delegate;
    unsigned long long _currentPageIndex;
    UIPageControl *_dotPageControl;
    TBDetailNumberPageControl *_numberPageControl;
    TBDetailPhotoCaptionControl *_captionControl;
    UIView *_subTitleDescView;
    UIView *_captionParentView;
    TBDetailPhotoBounceTipView *_bounceTipView;
    CDUnknownBlockType _actionHandler;
    UIImageView *_maskImageView;
    NSMutableDictionary *_successImageInfo;
    NSString *_eventToken;
    NSArray<TBMagicCubeLifeCycleProtocol> *_dataSourceArray;
    AliDetailMultimediaBrowserModel *_browserModel;
    AliDetailVideoBaseControl *_videoControl;
    AliDetailMultimediaModel *_multimediaModel;
    unsigned long long _padding;
    struct CGRect _maskOriginFrame;
}

@property(nonatomic) unsigned long long padding; // @synthesize padding=_padding;
@property(nonatomic) _Bool isLayouting; // @synthesize isLayouting=_isLayouting;
@property(retain, nonatomic) AliDetailSegmentControlBase *segmentControl; // @synthesize segmentControl=_segmentControl;
@property(retain, nonatomic) AliDetailMultimediaModel *multimediaModel; // @synthesize multimediaModel=_multimediaModel;
@property(retain, nonatomic) AliDetailVideoBaseControl *videoControl; // @synthesize videoControl=_videoControl;
@property(nonatomic) _Bool isBigShow; // @synthesize isBigShow=_isBigShow;
@property(retain, nonatomic) AliDetailMultimediaBrowserModel *browserModel; // @synthesize browserModel=_browserModel;
@property(nonatomic) _Bool firstEnter; // @synthesize firstEnter=_firstEnter;
@property(retain, nonatomic) NSArray<TBMagicCubeLifeCycleProtocol> *dataSourceArray; // @synthesize dataSourceArray=_dataSourceArray;
@property(retain, nonatomic) NSString *eventToken; // @synthesize eventToken=_eventToken;
@property(retain, nonatomic) NSMutableDictionary *successImageInfo; // @synthesize successImageInfo=_successImageInfo;
@property(nonatomic) struct CGRect maskOriginFrame; // @synthesize maskOriginFrame=_maskOriginFrame;
@property(retain, nonatomic) UIImageView *maskImageView; // @synthesize maskImageView=_maskImageView;
@property(copy, nonatomic) CDUnknownBlockType actionHandler; // @synthesize actionHandler=_actionHandler;
@property(retain, nonatomic) TBDetailPhotoBounceTipView *bounceTipView; // @synthesize bounceTipView=_bounceTipView;
@property(retain, nonatomic) UIView *captionParentView; // @synthesize captionParentView=_captionParentView;
@property(retain, nonatomic) UIView *subTitleDescView; // @synthesize subTitleDescView=_subTitleDescView;
@property(retain, nonatomic) TBDetailPhotoCaptionControl *captionControl; // @synthesize captionControl=_captionControl;
@property(retain, nonatomic) TBDetailNumberPageControl *numberPageControl; // @synthesize numberPageControl=_numberPageControl;
@property(retain, nonatomic) UIPageControl *dotPageControl; // @synthesize dotPageControl=_dotPageControl;
@property(nonatomic) unsigned long long currentPageIndex; // @synthesize currentPageIndex=_currentPageIndex;
@property(nonatomic) _Bool supportRotationMode; // @synthesize supportRotationMode=_supportRotationMode;
@property(nonatomic) __weak id <AliDetailMultimediaBrowserViewControllerBaseDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)videoDidScrollToAnchor:(long long)arg1;
- (id)createImageDisplayViewModel:(id)arg1 index:(unsigned long long)arg2;
- (void)loadWithDataSource:(id)arg1 pureImage:(_Bool)arg2 toView:(id)arg3 parentVC:(id)arg4 currentIndex:(unsigned long long)arg5 eventToken:(id)arg6;
- (void)updateSubTitleDescView;
- (void)updateCaption;
- (void)updateSegmentControlIfNeed;
- (void)updatePageControlIfNeeded;
- (struct CGRect)frameForCollectionView;
- (void)performLayoutSubviews;
- (void)viewDidLayoutSubviews;
- (void)updateCurrentPageIndex:(unsigned long long)arg1;
- (void)executeDelegatePreFinishMethod;
- (void)removeFromSuperview;
- (void)dismissBrowserCompletion:(CDUnknownBlockType)arg1 maskImageView:(id)arg2;
- (void)jumpToProductViewWithMaskImageView:(id)arg1;
- (void)dismissBrowserWithMaskImageView:(id)arg1;
- (struct CGSize)fitScreenSizeForImage:(id)arg1;
- (struct CGRect)frameToCenterForImageSize:(struct CGSize)arg1;
- (void)viewingPageAtIndex:(unsigned long long)arg1 animated:(_Bool)arg2 maskImageView:(id)arg3;
- (void)saveImage:(id)arg1 forIndex:(unsigned long long)arg2;
- (void)addBounceTipHandler:(CDUnknownBlockType)arg1;
- (void)segmentControlValueChanged:(id)arg1;
- (void)setCurrentSegmentIndex:(unsigned long long)arg1;
- (void)setupCollectionView;
- (void)prepareForStartAnimation;
- (void)setupContent;
- (void)addExtensionViewForViewModel:(id)arg1 onCellView:(id)arg2;
- (void)clickCloseButton:(id)arg1;
- (void)viewWillDisMiss;
- (void)setupSegmentControlIfNeed;
- (void)setupSubTitleDescViewIfNeeded;
- (void)setupCaptionControlIfNeeded;
- (void)setupPageControlIfNeeded;
- (void)setup;
- (id)getComponentView;
- (void)bindData:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)dealloc;
- (void)viewDidLoad;
- (id)createLayout;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

