//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSString;

@interface AliDetailJhsGlobalInfoModel : TBJSONModel
{
    NSString *_countryIcon;
    NSString *_countryName;
    NSString *_descText;
}

@property(copy, nonatomic) NSString *descText; // @synthesize descText=_descText;
@property(copy, nonatomic) NSString *countryName; // @synthesize countryName=_countryName;
@property(copy, nonatomic) NSString *countryIcon; // @synthesize countryIcon=_countryIcon;
- (void).cxx_destruct;

@end

