//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface AliTradeCombinationItemsButton : UIView
{
    UILabel *_label;
    UIImageView *_icon;
}

@property(retain, nonatomic) UIImageView *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (struct CGSize)resizeSelf;
- (void)setTitle:(id)arg1 icon:(id)arg2 color:(id)arg3 borderColor:(id)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

@end

