//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSArray, NSDictionary, NSString;
@protocol AliTradeCombinationItemsSingleItemModel;

@interface AliTradeCombinationItemsModel : TBJSONModel
{
    NSArray<AliTradeCombinationItemsSingleItemModel> *_bundleItemList;
    NSDictionary *_bundleSkuMap;
    NSString *_buyText;
    NSString *_cartText;
}

@property(copy, nonatomic) NSString *cartText; // @synthesize cartText=_cartText;
@property(copy, nonatomic) NSString *buyText; // @synthesize buyText=_buyText;
@property(retain, nonatomic) NSDictionary *bundleSkuMap; // @synthesize bundleSkuMap=_bundleSkuMap;
@property(retain, nonatomic) NSArray<AliTradeCombinationItemsSingleItemModel> *bundleItemList; // @synthesize bundleItemList=_bundleItemList;
- (void).cxx_destruct;

@end

