//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AMPFileTask.h"

@interface AMPFileDownloadTask : AMPFileTask
{
    _Bool _bImage;
    struct CGSize _rect;
}

@property(nonatomic) struct CGSize rect; // @synthesize rect=_rect;
@property(nonatomic) _Bool bImage; // @synthesize bImage=_bImage;

@end

