//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "ATSBaseRequest-Protocol.h"
#import "ATSCommandChainProtocol-Protocol.h"

@class NSDictionary, NSString;

@interface ATSBaseRequest : NSObject <ATSBaseRequest, ATSCommandChainProtocol>
{
    double _startTime;
    double _endTime;
    NSString *_client;
    unsigned long long _actionType;
    NSDictionary *_userInfo;
    NSDictionary *_dataParam;
}

@property(retain, nonatomic) NSDictionary *dataParam; // @synthesize dataParam=_dataParam;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) unsigned long long actionType; // @synthesize actionType=_actionType;
@property(nonatomic) NSString *client; // @synthesize client=_client;
@property(nonatomic) double endTime; // @synthesize endTime=_endTime;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
- (void).cxx_destruct;
- (id)userInfoForNextCommand;
- (id)nextCommandId;
- (void)invokeCommand;
- (id)actionName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

