//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "ATEventInterceptProtocol-Protocol.h"
#import "AliLaucherDataProtocal-Protocol.h"
#import "TBAppLaunchProtocol-Protocol.h"
#import "UTExposureViewProtocol-Protocol.h"

@class ATConfigManager, ATTrackerStatInfo, NSString, SRERuleEngine;
@protocol ATTrackerClickProtocol, UTExposureViewProtocol;

@interface ATTrackerManager : NSObject <ATEventInterceptProtocol, UTExposureViewProtocol, TBAppLaunchProtocol, AliLaucherDataProtocal>
{
    _Bool _isOpenSwitch;
    _Bool _isOpenSwitchSyncWithOrange;
    ATConfigManager *_configManager;
    id <UTExposureViewProtocol> _exposureViewHandler;
    id <ATTrackerClickProtocol> _clickHandler;
    SRERuleEngine *_ruleEngine;
    ATTrackerStatInfo *_trackerStatInfo;
}

+ (id)sharedManager;
@property(nonatomic) _Bool isOpenSwitchSyncWithOrange; // @synthesize isOpenSwitchSyncWithOrange=_isOpenSwitchSyncWithOrange;
@property(nonatomic) _Bool isOpenSwitch; // @synthesize isOpenSwitch=_isOpenSwitch;
@property(retain, nonatomic) ATTrackerStatInfo *trackerStatInfo; // @synthesize trackerStatInfo=_trackerStatInfo;
@property(retain, nonatomic) SRERuleEngine *ruleEngine; // @synthesize ruleEngine=_ruleEngine;
@property(retain, nonatomic) id <ATTrackerClickProtocol> clickHandler; // @synthesize clickHandler=_clickHandler;
@property(retain, nonatomic) id <UTExposureViewProtocol> exposureViewHandler; // @synthesize exposureViewHandler=_exposureViewHandler;
@property(retain, nonatomic) ATConfigManager *configManager; // @synthesize configManager=_configManager;
- (void).cxx_destruct;
- (id)exposureViewPropertiesWithView:(id)arg1 andUrl:(id)arg2;
- (id)exposureViewTagWithView:(id)arg1 andUrl:(id)arg2;
- (_Bool)shouldExposeView:(id)arg1 withUrl:(id)arg2;
- (void)handleLaucherData:(id)arg1;
- (void)homePageDidFinishLaunchingWithConfiguration:(id)arg1;
- (void)appDidFinishLaunchingWithConfiguration:(id)arg1;
- (void)extraGestureRecognizerHandler:(id)arg1;
- (void)addGestureHandlerForView:(id)arg1;
- (void)addGestureHandlerIfNeededForView:(id)arg1;
- (void)utPerformanceForView:(id)arg1 pageTrackerId:(id)arg2 beginTime:(double)arg3;
- (id)getUserId;
- (void)exposePerformanceForView:(id)arg1 beginTime:(double)arg2 commitCost:(double)arg3;
- (_Bool)hasConfigOfView:(id)arg1 pageTrackerId:(id)arg2 type:(id)arg3;
- (_Bool)isTargetView:(id)arg1;
- (_Bool)shouldInterceptClickEventOfView:(id)arg1;
- (_Bool)shouldInterceptExposureEventOfView:(id)arg1;
- (_Bool)shouldInterceptEventOfView:(id)arg1 touchPhase:(long long)arg2;
- (_Bool)isSupportTrack:(id)arg1;
- (void)stopDynamicTrack:(id)arg1;
- (_Bool)isInBucket;
- (_Bool)isOpenSwitchFromOrange;
- (_Bool)isDynamicTrackSwitchOn;
- (void)startDynamicTrack:(id)arg1 config:(id)arg2;
- (void)groupConfigATTrack:(id)arg1;
- (void)tearDown;
- (void)setUp;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

