//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CNLogisticsDetailCell.h"

@class CNLogisticsDetailCuntaoModel, UILabel;

@interface CNLogisticsDetailCuntaoView : CNLogisticsDetailCell
{
    UILabel *_nameLabel;
    UILabel *_officeTimeLabel;
    UILabel *_officeTimeTitleLabel;
    UILabel *_addressLabel;
}

@property(nonatomic) __weak UILabel *addressLabel; // @synthesize addressLabel=_addressLabel;
@property(nonatomic) __weak UILabel *officeTimeTitleLabel; // @synthesize officeTimeTitleLabel=_officeTimeTitleLabel;
@property(nonatomic) __weak UILabel *officeTimeLabel; // @synthesize officeTimeLabel=_officeTimeLabel;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)phone:(id)arg1;
- (void)info:(id)arg1;
- (void)updateModel;
- (void)initModel;

// Remaining properties
@property(retain, nonatomic) CNLogisticsDetailCuntaoModel *cellModel; // @dynamic cellModel;

@end

