//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface FaceRecordService : NSObject
{
    NSMutableDictionary *_recordDataDict;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *recordDataDict; // @synthesize recordDataDict=_recordDataDict;
- (void).cxx_destruct;
- (void)record:(id)arg1 withException:(id)arg2;
- (void)record:(id)arg1 withData:(id)arg2;
- (int)increaseForKey:(id)arg1;
- (void)copyData:(id)arg1 toDict:(id)arg2;

@end

