//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface MCBaseHandlerImp : NSObject
{
    NSMutableDictionary *_selDics;
}

+ (void)registerHandlers:(id)arg1;
@property(readonly, nonatomic) NSMutableDictionary *selDics; // @synthesize selDics=_selDics;
- (void).cxx_destruct;
- (id)routeWithUrl:(id)arg1 withQuery:(id)arg2 parameters:(id)arg3;
- (id)init;

@end

