//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "MCGroupChatHeaderViewProtocol-Protocol.h"

@class MCGroupChatHeaderViewVO, NSString, UIImageView;

@interface MCGroupChatHeaderView : UIView <MCGroupChatHeaderViewProtocol>
{
    UIImageView *_headerImageView;
    UIView *_imageViewGradient;
    MCGroupChatHeaderViewVO *_vo;
    UIView *_titleNavibar;
    long long _statusBarStyle;
}

@property(nonatomic) long long statusBarStyle; // @synthesize statusBarStyle=_statusBarStyle;
@property(retain, nonatomic) UIView *titleNavibar; // @synthesize titleNavibar=_titleNavibar;
@property(retain) MCGroupChatHeaderViewVO *vo; // @synthesize vo=_vo;
- (void).cxx_destruct;
- (void)viewWillAppear:(_Bool)arg1;
- (double)getHeight;
- (void)reloadTitleBarSize;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateAlpha;
- (void)addDelegate:(id)arg1;
- (void)layoutSubviews;
- (void)updateBarWithTitle:(id)arg1 count:(unsigned long long)arg2 headerLabel:(id)arg3;
- (void)updateBarWithTitle:(id)arg1 count:(unsigned long long)arg2;
- (void)updateBarContentColor;
- (id)initWithGroupChatHeaderViewVO:(id)arg1 fragmentView:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

