//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "MCPacketBodyProtocol-Protocol.h"

@class NSString;

@interface MCPacketBody : NSObject <MCPacketBodyProtocol>
{
    id _typeData;
    id _formatData;
    id _layoutData;
}

@property(retain, nonatomic) id layoutData; // @synthesize layoutData=_layoutData;
@property(retain, nonatomic) id formatData; // @synthesize formatData=_formatData;
@property(retain, nonatomic) id typeData; // @synthesize typeData=_typeData;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

