//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MCDataSourceProtocol-Protocol.h"

@class NSArray, NSDate, NSString;
@protocol MCRecentContactDataSourceDelegate, MCSessionDO;

@protocol MCRecentContactDataSourceProtocol <MCDataSourceProtocol>
@property(nonatomic) int status;
- (void)updateSession:(NSString *)arg1 sessionType:(int)arg2 visitTime:(NSDate *)arg3;
- (void)saveDraft:(NSString *)arg1 sessionType:(int)arg2 draft:(NSString *)arg3;
- (void)clearSessionMessage:(NSString *)arg1 sessionType:(int)arg2;
- (void)updateSession:(NSString *)arg1 sessionType:(int)arg2 remindType:(int)arg3;
- (void)updateSession:(NSString *)arg1 sessionType:(int)arg2 andIsRemind:(_Bool)arg3;
- (_Bool)leaveSession:(NSString *)arg1 sessionType:(int)arg2;
- (_Bool)enterSession:(NSString *)arg1 sessionType:(int)arg2;
- (void)batchClearSessionUnreadCount:(NSArray *)arg1;
- (void)clearSessionUnreadCount:(NSString *)arg1 sessionType:(int)arg2;
- (_Bool)removeSession:(NSString *)arg1 sessionType:(int)arg2;
- (void)updateSessions;
- (id <MCSessionDO>)getSessionById:(NSString *)arg1 sessionType:(int)arg2;
- (void)mergeSessionsWithMergeKey:(NSString *)arg1;
- (void)sessions;
- (long long)maxLastMessageTime;
- (long long)totalUnreacCount;
- (void)removeDataSourceDelegate:(id <MCRecentContactDataSourceDelegate>)arg1;
- (void)addDataSourceDelegate:(id <MCRecentContactDataSourceDelegate>)arg1;
@end

