//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSString, NSURLConnection, NWPolicyResult;

@interface NWHttpDetector : NSObject
{
    int _status;
    NSArray *_policies;
    NWPolicyResult *_currentPolicy;
    unsigned long long _policyIndex;
    NSURLConnection *_connection;
    NSString *_scheme;
    NSString *_host;
}

+ (id)detectionKey:(id)arg1 scheme:(id)arg2;
+ (void)reset:(id)arg1 scheme:(id)arg2;
+ (id)availablePolicy:(id)arg1 scheme:(id)arg2;
+ (void)initialize;
@property(retain, nonatomic) NSString *host; // @synthesize host=_host;
@property(retain, nonatomic) NSString *scheme; // @synthesize scheme=_scheme;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
@property(nonatomic) unsigned long long policyIndex; // @synthesize policyIndex=_policyIndex;
@property(retain, nonatomic) NWPolicyResult *currentPolicy; // @synthesize currentPolicy=_currentPolicy;
@property(retain, nonatomic) NSArray *policies; // @synthesize policies=_policies;
@property int status; // @synthesize status=_status;
- (void).cxx_destruct;
- (id)description;
- (void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)completeDetection;
- (void)sendDetection:(id)arg1 scheme:(id)arg2;
- (void)start;
- (id)initWithHost:(id)arg1 withScheme:(id)arg2;

@end

