//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@protocol OS_dispatch_source;

@interface NWTimer : NSObject
{
    _Bool _yesOrNo;
    NSObject<OS_dispatch_source> *_timer;
    id _aTarget;
    SEL _aSelector;
    id _userInfo;
}

+ (id)scheduledTimerWithTimeInterval:(double)arg1 target:(id)arg2 selector:(SEL)arg3 userInfo:(id)arg4 repeats:(_Bool)arg5;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) _Bool yesOrNo; // @synthesize yesOrNo=_yesOrNo;
@property(nonatomic) SEL aSelector; // @synthesize aSelector=_aSelector;
@property(nonatomic) __weak id aTarget; // @synthesize aTarget=_aTarget;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *timer; // @synthesize timer=_timer;
- (void).cxx_destruct;
- (void)dealloc;
- (void)invalidate;
- (id)initWithTimeInterval:(double)arg1 target:(id)arg2 selector:(SEL)arg3 userInfo:(id)arg4 repeats:(_Bool)arg5;

@end

