//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface TBCProtocolHandleFactory : NSObject
{
    NSMutableDictionary *_handles;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *handles; // @synthesize handles=_handles;
- (void).cxx_destruct;
- (void)removeHandlerForProtocol:(id)arg1 engineId:(id)arg2;
- (void)removeHandlerForEngine:(id)arg1;
- (id)handleForProtocol:(id)arg1 engineId:(id)arg2;
- (void)registerProtocol:(id)arg1 handler:(id)arg2 engineId:(id)arg3;
- (id)init;

@end

