//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class UIImageView, UIView;

@interface TBDialog : NSObject
{
    _Bool _animationRunning;
    UIView *_bgView;
    UIView *_moveView;
    UIImageView *_closeImageView;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool animationRunning; // @synthesize animationRunning=_animationRunning;
@property(retain, nonatomic) UIImageView *closeImageView; // @synthesize closeImageView=_closeImageView;
@property(retain, nonatomic) UIView *moveView; // @synthesize moveView=_moveView;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
- (void).cxx_destruct;
- (void)handleTapClose:(id)arg1;
- (void)hide;
- (void)showWithView:(id)arg1;
- (void)startDisappearAnimation:(id)arg1;
- (void)startAppearAnimation:(id)arg1;
- (void)layoutView:(id)arg1;

@end

