//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBChatViewController.h"

#import "MCRecentContactDataSourceDelegate-Protocol.h"
#import "TBIMRelationServiceDelegate-Protocol.h"
#import "TBIMUserServiceDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class MCChatAddFriendsNoticePlugin, MCChatMessageNoticePlugin, MCDecorateTemplate, MCShopInfoPlugin, NSDictionary, NSString, UIButton, UIImageView, UILabel, UIView;
@protocol MCRecentContactDataSourceProtocol, MCSessionDO, TBIMUserAdapter;

@interface TBIMChatViewController : TBChatViewController <UIActionSheetDelegate, UIAlertViewDelegate, TBIMRelationServiceDelegate, MCRecentContactDataSourceDelegate, TBIMUserServiceDelegate>
{
    UIButton *_cleanTipView;
    UIView *_firstTipView;
    UIImageView *_backgroundImage;
    UILabel *_tipLabel;
    unsigned long long _bizSubId;
    _Bool _hasLoadFamilyComponent;
    NSString *_reciverId;
    id <TBIMUserAdapter> _receiver;
    UIImageView *_headView;
    MCChatMessageNoticePlugin *_messageNoticePlugin;
    MCChatAddFriendsNoticePlugin *_addFriendsNoticePlugin;
    id <MCRecentContactDataSourceProtocol> _sessionDatasource;
    id <MCSessionDO> _session;
    MCShopInfoPlugin *_shopInfoPlugin;
    MCDecorateTemplate *_template;
    NSString *_jumpURLString;
    NSDictionary *_ext;
}

@property(retain, nonatomic) NSDictionary *ext; // @synthesize ext=_ext;
@property(nonatomic) _Bool hasLoadFamilyComponent; // @synthesize hasLoadFamilyComponent=_hasLoadFamilyComponent;
@property(copy, nonatomic) NSString *jumpURLString; // @synthesize jumpURLString=_jumpURLString;
@property(retain, nonatomic) MCDecorateTemplate *template; // @synthesize template=_template;
@property(retain, nonatomic) MCShopInfoPlugin *shopInfoPlugin; // @synthesize shopInfoPlugin=_shopInfoPlugin;
@property(retain, nonatomic) id <MCSessionDO> session; // @synthesize session=_session;
@property(retain, nonatomic) id <MCRecentContactDataSourceProtocol> sessionDatasource; // @synthesize sessionDatasource=_sessionDatasource;
@property(retain, nonatomic) MCChatAddFriendsNoticePlugin *addFriendsNoticePlugin; // @synthesize addFriendsNoticePlugin=_addFriendsNoticePlugin;
@property(retain, nonatomic) MCChatMessageNoticePlugin *messageNoticePlugin; // @synthesize messageNoticePlugin=_messageNoticePlugin;
@property(retain, nonatomic) UIImageView *headView; // @synthesize headView=_headView;
@property(retain, nonatomic) id <TBIMUserAdapter> receiver; // @synthesize receiver=_receiver;
@property(copy, nonatomic) NSString *reciverId; // @synthesize reciverId=_reciverId;
- (void).cxx_destruct;
- (void)sendEvent:(id)arg1;
- (void)templateMenuAction;
- (void)loadFamilyTemplate;
- (void)loadLifeRangeTemplate:(id)arg1;
- (void)loadLifeRangeTemplate;
- (void)loadTemplate;
- (void)addFamilyBackgroundComponent:(id)arg1;
- (void)addFamilyPannelUpperDataSouce:(id)arg1;
- (void)addNavBtWithComponent:(id)arg1;
- (void)addInputExIconWithComponent:(id)arg1;
- (void)addInputExWithComponent:(id)arg1;
- (void)addLifeRangeShopInfoPluginWithComponent:(id)arg1;
- (void)sessionChange:(id)arg1;
- (void)sessionAdd:(id)arg1;
- (void)friendDeleteIsSuccess:(_Bool)arg1 userId:(id)arg2 error:(id)arg3;
- (void)taoFriendDataUpdate:(id)arg1;
- (void)UserChange:(id)arg1;
- (void)gotoChatProfile:(id)arg1;
- (void)gotoDarenPage:(id)arg1;
- (void)gotoDarenProfile:(id)arg1;
- (void)gotoShareItem:(id)arg1;
- (void)configTitleView;
- (void)setNavibarRightItem;
- (void)setupNavigation;
- (void)changePageName:(id)arg1 moduleSPM:(id)arg2;
- (void)updateNaviBar;
- (void)handleSingleTap:(id)arg1;
- (void)addNewUserTip;
- (void)showIsFriend;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)doPageConfigSpmStatistic:(id)arg1;
- (id)initWithNavigatorURL:(id)arg1 query:(id)arg2 nativeParams:(id)arg3;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

