//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary, NSString, UIView;

@interface TBLiveWebViewModel : NSObject
{
    _Bool _renderSuccess;
    _Bool _isModal;
    _Bool _hideWhenClickModal;
    _Bool _loadingAnimate;
    _Bool _hidden;
    NSString *_url;
    UIView *_actionView;
    UIView *_baseView;
    UIView *_renderView;
    NSString *_rendType;
    unsigned long long _enterAnimationType;
    unsigned long long _exitAnimationType;
    long long _fireEvents;
    NSString *_trackInfo;
    NSDictionary *_weexDict;
    struct CGRect _frame;
}

@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
@property(retain, nonatomic) NSDictionary *weexDict; // @synthesize weexDict=_weexDict;
@property(retain, nonatomic) NSString *trackInfo; // @synthesize trackInfo=_trackInfo;
@property(nonatomic) _Bool loadingAnimate; // @synthesize loadingAnimate=_loadingAnimate;
@property(nonatomic) _Bool hideWhenClickModal; // @synthesize hideWhenClickModal=_hideWhenClickModal;
@property(nonatomic) _Bool isModal; // @synthesize isModal=_isModal;
@property(nonatomic) long long fireEvents; // @synthesize fireEvents=_fireEvents;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(nonatomic) unsigned long long exitAnimationType; // @synthesize exitAnimationType=_exitAnimationType;
@property(nonatomic) unsigned long long enterAnimationType; // @synthesize enterAnimationType=_enterAnimationType;
@property(retain, nonatomic) NSString *rendType; // @synthesize rendType=_rendType;
@property(nonatomic) _Bool renderSuccess; // @synthesize renderSuccess=_renderSuccess;
@property(retain, nonatomic) UIView *renderView; // @synthesize renderView=_renderView;
@property(retain, nonatomic) UIView *baseView; // @synthesize baseView=_baseView;
@property(retain, nonatomic) UIView *actionView; // @synthesize actionView=_actionView;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (id)bottomView;

@end

