//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "TBLiveInterLifeCycleProtocol-Protocol.h"
#import "TBLiveInterRenderProtocol-Protocol.h"

@class NSMutableArray, NSString;

@interface TBLiveInterComponentController : NSObject <TBLiveInterLifeCycleProtocol, TBLiveInterRenderProtocol>
{
    NSString *_bizcode;
    NSMutableArray *_componentArray;
}

@property(retain, nonatomic) NSMutableArray *componentArray; // @synthesize componentArray=_componentArray;
@property(copy, nonatomic) NSString *bizcode; // @synthesize bizcode=_bizcode;
- (void).cxx_destruct;
- (void)didRenderViewFailure:(id)arg1;
- (void)didRenderViewSuccess:(id)arg1 view:(id)arg2;
- (void)removeAllComponent;
- (void)removeComponent:(id)arg1;
- (void)createComponentWithURL:(id)arg1 type:(id)arg2 messageId:(id)arg3 topic:(id)arg4 model:(id)arg5 vc:(id)arg6;
- (void)createComponent:(id)arg1 topic:(id)arg2 model:(id)arg3 viewController:(id)arg4;
- (void)didDestroy;
- (void)didCreate;
- (void)dealloc;
- (void)setupInit;
- (id)initWithBizcode:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

