//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSString;

@interface TBLiveRewardTaskItemModel : TBJSONModel
{
    NSString *_exchangeOrderId;
    NSString *_activityId;
    NSString *_point;
}

@property(copy, nonatomic) NSString *point; // @synthesize point=_point;
@property(copy, nonatomic) NSString *activityId; // @synthesize activityId=_activityId;
@property(copy, nonatomic) NSString *exchangeOrderId; // @synthesize exchangeOrderId=_exchangeOrderId;
- (void).cxx_destruct;

@end

