//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBOrderComponent.h"

@interface TBOrderStatusComponent : TBOrderComponent
{
}

- (id)bgColorEnd;
- (id)bgColorStart;
- (_Bool)openGradient;
- (_Bool)rainbowBar;
- (id)bgColor;
- (id)style;
- (id)extra;
- (id)flagPic;
- (id)title;
- (id)code;
- (id)text;

@end

