//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBCBaseComponent.h"

@class TBCComponentContext, TBCTextLabelComponent, UIImageView;

@interface TBRDShopkeeperReplyComponent : TBCBaseComponent
{
    UIImageView *_ivBack;
    TBCTextLabelComponent *_textLabel;
    TBCComponentContext *_ct;
}

+ (id)defaultStyle;
+ (id)componentTag;
@property(retain, nonatomic) TBCComponentContext *ct; // @synthesize ct=_ct;
@property(retain, nonatomic) TBCTextLabelComponent *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) UIImageView *ivBack; // @synthesize ivBack=_ivBack;
- (void).cxx_destruct;
- (void)loadContext:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

