//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBRecmdCardModel.h"

@class TBRecmdPicComponent;

@interface TBRecmdHeaderCardModel : TBRecmdCardModel
{
    TBRecmdPicComponent *_mainIcon;
}

+ (id)factoryKey;
@property(retain, nonatomic) TBRecmdPicComponent *mainIcon; // @synthesize mainIcon=_mainIcon;
- (void).cxx_destruct;
- (id)bgImgUrl;

@end

