//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TBSCSFilter : NSObject
{
}

+ (id)richTextImage:(id)arg1;
+ (void)registerEmotionFilterForEngine:(id)arg1;
+ (id)textTransfer:(id)arg1;
+ (id)changeLikeStatus:(id)arg1 args:(id)arg2;
+ (id)displayLikeNum:(id)arg1;
+ (id)displayCommentNum:(id)arg1;
+ (void)registerRichTextImageFilterForEngine:(id)arg1;
+ (void)registerInteractFilterForEngine:(id)arg1;

@end

