//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSRecursiveLock, NSString;

@interface TBSDKPushCenterConfiguration : NSObject
{
    NSMutableArray *_accsHostArray;
    NSRecursiveLock *_lock;
    int _envrionment;
    _Bool _isUseSecurityGuard;
    NSString *_pushUserToken;
    NSString *_appKey;
    NSString *_appSecret;
    NSString *_deviceID;
    NSString *_customAppVersion;
}

+ (void)setLogLevelWithPushSDK:(int)arg1 withAccsSDK:(int)arg2 withNetworkSDK:(int)arg3;
+ (id)getSDKVersion;
+ (id)shareInstance;
@property(nonatomic) _Bool isUseSecurityGuard; // @synthesize isUseSecurityGuard=_isUseSecurityGuard;
@property(retain, nonatomic) NSString *customAppVersion; // @synthesize customAppVersion=_customAppVersion;
@property(retain, nonatomic) NSString *deviceID; // @synthesize deviceID=_deviceID;
@property(retain, nonatomic) NSString *appSecret; // @synthesize appSecret=_appSecret;
@property(retain, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
- (void).cxx_destruct;
- (void)setEnvrionment:(int)arg1;
- (void)setAccsHost:(id)arg1 withDebugHost:(id)arg2 withDailyHost:(id)arg3;
- (id)currentAccsHost;
@property(retain, nonatomic) NSString *pushUserToken; // @synthesize pushUserToken=_pushUserToken;
- (id)init;

@end

