//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSDate, NSTimer;
@protocol TBShopCountdownViewDelegate;

@interface TBShopCountdownView : UIView
{
    NSTimer *tickTimer;
    _Bool _running;
    NSDate *_targetDate;
    id <TBShopCountdownViewDelegate> _delegate;
}

@property(nonatomic) __weak id <TBShopCountdownViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool running; // @synthesize running=_running;
@property(retain, nonatomic) NSDate *targetDate; // @synthesize targetDate=_targetDate;
- (void).cxx_destruct;
- (void)didMoveToWindow;
- (void)willMoveToWindow:(id)arg1;
- (void)finish;
- (void)updateDigit;
- (void)tick;
- (void)offTickTimer;
- (void)onTickTimer;
- (_Bool)valid;
- (void)setDigit:(long long)arg1 forViewType:(unsigned long long)arg2;
- (void)setDigit:(long long)arg1 forViewIndex:(unsigned long long)arg2;
- (struct CGSize)intrinsicContentSize;
- (void)renderView;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

