//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface TBShopTabStyleModel : NSObject
{
    _Bool _gradient;
    NSString *_titleColor;
    NSString *_selectedTitleColor;
    NSString *_bgColor;
    NSString *_selectedBgColor;
    NSString *_indicatorColor;
}

@property(nonatomic) _Bool gradient; // @synthesize gradient=_gradient;
@property(retain, nonatomic) NSString *indicatorColor; // @synthesize indicatorColor=_indicatorColor;
@property(retain, nonatomic) NSString *selectedBgColor; // @synthesize selectedBgColor=_selectedBgColor;
@property(retain, nonatomic) NSString *bgColor; // @synthesize bgColor=_bgColor;
@property(retain, nonatomic) NSString *selectedTitleColor; // @synthesize selectedTitleColor=_selectedTitleColor;
@property(retain, nonatomic) NSString *titleColor; // @synthesize titleColor=_titleColor;
- (void).cxx_destruct;
- (id)initWithData:(id)arg1;

@end

