//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIButton;
@protocol TBSNSTopicPostPhotoAreaViewDelegate;

@interface TBSNSTopicPostPhotoAreaView : UIView
{
    id <TBSNSTopicPostPhotoAreaViewDelegate> _delegate;
    NSArray *_preSelectedPhotoModels;
    UIButton *_addPhotoButton;
}

@property(retain, nonatomic) UIButton *addPhotoButton; // @synthesize addPhotoButton=_addPhotoButton;
@property(retain, nonatomic) NSArray *preSelectedPhotoModels; // @synthesize preSelectedPhotoModels=_preSelectedPhotoModels;
@property(nonatomic) __weak id <TBSNSTopicPostPhotoAreaViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layout;
- (void)layoutSubviews;
- (id)selectedPhotoModels;
- (void)addImage:(id)arg1 model:(id)arg2;
- (void)removePhotoWithImageView:(id)arg1;
- (void)singlePhotoViewClick:(id)arg1;
- (void)deleteButtonClick:(id)arg1;
- (void)addPhotoButtonClick:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

