//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBTradeSelectModel.h"

@class TBTradeShipDatePickerModel;

@interface TBTradeDeliveryMethodModel : TBTradeSelectModel
{
    TBTradeShipDatePickerModel *_shipDatePickerModel;
}

@property(retain, nonatomic) TBTradeShipDatePickerModel *shipDatePickerModel; // @synthesize shipDatePickerModel=_shipDatePickerModel;
- (void).cxx_destruct;
- (void)setEngine:(id)arg1;
- (void)setSelectedId:(id)arg1;
- (void)loadOptionArray:(id)arg1;

@end

