//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface TBXSearchConfig : NSObject
{
    NSMutableDictionary *_outterConfig;
    NSMutableDictionary *_resultConfig;
    NSMutableDictionary *_origConfig;
}

@property(retain, nonatomic) NSMutableDictionary *origConfig; // @synthesize origConfig=_origConfig;
@property(retain, nonatomic) NSMutableDictionary *resultConfig; // @synthesize resultConfig=_resultConfig;
@property(retain, nonatomic) NSMutableDictionary *outterConfig; // @synthesize outterConfig=_outterConfig;
- (void).cxx_destruct;
- (id)defaultSearchBarType;
- (id)getWfLayoutConfig;
- (id)getListLayoutConfig;
- (id)getChituConfig;
- (id)getRequestServiceConfig;
- (id)getWeexConfig;
- (void)setConfigValue:(id)arg1 ForKey:(id)arg2;
- (id)origConfigValueForKey:(id)arg1;
- (id)getAllConfig;
- (void)setOutterConfigValue:(id)arg1 forKey:(id)arg2;
- (id)init;

@end

