//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface TidaBeaconInfo : NSObject
{
    NSString *_type;
    long long _bluetooth;
    long long _gps;
}

@property(nonatomic) long long gps; // @synthesize gps=_gps;
@property(nonatomic) long long bluetooth; // @synthesize bluetooth=_bluetooth;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

