//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSDate, NSNumber, NSString;

@interface WWDBUserDefaults : NSManagedObject
{
}

+ (id)fetchRequest;

// Remaining properties
@property(copy, nonatomic) NSDate *wwdbDateValue; // @dynamic wwdbDateValue;
@property(copy, nonatomic) NSString *wwdbKey; // @dynamic wwdbKey;
@property(copy, nonatomic) NSNumber *wwdbNumValue; // @dynamic wwdbNumValue;
@property(copy, nonatomic) NSString *wwdbStringValue; // @dynamic wwdbStringValue;

@end

