//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIScrollViewDelegate-Protocol.h"
#import "XSearchSDKChildBaseViewControllerDelegate-Protocol.h"
#import "XSearchScrollViewProxyDelegate-Protocol.h"
#import "XSearchTabContentProtocol-Protocol.h"

@class NSString, UIScrollView, UIView, XSearchContext, XSearchCoordinativeScrollContainerManager, XSearchHeaderView, XSearchScrollViewProxy, XSearchService, XSearchSingleContainerView, XSearchTabContentComponent;
@protocol XSearchSDKDelegate;

@interface XSearchSDKViewController : UIViewController <XSearchTabContentProtocol, XSearchSDKChildBaseViewControllerDelegate, UIScrollViewDelegate, XSearchScrollViewProxyDelegate>
{
    _Bool _resetScrollStatusWhenDisappear;
    _Bool _openDisableAutoLayoutWhenDisappear;
    _Bool _isClickedTab;
    id <XSearchSDKDelegate> _delegate;
    UIScrollView *_mainScrollView;
    XSearchService *_searchService;
    XSearchContext *_searchContext;
    XSearchHeaderView *_headerView;
    XSearchSingleContainerView *_themeView;
    UIView *_wrapperView;
    UIView *_statusBarPlaceHolderView;
    UIScrollView *_childScrollView;
    XSearchTabContentComponent *_tabContentComponent;
    XSearchCoordinativeScrollContainerManager *_coordinativeScrollContainerManager;
    XSearchScrollViewProxy *_childScrollViewProxy;
    XSearchSingleContainerView *_emptyView;
    XSearchSingleContainerView *_errorView;
    XSearchSingleContainerView *_loadingView;
}

@property(retain, nonatomic) XSearchSingleContainerView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) XSearchSingleContainerView *errorView; // @synthesize errorView=_errorView;
@property(retain, nonatomic) XSearchSingleContainerView *emptyView; // @synthesize emptyView=_emptyView;
@property(nonatomic) _Bool isClickedTab; // @synthesize isClickedTab=_isClickedTab;
@property(retain, nonatomic) XSearchScrollViewProxy *childScrollViewProxy; // @synthesize childScrollViewProxy=_childScrollViewProxy;
@property(retain, nonatomic) XSearchCoordinativeScrollContainerManager *coordinativeScrollContainerManager; // @synthesize coordinativeScrollContainerManager=_coordinativeScrollContainerManager;
@property(retain, nonatomic) XSearchTabContentComponent *tabContentComponent; // @synthesize tabContentComponent=_tabContentComponent;
@property(retain, nonatomic) UIScrollView *childScrollView; // @synthesize childScrollView=_childScrollView;
@property(retain, nonatomic) UIView *statusBarPlaceHolderView; // @synthesize statusBarPlaceHolderView=_statusBarPlaceHolderView;
@property(retain, nonatomic) UIView *wrapperView; // @synthesize wrapperView=_wrapperView;
@property(nonatomic) _Bool openDisableAutoLayoutWhenDisappear; // @synthesize openDisableAutoLayoutWhenDisappear=_openDisableAutoLayoutWhenDisappear;
@property(retain, nonatomic) XSearchSingleContainerView *themeView; // @synthesize themeView=_themeView;
@property(retain, nonatomic) XSearchHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) XSearchContext *searchContext; // @synthesize searchContext=_searchContext;
@property(retain, nonatomic) XSearchService *searchService; // @synthesize searchService=_searchService;
@property(retain, nonatomic) UIScrollView *mainScrollView; // @synthesize mainScrollView=_mainScrollView;
@property(nonatomic) _Bool resetScrollStatusWhenDisappear; // @synthesize resetScrollStatusWhenDisappear=_resetScrollStatusWhenDisappear;
@property(nonatomic) __weak id <XSearchSDKDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)showChiTu;
- (void)showChiTuLogoWhenReady;
- (void)chituRun;
- (void)chiTuInit;
- (void)changeStatusViewFrame:(_Bool)arg1;
- (struct CGRect)getStatusViewFrame:(_Bool)arg1;
- (void)changeStatusViewFailForFilterSearch:(_Bool)arg1 error:(id)arg2;
- (void)changeStatusViewSuccessForFilterSearch:(_Bool)arg1 isEmpty:(_Bool)arg2;
- (void)changeStatusViewStartForFilterSearch:(_Bool)arg1;
- (void)loadStatusView;
- (void)hideStatusView;
- (void)createStatusView;
- (_Bool)enableInnerSearchBar;
- (void)disableScroll;
- (void)enableScroll;
- (double)getSearchBarViewTop;
- (void)setDefaultParser;
- (void)tabContentDidScroll:(id)arg1 positionRatio:(double)arg2;
- (void)tabContentDidEndSlidingWithIndex:(long long)arg1 ScrollView:(id)arg2;
- (void)tabContentWhenVCDidHidden:(id)arg1;
- (void)tabContentWhenVCDidShow:(id)arg1 newCreate:(_Bool)arg2;
- (void)tabContentWhenVCNewCreate:(id)arg1;
- (void)tabContentComponentChangeToIndex:(long long)arg1 searchService:(id)arg2;
- (void)bindSearchServiceWhenChangeTab:(id)arg1;
- (void)childVCH5FindishLoad:(id)arg1;
- (void)childVCScrollToTop;
- (void)childVCSearchFailed:(id)arg1 Error:(id)arg2;
- (void)childVCSearchSuccess:(id)arg1;
- (void)childVCSearchStart:(id)arg1;
- (void)fixSearchFail:(id)arg1;
- (void)fixSearchSuccess;
- (void)fixSearchStart;
- (void)contract:(id)arg1;
- (void)expand:(id)arg1;
- (void)scrollViewProxyDidScroll:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setCoordinativeHeaderView;
- (double)getScrollBorderValue;
- (void)dealloc;
- (void)disableAutoLayoutWhenDisappear;
- (void)addEvents;
- (void)contract;
- (void)expand;
- (void)layoutContainer;
- (void)headerLayout;
- (void)showChildVCWithSearchService:(id)arg1 errorData:(id)arg2;
- (void)dataLoaded;
- (double)getHeightOfSearchBarView;
- (double)getBottomOfStickyView;
- (void)didReceiveMemoryWarning;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadCoordinativeScrollModule;
- (void)createHeaderView:(double)arg1;
- (void)viewDidLoad;
- (id)initWithQuery:(id)arg1 Service:(id)arg2 Context:(id)arg3 Delegate:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

