//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AWEBaseApiModel.h"

@class AWEURLModel, AWEUserModel, NSString;

@interface AWEAtNoticeModel : AWEBaseApiModel
{
    NSString *_title;
    NSString *_content;
    NSString *_schemaURL;
    AWEURLModel *_imageURL;
    long long _subType;
    AWEUserModel *_userInfo;
    double _contentH;
    double _nameW;
}

+ (id)userInfoJSONTransformer;
+ (id)imageURLJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(nonatomic) double nameW; // @synthesize nameW=_nameW;
@property(nonatomic) double contentH; // @synthesize contentH=_contentH;
@property(retain, nonatomic) AWEUserModel *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) long long subType; // @synthesize subType=_subType;
@property(retain, nonatomic) AWEURLModel *imageURL; // @synthesize imageURL=_imageURL;
@property(retain, nonatomic) NSString *schemaURL; // @synthesize schemaURL=_schemaURL;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

