//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class AWEUserModel, UIImageView, UILabel;

@interface AWEUserShareUtil : NSObject
{
    unsigned long long _type;
    AWEUserModel *_model;
    UIImageView *_backgroundImageView;
    UIImageView *_qrCodeImageView;
    UIImageView *_movieScreenshotImageView;
    UIImageView *_avatarImageView;
    UILabel *_userNameLabel;
    UILabel *_userIdLabel;
}

@property(retain, nonatomic) UILabel *userIdLabel; // @synthesize userIdLabel=_userIdLabel;
@property(retain, nonatomic) UILabel *userNameLabel; // @synthesize userNameLabel=_userNameLabel;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) UIImageView *movieScreenshotImageView; // @synthesize movieScreenshotImageView=_movieScreenshotImageView;
@property(retain, nonatomic) UIImageView *qrCodeImageView; // @synthesize qrCodeImageView=_qrCodeImageView;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(retain, nonatomic) AWEUserModel *model; // @synthesize model=_model;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)fetchCommonMusicShareImageView:(CDUnknownBlockType)arg1;
- (void)fetchDefaultShareImageView:(CDUnknownBlockType)arg1;
- (void)fetchShareImage:(id)arg1 forType:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;

@end

