//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface NHAccountPhoneRegistration : NSObject
{
}

+ (id)sharedInstance;
- (void)handleUserInfoResult:(id)arg1 error:(id)arg2 context:(id)arg3;
- (void)startRegisterByTicket:(id)arg1 captcha:(id)arg2 finishBlock:(CDUnknownBlockType)arg3;
- (void)startPreRegisterWithPhoneNumber:(id)arg1 code:(id)arg2 password:(id)arg3 captcha:(id)arg4 type:(long long)arg5 finishBlock:(CDUnknownBlockType)arg6;
- (void)startChangeMobileWithPhoneNumber:(id)arg1 code:(id)arg2 captcha:(id)arg3 finishBlock:(CDUnknownBlockType)arg4;
- (void)startValidateWithCode:(id)arg1 captcha:(id)arg2 type:(long long)arg3 finishBlock:(CDUnknownBlockType)arg4;
- (void)startUnbindPhoneWithCode:(id)arg1 captcha:(id)arg2 finishBlock:(CDUnknownBlockType)arg3;
- (void)startBindPhoneNumber:(id)arg1 code:(id)arg2 captcha:(id)arg3 password:(id)arg4 finishBlock:(CDUnknownBlockType)arg5;
- (void)startBindPhoneNumber:(id)arg1 code:(id)arg2 captcha:(id)arg3 finishBlock:(CDUnknownBlockType)arg4;
- (void)startChangePasswordWithPassword:(id)arg1 code:(id)arg2 captcha:(id)arg3 finishBlock:(CDUnknownBlockType)arg4;
- (void)startResetPasswordWithPhoneNumber:(id)arg1 code:(id)arg2 password:(id)arg3 captcha:(id)arg4 FinishBlock:(CDUnknownBlockType)arg5;
- (id)imageFromString:(id)arg1;
- (void)startLoginWithPhoneNumber:(id)arg1 password:(id)arg2 captcha:(id)arg3 finishBlock:(CDUnknownBlockType)arg4;
- (void)startRefreshCaptchaWithScenarioType:(long long)arg1 finishBlock:(CDUnknownBlockType)arg2;
- (void)startRegisterWithPhoneNumber:(id)arg1 code:(id)arg2 password:(id)arg3 captcha:(id)arg4 type:(long long)arg5 finishBlock:(CDUnknownBlockType)arg6;
- (void)startSendVoiceCodeWithPhoneNumber:(id)arg1 captcha:(id)arg2 type:(long long)arg3 finishBlock:(CDUnknownBlockType)arg4;
- (void)startSendCodeWithPhoneNumber:(id)arg1 captcha:(id)arg2 type:(long long)arg3 finishBlock:(CDUnknownBlockType)arg4;
@property(copy, nonatomic) NSString *draftMobile;

@end

