//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TTFQuizShowLiveRoomViewModel, TTFantasyLabel;

@interface TTFCountdownContainerView : UIView
{
    TTFQuizShowLiveRoomViewModel *_viewModel;
    TTFantasyLabel *_countdownDescribeLabel;
    TTFantasyLabel *_timeMinuteLabel;
    TTFantasyLabel *_timeColonLabel;
    TTFantasyLabel *_timeSecondLabel;
    TTFantasyLabel *_beginningLabel;
}

@property(retain, nonatomic) TTFantasyLabel *beginningLabel; // @synthesize beginningLabel=_beginningLabel;
@property(retain, nonatomic) TTFantasyLabel *timeSecondLabel; // @synthesize timeSecondLabel=_timeSecondLabel;
@property(retain, nonatomic) TTFantasyLabel *timeColonLabel; // @synthesize timeColonLabel=_timeColonLabel;
@property(retain, nonatomic) TTFantasyLabel *timeMinuteLabel; // @synthesize timeMinuteLabel=_timeMinuteLabel;
@property(retain, nonatomic) TTFantasyLabel *countdownDescribeLabel; // @synthesize countdownDescribeLabel=_countdownDescribeLabel;
@property(retain, nonatomic) TTFQuizShowLiveRoomViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (id)init;

@end

