//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SSDataOperation.h"

@class TTHttpTask;

@interface ArticleGetRemoteDataOperation : SSDataOperation
{
    TTHttpTask *_httpTask;
}

+ (id)encreptTime:(double)arg1;
+ (id)requestInfoForOperationContext:(id)arg1;
@property(retain, nonatomic) TTHttpTask *httpTask; // @synthesize httpTask=_httpTask;
- (void).cxx_destruct;
- (void)result:(id)arg1 error:(id)arg2 userInfo:(id)arg3;
- (void)execute:(id)arg1;
- (void)cancel;
- (id)init;
- (void)dealloc;

@end

