//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, UIColor, UIFont;
@protocol UITextFieldDelegate><UITextViewDelegate;

@protocol CCUITextInput <NSObject>
@property(nonatomic, setter=ccui_setSecureTextEntry:) _Bool ccui_secureTextEntry;
@property(retain, nonatomic, setter=ccui_setFont:) UIFont *ccui_font;
@property(retain, nonatomic, setter=ccui_setTextColor:) UIColor *ccui_textColor;
@property(retain, nonatomic, setter=ccui_setPlaceholder:) NSString *ccui_placeholder;
@property(retain, nonatomic, setter=ccui_setText:) NSString *ccui_text;
- (void)ccui_setDelegate:(id <UITextFieldDelegate><UITextViewDelegate>)arg1;
@end

