//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FRThreadFooterBaseManager.h"

#import "FRThreadFooterCommonEmptyCellDelegate-Protocol.h"
#import "FRThreadFooterCommonTipCellDelegate-Protocol.h"
#import "TTCommentDetailCellDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSDictionary, NSIndexPath, NSString, TTCommentDetailReplyCommentModel, TTCommentReplyViewModel;
@protocol FRCommentRepostFooterCommentDelegate;

@interface FRCommentRepostFooterCommentManager : FRThreadFooterBaseManager <TTCommentDetailCellDelegate, UITableViewDelegate, UITableViewDataSource, FRThreadFooterCommonEmptyCellDelegate, FRThreadFooterCommonTipCellDelegate, UIActionSheetDelegate>
{
    _Bool _hasDeleteReplyPermission;
    _Bool _needRefreshLayout;
    NSDictionary *_commentTrackDictionary;
    NSString *_commentRepostID;
    NSString *_contentAuthorID;
    NSDictionary *_trackDic;
    TTCommentReplyViewModel *_replyViewModel;
    TTCommentDetailReplyCommentModel *_needDeleteCommentModel;
    NSIndexPath *_needAnimatedIndexPath;
    id <FRCommentRepostFooterCommentDelegate> _delegate;
    double _emptyCellHeight;
    double _footerViewHeight;
    double _selfLastOffset;
    double _lastMangerOffset;
    struct CGRect _containerBounds;
}

+ (id)schemaTrackForPersonalHomeSchema:(id)arg1 categoryName:(id)arg2 fromPage:(id)arg3 groupId:(id)arg4 profileUserId:(id)arg5;
@property(nonatomic) double lastMangerOffset; // @synthesize lastMangerOffset=_lastMangerOffset;
@property(nonatomic) double selfLastOffset; // @synthesize selfLastOffset=_selfLastOffset;
@property(nonatomic) double footerViewHeight; // @synthesize footerViewHeight=_footerViewHeight;
@property(nonatomic) double emptyCellHeight; // @synthesize emptyCellHeight=_emptyCellHeight;
@property(nonatomic) __weak id <FRCommentRepostFooterCommentDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool needRefreshLayout; // @synthesize needRefreshLayout=_needRefreshLayout;
@property(retain, nonatomic) NSIndexPath *needAnimatedIndexPath; // @synthesize needAnimatedIndexPath=_needAnimatedIndexPath;
@property(retain, nonatomic) TTCommentDetailReplyCommentModel *needDeleteCommentModel; // @synthesize needDeleteCommentModel=_needDeleteCommentModel;
@property(retain, nonatomic) TTCommentReplyViewModel *replyViewModel; // @synthesize replyViewModel=_replyViewModel;
@property(retain, nonatomic) NSDictionary *trackDic; // @synthesize trackDic=_trackDic;
@property(nonatomic) struct CGRect containerBounds; // @synthesize containerBounds=_containerBounds;
@property(retain, nonatomic) NSString *contentAuthorID; // @synthesize contentAuthorID=_contentAuthorID;
@property(retain, nonatomic) NSString *commentRepostID; // @synthesize commentRepostID=_commentRepostID;
@property(copy, nonatomic) NSDictionary *commentTrackDictionary; // @synthesize commentTrackDictionary=_commentTrackDictionary;
@property(nonatomic) _Bool hasDeleteReplyPermission; // @synthesize hasDeleteReplyPermission=_hasDeleteReplyPermission;
- (void).cxx_destruct;
- (void)FR_sendHalfStatusFooterImpressionsForVisibleCellsWithOffset:(double)arg1;
- (void)FR_sendShowTrackForVisibleCells;
- (void)FR_sendShowStatusTrackForShow:(_Bool)arg1;
- (_Bool)FR_scrollToIndexPath:(id)arg1;
- (void)FR_refreshData;
- (void)FR_markTopCellNeedAnimation;
- (void)FR_insertDataWithDict:(id)arg1;
- (void)FR_footerViewDidDisappear;
- (void)FR_footerViewWillDisappear;
- (void)FR_footerViewDidAppear;
- (void)FR_footerViewWillAppear;
- (void)FR_didLayoutTableView;
- (_Bool)FR_isSelfResponsible;
- (void)FR_managerDidUnResponsibleForTableView:(id)arg1 toManager:(id)arg2 withAction:(unsigned long long)arg3;
- (void)FR_managerWillUnResponsibleForTableView:(id)arg1 toManager:(id)arg2 withAction:(unsigned long long)arg3;
- (void)FR_managerDidResponsibleForTableView:(id)arg1 fromManager:(id)arg2 withAction:(unsigned long long)arg3;
- (void)FR_managerWillResponsibleWithTableView:(id)arg1 fromManager:(id)arg2 withAction:(unsigned long long)arg3;
- (void)FR_managerBeResponsibleForTableView:(id)arg1 fromManager:(id)arg2 withAction:(unsigned long long)arg3;
- (void)FR_registerTableView:(id)arg1;
- (id)commonV3TrackExtra;
- (void)trackWithEventV3:(id)arg1 extraDictionary:(id)arg2 isDoubleTrack:(_Bool)arg3;
- (void)trackWithEvent:(id)arg1 label:(id)arg2 value:(id)arg3 ext_value:(id)arg4 extraDictionary:(id)arg5;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)tt_commentCell:(id)arg1 quotedNameOnClickedWithCommentModel:(id)arg2;
- (void)tt_commentCell:(id)arg1 nameViewonClickedWithCommentModel:(id)arg2;
- (void)tt_commentCell:(id)arg1 digCommentWithCommentModel:(id)arg2;
- (void)tt_commentCell:(id)arg1 deleteCommentWithCommentModel:(id)arg2;
- (void)tt_commentCell:(id)arg1 avatarTappedWithCommentModel:(id)arg2;
- (void)tt_commentCell:(id)arg1 replyButtonClickedWithModel:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)fr_commFooterTipCell:(id)arg1 onClickForCellType:(unsigned long long)arg2 tipType:(unsigned long long)arg3;
- (unsigned long long)footerCellType;
- (void)frFooterCommonEmptyCell:(id)arg1 emptyCellType:(long long)arg2 indicateType:(long long)arg3;
@property(readonly, nonatomic) NSString *writeCommentViewPlaceholder;
- (void)p_enterProfileWithUserID:(id)arg1;
- (void)p_tryLoadMoreComments;
- (void)p_refreshComments;
- (_Bool)p_shouldShowHeaderViewInSection:(long long)arg1;
- (_Bool)p_shouldShowPlainFooterEmptyCellInSection;
- (void)p_addPullUpViewIfNeeded;
- (void)p_addObservers;
- (void)p_commonConfigure;
- (double)p_tableViewTotalContentSizeNeedInser;
- (void)p_refreshListUI;
- (void)threadForwardAndReplySuccess:(id)arg1;
- (void)themeChanged:(id)arg1;
- (void)fontSizeChanged;
- (void)keyboardDidShow;
- (void)applicationStautsBarDidRotate;
- (id)initWithCommentRepostID:(id)arg1 withContentAuthorID:(id)arg2 withContainerBounds:(struct CGRect)arg3 withFooterCommentDelegate:(id)arg4;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

