//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;

@interface FRUserRoleStructModel : JSONModel
{
    long long _role_display_type;
    NSString *_role_name;
}

@property(retain, nonatomic) NSString *role_name; // @synthesize role_name=_role_name;
@property(nonatomic) long long role_display_type; // @synthesize role_display_type=_role_display_type;
- (void).cxx_destruct;
- (void)reset;
- (id)init;

@end

