//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (TTAdditions)
- (id)ttentity_dictionaryValueForKey:(id)arg1 defalutValue:(id)arg2;
- (id)ttentity_stringValueForKey:(id)arg1 defaultValue:(id)arg2;
- (_Bool)ttentity_boolValueForKey:(id)arg1 defaultValue:(_Bool)arg2;
- (long long)ttentity_longlongValueForKey:(id)arg1 defaultValue:(long long)arg2;
- (double)ttentity_doubleValueForKey:(id)arg1 defaultValue:(double)arg2;
@end

