//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SSThemedView.h"

@class SSThemedButton, SSThemedLabel, TTAlphaThemedButton;

@interface TTAccountAlertView : SSThemedView
{
    _Bool _touchDismissEnabled;
    SSThemedView *_centerView;
    SSThemedLabel *_titleLabel;
    SSThemedLabel *_messageLabel;
    TTAlphaThemedButton *_tipBtn;
    TTAlphaThemedButton *_cancelBtn;
    SSThemedButton *_doneBtn;
    CDUnknownBlockType _tapCompletedHandler;
    CDUnknownBlockType _didDismissCompletedHandler;
}

+ (id)_attributesWithFontSize:(double)arg1 lineSpacing:(double)arg2 lineBreakMode:(long long)arg3 textAlignment:(long long)arg4;
+ (id)attributedStringWithString:(id)arg1 fontSize:(double)arg2 lineSpacing:(double)arg3 lineBreakMode:(long long)arg4 textAlignment:(long long)arg5;
@property(copy, nonatomic) CDUnknownBlockType didDismissCompletedHandler; // @synthesize didDismissCompletedHandler=_didDismissCompletedHandler;
@property(copy, nonatomic) CDUnknownBlockType tapCompletedHandler; // @synthesize tapCompletedHandler=_tapCompletedHandler;
@property(retain, nonatomic) SSThemedButton *doneBtn; // @synthesize doneBtn=_doneBtn;
@property(retain, nonatomic) TTAlphaThemedButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) TTAlphaThemedButton *tipBtn; // @synthesize tipBtn=_tipBtn;
@property(retain, nonatomic) SSThemedLabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) SSThemedLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) SSThemedView *centerView; // @synthesize centerView=_centerView;
@property(nonatomic) _Bool touchDismissEnabled; // @synthesize touchDismissEnabled=_touchDismissEnabled;
- (void).cxx_destruct;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)doneBtnTouched:(id)arg1;
- (void)cancelBtnTouched:(id)arg1;
- (void)tipBtnTouched:(id)arg1;
- (void)layoutSubviews;
- (void)doLayoutSubviews;
- (void)hide;
- (void)hideWithEventType:(long long)arg1;
- (void)showInView:(id)arg1;
- (void)show;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 message:(id)arg2 cancelBtnTitle:(id)arg3 confirmBtnTitle:(id)arg4 animated:(_Bool)arg5 tapCompletion:(CDUnknownBlockType)arg6;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

