//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;
@protocol Optional;

@interface TTAdFeedLbsModel : JSONModel
{
    NSString<Optional> *_district;
    NSString<Optional> *_street;
    NSString<Optional> *_distance;
}

@property(copy, nonatomic) NSString<Optional> *distance; // @synthesize distance=_distance;
@property(copy, nonatomic) NSString<Optional> *street; // @synthesize street=_street;
@property(copy, nonatomic) NSString<Optional> *district; // @synthesize district=_district;
- (void).cxx_destruct;

@end

