//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSTimer, TTFLiveHeartbeat;
@protocol TTFLiveTrackerDataSource;

@interface TTFLiveTracker : NSObject
{
    _Bool _hasReportFirstFrame;
    _Bool _hasCallPlay;
    id <TTFLiveTrackerDataSource> _dataSource;
    NSTimer *_timer;
    TTFLiveHeartbeat *_liveHeartbeat;
    double _fetchStartTs;
    double _callPlayTs;
    double _lastStallTime;
}

@property(nonatomic) double lastStallTime; // @synthesize lastStallTime=_lastStallTime;
@property(nonatomic) _Bool hasCallPlay; // @synthesize hasCallPlay=_hasCallPlay;
@property(nonatomic) _Bool hasReportFirstFrame; // @synthesize hasReportFirstFrame=_hasReportFirstFrame;
@property(nonatomic) double callPlayTs; // @synthesize callPlayTs=_callPlayTs;
@property(nonatomic) double fetchStartTs; // @synthesize fetchStartTs=_fetchStartTs;
@property(retain, nonatomic) TTFLiveHeartbeat *liveHeartbeat; // @synthesize liveHeartbeat=_liveHeartbeat;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) __weak id <TTFLiveTrackerDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)closePlayerTrack;
- (void)didReceivedError:(id)arg1;
- (void)endBuffering;
- (void)startBuffering;
- (void)showFirstFrame;
- (void)willPlayUrl:(id)arg1;
- (void)endFetchURL;
- (void)startFetchURL;
- (void)trackLiveEvent;
- (id)init;
- (void)dealloc;

@end

