//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;

@interface TTFTeamInviteJoinAlertView : UIView
{
    UIButton *_joinButton;
    UIView *_containerView;
    UIView *_maskView;
    CDUnknownBlockType _dismissBlock;
}

@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
@property(retain, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIButton *joinButton; // @synthesize joinButton=_joinButton;
- (void).cxx_destruct;
- (void)dismiss:(id)arg1;
- (void)dismiss;
- (void)showInView:(id)arg1 scale:(double)arg2 dismissBlock:(CDUnknownBlockType)arg3;
- (id)initWithTitle:(id)arg1 description:(id)arg2;

@end

