//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ExploreCellBase.h"

@class TTHashtagRightPicCellView;

@interface TTHashtagRightPicCell : ExploreCellBase
{
    TTHashtagRightPicCellView *_hashtagRightPicCellView;
}

+ (Class)cellViewClass;
@property(retain, nonatomic) TTHashtagRightPicCellView *hashtagRightPicCellView; // @synthesize hashtagRightPicCellView=_hashtagRightPicCellView;
- (void).cxx_destruct;
- (void)didEndDisplaying;
- (void)willDisplay;
- (id)createCellView;

@end

