//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TTLUserInfoCard.h"

@class UIImageView;

@interface TTLAudienceInfoCard : TTLUserInfoCard
{
    UIImageView *_avatarView;
}

@property(retain, nonatomic) UIImageView *avatarView; // @synthesize avatarView=_avatarView;
- (void).cxx_destruct;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)setUser:(id)arg1;
- (void)kickButtonCLicked:(id)arg1;
- (void)silenceButtonClicked:(id)arg1;
- (id)_attributedStringFromNumber:(long long)arg1;
- (void)_updateSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

