//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TTLResourceDownloadManager : NSObject
{
}

+ (id)sharedManager;
- (_Bool)removeItemAtPath:(id)arg1 error:(id *)arg2;
- (void)downloadFilterResource;
- (void)createDirAtPath:(id)arg1;
- (void)prepareResource;
- (_Bool)isResourceReady;
- (id)resourcePath;

@end

