//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TTLTracker : NSObject
{
}

+ (void)event:(id)arg1 label:(id)arg2 value:(id)arg3 extValue:(id)arg4 extValue2:(id)arg5 dict:(id)arg6;
+ (void)eventV3:(id)arg1 params:(id)arg2;

@end

