//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray;

@interface TTRelevantDurationTracker : NSObject
{
    _Bool _tracking;
    NSMutableArray *_eventArray;
}

+ (id)sharedTracker;
@property(nonatomic) _Bool tracking; // @synthesize tracking=_tracking;
@property(retain, nonatomic) NSMutableArray *eventArray; // @synthesize eventArray=_eventArray;
- (void).cxx_destruct;
- (void)sendRelevantDuration;
- (void)beginRelevantDurationTracking;
- (void)appendRelevantDurationWithDictionary:(id)arg1;
- (void)appendRelevantDurationWithGroupID:(id)arg1 itemID:(id)arg2 enterFrom:(id)arg3 categoryName:(id)arg4 stayTime:(long long)arg5 logPb:(id)arg6 answerID:(id)arg7 questionID:(id)arg8 enterFromAnswerID:(id)arg9 parentEnterFrom:(id)arg10;
- (void)appendRelevantDurationWithGroupID:(id)arg1 itemID:(id)arg2 enterFrom:(id)arg3 categoryName:(id)arg4 stayTime:(long long)arg5 logPb:(id)arg6;
- (id)init;

@end

