//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSSet;

@interface TTShareToRepostManager : NSObject
{
    NSSet *_supportActivityContentItemTypes;
    NSSet *_needShowGuideViewActivityContentItemTypes;
    NSSet *_supportActivityTypes;
    NSSet *_needShowGuideViewActivityTypes;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSSet *needShowGuideViewActivityTypes; // @synthesize needShowGuideViewActivityTypes=_needShowGuideViewActivityTypes;
@property(retain, nonatomic) NSSet *supportActivityTypes; // @synthesize supportActivityTypes=_supportActivityTypes;
@property(retain, nonatomic) NSSet *needShowGuideViewActivityContentItemTypes; // @synthesize needShowGuideViewActivityContentItemTypes=_needShowGuideViewActivityContentItemTypes;
@property(retain, nonatomic) NSSet *supportActivityContentItemTypes; // @synthesize supportActivityContentItemTypes=_supportActivityContentItemTypes;
- (void).cxx_destruct;
- (_Bool)validateWithActivityType:(long long)arg1 operationItemType:(unsigned long long)arg2;
- (id)getShareChannelWithActivityType:(long long)arg1;
- (_Bool)validateWithActivity:(id)arg1 operationIdType:(long long)arg2;
- (_Bool)validateWithActivity:(id)arg1 operationItemType:(unsigned long long)arg2;
- (id)getShareChannelWithActivity:(id)arg1;
- (id)richSpanTextForRepostSegments:(id)arg1;
- (void)shareToRepostWithActivityType:(long long)arg1 repostType:(unsigned long long)arg2 operationItemType:(unsigned long long)arg3 operationItemID:(id)arg4 originArticle:(id)arg5 originThread:(id)arg6 originShortVideoOriginalData:(id)arg7 originWendaAnswer:(id)arg8 repostSegments:(id)arg9;
- (void)shareToRepostWithActivity:(id)arg1 withRepostParameters:(id)arg2;
- (void)shareToRepostWithActivity:(id)arg1 repostType:(unsigned long long)arg2 operationItemType:(unsigned long long)arg3 operationItemID:(id)arg4 originArticle:(id)arg5 originThread:(id)arg6 originShortVideoOriginalData:(id)arg7 originWendaAnswer:(id)arg8 repostSegments:(id)arg9;
- (void)shareToRepostWithShareChannel:(id)arg1 isNeedShowGuideViewShareChannel:(_Bool)arg2 withRepostParameters:(id)arg3;
- (void)shareToRepostWithShareChannel:(id)arg1 isNeedShowGuideViewShareChannel:(_Bool)arg2 repostType:(unsigned long long)arg3 operationItemType:(unsigned long long)arg4 operationItemID:(id)arg5 originArticle:(id)arg6 originThread:(id)arg7 originShortVideoOriginalData:(id)arg8 originWendaAnswer:(id)arg9 repostSegments:(id)arg10;
- (id)init;

@end

