//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SSThemedView.h"

#import "TTPushAlertViewProtocol-Protocol.h"

@class NSString, SSThemedButton, SSThemedImageView, SSThemedLabel, TTPushAlertModel, TTStrongPushButtonsView, TTStrongPushImagesView;

@interface TTStrongPushAlertView : SSThemedView <TTPushAlertViewProtocol>
{
    long long _deviceOrientation;
    _Bool _shouldAutorotate;
    TTPushAlertModel *_alertModel;
    CDUnknownBlockType _didTapHandler;
    CDUnknownBlockType _willHideHandler;
    CDUnknownBlockType _didHideHandler;
    SSThemedView *_containerView;
    SSThemedImageView *_volumeImageView;
    SSThemedLabel *_titleLabel;
    SSThemedLabel *_detailLabel;
    TTStrongPushImagesView *_imagesView;
    TTStrongPushButtonsView *_buttonContainerView;
    SSThemedButton *_tappedEventButton;
}

+ (_Bool)isShowing;
+ (void)hideMe;
+ (void)showMe;
+ (id)showWithAlertModel:(id)arg1 willHideBlock:(CDUnknownBlockType)arg2 didHideBlock:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) SSThemedButton *tappedEventButton; // @synthesize tappedEventButton=_tappedEventButton;
@property(retain, nonatomic) TTStrongPushButtonsView *buttonContainerView; // @synthesize buttonContainerView=_buttonContainerView;
@property(retain, nonatomic) TTStrongPushImagesView *imagesView; // @synthesize imagesView=_imagesView;
@property(retain, nonatomic) SSThemedLabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) SSThemedLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) SSThemedImageView *volumeImageView; // @synthesize volumeImageView=_volumeImageView;
@property(retain, nonatomic) SSThemedView *containerView; // @synthesize containerView=_containerView;
@property(copy, nonatomic) CDUnknownBlockType didHideHandler; // @synthesize didHideHandler=_didHideHandler;
@property(copy, nonatomic) CDUnknownBlockType willHideHandler; // @synthesize willHideHandler=_willHideHandler;
@property(copy, nonatomic) CDUnknownBlockType didTapHandler; // @synthesize didTapHandler=_didTapHandler;
@property(retain, nonatomic) TTPushAlertModel *alertModel; // @synthesize alertModel=_alertModel;
@property(nonatomic) _Bool shouldAutorotate; // @synthesize shouldAutorotate=_shouldAutorotate;
- (void).cxx_destruct;
- (double)__imagesContainerHeight__;
- (double)__containerViewHeight__;
- (void)layoutOniOS7WithOrientation:(long long)arg1;
- (struct CGRect)__targetRectForContainerViewWithKeyboardHeight:(double)arg1;
- (void)__adjustFrameBeforeShowAnimation__;
- (id)__findSuperViewInVisibleWindow__;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)didDeviceOrientationChangeWhenSuperViewDoesNotRotate;
- (void)handleOrientationDidReceiveDeviceRotateNotification:(id)arg1;
- (void)hideWithAnimated:(_Bool)arg1 dismissReason:(long long)arg2;
- (void)hideWithAnimated:(_Bool)arg1;
- (void)hide;
- (void)showWithAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)show;
- (void)strongPushAlertActionDidTapContentButton:(id)arg1;
- (void)handleActionDidTapViewInstantlyButton:(id)arg1;
- (void)handleActionDidTapIgnoreButton:(id)arg1;
- (void)doCustomLayout;
- (void)layoutSubviews;
- (void)setupCustomViews;
- (void)removeRotateObserver;
- (void)addRotateObserver;
- (void)addKeyboardObservers;
- (void)setupControls;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithAlertModel:(id)arg1 willHideBlock:(CDUnknownBlockType)arg2 didHideBlock:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

