//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FRCommonUserInfoStructModel, NSArray, NSMutableArray, NSString;

@interface TTUGCStoryBaseViewModel : NSObject
{
    _Bool _hasMore;
    NSString *_userID;
    NSString *_reason;
    NSString *_tail;
    FRCommonUserInfoStructModel *_userInfo;
    NSArray *_dataSource;
    unsigned long long _offset;
    NSMutableArray *_idsArray;
}

@property(retain, nonatomic) NSMutableArray *idsArray; // @synthesize idsArray=_idsArray;
@property(nonatomic) unsigned long long offset; // @synthesize offset=_offset;
@property(copy, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) FRCommonUserInfoStructModel *userInfo; // @synthesize userInfo=_userInfo;
@property(copy, nonatomic) NSString *tail; // @synthesize tail=_tail;
@property(copy, nonatomic) NSString *reason; // @synthesize reason=_reason;
@property(copy, nonatomic) NSString *userID; // @synthesize userID=_userID;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
- (void).cxx_destruct;
- (id)categoryID;
- (void)sendEmptyEvent;
- (void)refreshData;
- (void)updateThreadOrderedDatasPreOrNextCellType;
- (void)originalDataUpdateWithID:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)removeShortVideoWithGroupID:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)removeWithID:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)isNeedRequestForPreloadOrNoRequestWithCompletion:(CDUnknownBlockType)arg1;
- (void)preloadWithCompletion:(CDUnknownBlockType)arg1;
- (void)requestStoryDataWithCompletion:(CDUnknownBlockType)arg1;
- (id)getUniqueIDForLastRead;
- (long long)totalNumber;
- (id)itemAtIndex:(long long)arg1;
- (id)init;

@end

