//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSString, TTVFeedListViewController;

@interface TTVFeedCellSelectContext : NSObject
{
    _Bool _clickComment;
    NSMutableDictionary *_eventContext;
    NSString *_screenName;
    unsigned long long _refer;
    NSString *_categoryId;
    TTVFeedListViewController *_feedListViewController;
}

@property(nonatomic) __weak TTVFeedListViewController *feedListViewController; // @synthesize feedListViewController=_feedListViewController;
@property(nonatomic) _Bool clickComment; // @synthesize clickComment=_clickComment;
@property(copy, nonatomic) NSString *categoryId; // @synthesize categoryId=_categoryId;
@property(nonatomic) unsigned long long refer; // @synthesize refer=_refer;
@property(retain, nonatomic) NSString *screenName; // @synthesize screenName=_screenName;
@property(retain, nonatomic) NSMutableDictionary *eventContext; // @synthesize eventContext=_eventContext;
- (void).cxx_destruct;

@end

