//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"

@interface TTVideoADExpireItem : NSObject <NSCoding>
{
    double _requestTime;
    double _expiredTime;
}

@property(nonatomic) double expiredTime; // @synthesize expiredTime=_expiredTime;
@property(nonatomic) double requestTime; // @synthesize requestTime=_requestTime;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

