//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIDevice.h>

@interface UIDevice (HTSVideoEditor)
+ (_Bool)supportMetalCNN;
+ (struct CGSize)htsVideo_availableProcessSizeForDevice;
+ (id)htsVideo_availableCaptureSessionPresetForDevice;
+ (struct CGSize)htsVideo_sizeForCaptureSessionPreset:(id)arg1;
+ (_Bool)htsVideo_isMicrophoneNowAvailable;
+ (void)htsVideo_microphoneAuthorzied:(CDUnknownBlockType)arg1 notAuthorized:(CDUnknownBlockType)arg2;
+ (void)htsVideo_cameraAuthorzied:(CDUnknownBlockType)arg1 notAuthorized:(CDUnknownBlockType)arg2;
+ (_Bool)isMicroPhoneAuth;
+ (_Bool)isCameraAuth;
+ (_Bool)supportb612Beautify;
+ (_Bool)htsVideo_isiOS10_3AndLater;
+ (_Bool)htsVideo_isLowerIOS7;
+ (_Bool)htsVideo_isHigherIOS7;
+ (_Bool)htsVideo_isiPhone;
+ (id)htsVideo_machineModel;
- (_Bool)htsVideo_isiOS9AndLater;
- (_Bool)htsVideo_isPoorThanIPhone6;
- (_Bool)htsVideo_isPoorThanIPhone5s;
- (_Bool)htsVideo_isPoorThanIPhone5;
- (_Bool)htsVideo_isPoorThanIPhone4s;
@end

