//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SSThemedButton, WDBottomToolView;

@protocol WDBottomToolViewDelegate <NSObject>
- (void)bottomView:(WDBottomToolView *)arg1 nextButtonClicked:(SSThemedButton *)arg2;
- (void)bottomView:(WDBottomToolView *)arg1 diggButtonClicked:(SSThemedButton *)arg2;
- (void)bottomView:(WDBottomToolView *)arg1 commentButtonClicked:(SSThemedButton *)arg2;
- (void)bottomView:(WDBottomToolView *)arg1 emojiButtonClicked:(SSThemedButton *)arg2;
- (void)bottomView:(WDBottomToolView *)arg1 writeButtonClicked:(SSThemedButton *)arg2;
@end

