//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSAttributedString, NSDictionary, TTRichSpanText, WDExcellentCommentEntity;

@interface WDListCellCommentLayoutModel : NSObject
{
    double _width;
    double _height;
    double _padding;
    NSAttributedString *_attributedStr;
    NSDictionary *_linkAttributes;
    TTRichSpanText *_richSpanText;
    WDExcellentCommentEntity *_commentEntity;
}

@property(retain, nonatomic) WDExcellentCommentEntity *commentEntity; // @synthesize commentEntity=_commentEntity;
@property(retain, nonatomic) TTRichSpanText *richSpanText; // @synthesize richSpanText=_richSpanText;
@property(retain, nonatomic) NSDictionary *linkAttributes; // @synthesize linkAttributes=_linkAttributes;
@property(retain, nonatomic) NSAttributedString *attributedStr; // @synthesize attributedStr=_attributedStr;
@property(nonatomic) double padding; // @synthesize padding=_padding;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double width; // @synthesize width=_width;
- (void).cxx_destruct;

@end

