//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class WDAnswerEntity, WDListCellDataModel;

@interface WDMoreListCellViewModel : NSObject
{
    _Bool _isInvalidData;
    _Bool _isFollowButtonHidden;
    WDAnswerEntity *_ansEntity;
    WDListCellDataModel *_dataModel;
}

@property(nonatomic) _Bool isFollowButtonHidden; // @synthesize isFollowButtonHidden=_isFollowButtonHidden;
@property(nonatomic) _Bool isInvalidData; // @synthesize isInvalidData=_isInvalidData;
@property(retain, nonatomic) WDListCellDataModel *dataModel; // @synthesize dataModel=_dataModel;
@property(retain, nonatomic) WDAnswerEntity *ansEntity; // @synthesize ansEntity=_ansEntity;
- (void).cxx_destruct;
- (id)trimSpaceFromOriginString:(id)arg1;
- (void)sendTrackWithLabel:(id)arg1;
- (void)cellDidSelectedWithGdExtJson:(id)arg1;
- (id)followButtonTappedTrackDict;
- (id)diggButtonTappedTrackDict;
- (id)forwardButtonTappedTrackDict;
- (id)commentButtonTappedTrackDict;
- (void)forwardCurrentAnswerToUGC;
- (void)enterAnswerDetailPageFromComment;
- (id)forwardButtonContent;
- (id)commentButtonContent;
- (id)diggButtonContent;
- (id)forwardCount;
- (id)commentCount;
- (id)diggCount;
- (id)bottomLabelContent;
- (id)answerContentAbstract;
- (id)secondLineContent;
- (id)initWithDataModel:(id)arg1;

@end

