//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AliAssetTallyBaseOperation.h"

@class NSArray;

@interface AliAssetTallyResetOperation : AliAssetTallyBaseOperation
{
    NSArray *_versionList;
}

@property(retain, nonatomic) NSArray *versionList; // @synthesize versionList=_versionList;
- (void).cxx_destruct;
- (void)main;

@end

