//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@class UIColor;

@interface APMRecorderFocusLayer : CALayer
{
    double _length;
    UIColor *_focusLineColor;
    struct CGPoint _center;
}

+ (_Bool)needsDisplayForKey:(id)arg1;
@property(retain, nonatomic) UIColor *focusLineColor; // @synthesize focusLineColor=_focusLineColor;
@property(nonatomic) struct CGPoint center; // @synthesize center=_center;
@property(nonatomic) double length; // @synthesize length=_length;
- (void).cxx_destruct;
- (void)drawInContext:(struct CGContext *)arg1;
- (id)initWithLayer:(id)arg1;

@end

