//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CCDCPostOperation.h"

@interface CCDCPostAndForeignOperation : CCDCPostOperation
{
}

- (id)buildRequest:(id)arg1;
- (id)initWithCardNumber:(id)arg1 doUpdate:(_Bool)arg2;
- (id)initWithCardNumber:(id)arg1;

@end

