//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewFlowLayout.h>

@interface EWCardListLayout : UICollectionViewFlowLayout
{
    double _pageWidth;
    unsigned long long _currentIndex;
    CDUnknownBlockType _currentIndexChangedBlock;
}

@property(copy, nonatomic) CDUnknownBlockType currentIndexChangedBlock; // @synthesize currentIndexChangedBlock=_currentIndexChangedBlock;
@property(readonly, nonatomic) unsigned long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(nonatomic) double pageWidth; // @synthesize pageWidth=_pageWidth;
- (void).cxx_destruct;
- (void)correctCurrentIndex:(unsigned long long)arg1;
- (void)setCurrentIndex:(unsigned long long)arg1;
- (double)flickVelocity;
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1 withScrollingVelocity:(struct CGPoint)arg2;

@end

