//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class FBDocument, NSString;

@interface FBTableViewCell : UITableViewCell
{
    FBDocument *_doc;
    NSString *_version;
}

+ (double)heightForCell:(id)arg1 data:(id)arg2;
+ (double)heightForCell:(id)arg1 data:(id)arg2 delegate:(id)arg3;
+ (id)cell:(id)arg1 data:(id)arg2;
@property(retain, nonatomic) NSString *version; // @synthesize version=_version;
@property(retain, nonatomic) FBDocument *doc; // @synthesize doc=_doc;
- (void).cxx_destruct;
- (void)reloadData:(id)arg1;
- (id)initWithDoc:(id)arg1 data:(id)arg2 reuseIdentifier:(id)arg3 delegate:(id)arg4;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)reloadData:(id)arg1 cellId:(id)arg2;
- (void)setCellTpl:(id)arg1;

@end

