//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface H5BizServiceDataMgmt : NSObject
{
    NSMutableDictionary *_serviceData;
    NSMutableDictionary *_serviceIdCallbacks;
}

+ (id)shared;
@property(retain, nonatomic) NSMutableDictionary *serviceIdCallbacks; // @synthesize serviceIdCallbacks=_serviceIdCallbacks;
@property(retain, nonatomic) NSMutableDictionary *serviceData; // @synthesize serviceData=_serviceData;
- (void).cxx_destruct;
- (id)popDataOfServiceId:(id)arg1;
- (id)getCallbackOfServiceId:(id)arg1;
- (void)pushData:(id)arg1 ServiceId:(id)arg2;
- (void)registerCallback:(id)arg1 withServiceId:(id)arg2;
- (id)generateServiceInstanceId;
- (id)initPrivate;

@end

