//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITabBarItem.h>

@class NSString;

@interface H5TabBarItem : UITabBarItem
{
    NSString *_identifier;
}

@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)setSuperSelectedImage:(id)arg1;
- (void)setFinishedSelectedImage:(id)arg1 withFinishedUnselectedImage:(id)arg2;
- (void)setSelectedImage:(id)arg1;
- (id)initWithTitle:(id)arg1 identifier:(id)arg2 color:(id)arg3 selectedColor:(id)arg4;

@end

