//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class APButton;

@interface HPersonalLogoutView : UIView
{
    APButton *_logoutBtn;
}

@property(retain, nonatomic) APButton *logoutBtn; // @synthesize logoutBtn=_logoutBtn;
- (void).cxx_destruct;
- (void)logoutHandler:(id)arg1;
- (void)refresh;
- (id)init;

@end

