//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LFCVOBase2.h"

@class NSString;

@interface LFCBaseRespVO2 : LFCVOBase2
{
    NSString *_resultStatus;
    NSString *_memo;
}

@property(retain, nonatomic) NSString *memo; // @synthesize memo=_memo;
@property(retain, nonatomic) NSString *resultStatus; // @synthesize resultStatus=_resultStatus;
- (void).cxx_destruct;

@end

