//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MYPromotionConfigModel;
@protocol MYPromotionViewControllerDelegate;

@interface MYPromotionViewController : UIViewController
{
    _Bool _isTracking;
    _Bool _isActive;
    UIViewController *_attachViewController;
    MYPromotionConfigModel *_config;
    id <MYPromotionViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <MYPromotionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isActive; // @synthesize isActive=_isActive;
@property(nonatomic) _Bool isTracking; // @synthesize isTracking=_isTracking;
@property(readonly, nonatomic) MYPromotionConfigModel *config; // @synthesize config=_config;
@property(nonatomic) __weak UIViewController *attachViewController; // @synthesize attachViewController=_attachViewController;
- (void).cxx_destruct;
- (void)untrackView:(id)arg1;
- (void)trackView:(id)arg1;
- (void)show;
- (void)hidePromotion;
- (void)promotionDidHide;
- (void)promotionWillHide;
- (_Bool)display;
- (void)showPromotion;
- (void)promotionDidShow;
- (void)promotionWillShow;
- (void)tearDownContentViewController;
- (void)setupContentViewController;
- (id)contentViewController;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithConfig:(id)arg1;
- (void)dealloc;

@end

