//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface NSObject (DTTargetAction)
- (void)sendActionsForCustomEvents:(id)arg1;
- (void)removeTargetByCustomEvents:(id)arg1;
- (void)removeTarget:(id)arg1 forCustomEvents:(id)arg2;
- (void)addTarget:(id)arg1 action:(SEL)arg2 forCustomEvents:(id)arg3;
@end

