//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "O2OSEARCHToString.h"

@class NSString;

@interface O2OSEARCHShadingWordHotWordRequest : O2OSEARCHToString
{
    NSString *_uid;
    NSString *_cityCode;
    NSString *_longitude;
    NSString *_latitude;
    NSString *_ftCategoryId;
    NSString *_bgCategoryId;
}

@property(retain, nonatomic) NSString *bgCategoryId; // @synthesize bgCategoryId=_bgCategoryId;
@property(retain, nonatomic) NSString *ftCategoryId; // @synthesize ftCategoryId=_ftCategoryId;
@property(retain, nonatomic) NSString *latitude; // @synthesize latitude=_latitude;
@property(retain, nonatomic) NSString *longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSString *cityCode; // @synthesize cityCode=_cityCode;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (void).cxx_destruct;

@end

