//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString;

@interface SFAProfileItemContent : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *actionUrl; // @dynamic actionUrl;
@property(readonly) _Bool hasActionUrl; // @dynamic hasActionUrl;
@property(readonly) _Bool hasItemDesc; // @dynamic hasItemDesc;
@property(readonly) _Bool hasItemIcon; // @dynamic hasItemIcon;
@property(readonly) _Bool hasItemId; // @dynamic hasItemId;
@property(readonly) _Bool hasItemTitle; // @dynamic hasItemTitle;
@property(retain, nonatomic) NSString *itemDesc; // @dynamic itemDesc;
@property(retain, nonatomic) NSString *itemIcon; // @dynamic itemIcon;
@property(retain, nonatomic) NSString *itemId; // @dynamic itemId;
@property(retain, nonatomic) NSString *itemTitle; // @dynamic itemTitle;

@end

