//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface TLBarCameraButton : UIButton
{
    _Bool _enableInteractive;
}

+ (id)cameraButtonWithTarget:(id)arg1 action:(SEL)arg2;
@property(nonatomic) _Bool enableInteractive; // @synthesize enableInteractive=_enableInteractive;

@end

