//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface TRANSFERPRODBatchDetailQueryReq : NSObject
{
    _Bool _fromScanCode;
    NSString *_batchNo;
    NSString *_token;
}

@property(nonatomic) _Bool fromScanCode; // @synthesize fromScanCode=_fromScanCode;
@property(retain, nonatomic) NSString *token; // @synthesize token=_token;
@property(retain, nonatomic) NSString *batchNo; // @synthesize batchNo=_batchNo;
- (void).cxx_destruct;

@end

