//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UILabel;

@interface TZBPorfitNumbersCell : UITableViewCell
{
    UILabel *_leftProfitLabel;
    UILabel *_rightProfitLabel;
    UILabel *_leftDescriptionLabel;
    UILabel *_rightDescriptionLabel;
}

+ (double)cellHeight;
@property(retain, nonatomic) UILabel *rightDescriptionLabel; // @synthesize rightDescriptionLabel=_rightDescriptionLabel;
@property(retain, nonatomic) UILabel *leftDescriptionLabel; // @synthesize leftDescriptionLabel=_leftDescriptionLabel;
@property(retain, nonatomic) UILabel *rightProfitLabel; // @synthesize rightProfitLabel=_rightProfitLabel;
@property(retain, nonatomic) UILabel *leftProfitLabel; // @synthesize leftProfitLabel=_leftProfitLabel;
- (void).cxx_destruct;
- (void)setupSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

