//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationItem.h>

@interface UINavigationItem (APExtUIFixedSpaceItem)
+ (void)swizzleNavigationItemMethodWithClass:(Class)arg1 oriMethod:(SEL)arg2 newMethod:(SEL)arg3;
+ (void)load;
- (_Bool)switchForCloseFixedSpaceItem;
- (id)alipayComUIFixedSpaceItem;
- (id)alipayComUIRightBarButtonItems;
- (id)alipayComUIRightBarButtonItem;
- (void)alipayComUISetRightBarButtonItems:(id)arg1 animated:(_Bool)arg2;
- (void)alipayComUISetRightBarButtonItem:(id)arg1 animated:(_Bool)arg2;
@end

