//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WEALTHToString.h"

#import "NSCopying-Protocol.h"

@class NSString;

@interface WEALTHFundTransferOutTipInfo : WEALTHToString <NSCopying>
{
    _Bool _displayBankChannelTip;
    _Bool _displayTransferOutTimes;
    NSString *_canTransferOutZeroTip;
    NSString *_bankChannelTip;
}

@property(nonatomic) _Bool displayTransferOutTimes; // @synthesize displayTransferOutTimes=_displayTransferOutTimes;
@property(nonatomic) _Bool displayBankChannelTip; // @synthesize displayBankChannelTip=_displayBankChannelTip;
@property(retain, nonatomic) NSString *bankChannelTip; // @synthesize bankChannelTip=_bankChannelTip;
@property(retain, nonatomic) NSString *canTransferOutZeroTip; // @synthesize canTransferOutZeroTip=_canTransferOutZeroTip;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

