//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSString, UIActivityIndicatorView, UILabel;

@interface WKPagedControl : UIControl
{
    long long _pagedState;
    UILabel *_textLabel;
    UIActivityIndicatorView *_indicatorView;
    NSString *_loadingText;
}

@property(retain, nonatomic) NSString *loadingText; // @synthesize loadingText=_loadingText;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(nonatomic) long long pagedState; // @synthesize pagedState=_pagedState;
- (void).cxx_destruct;
- (void)endPaging:(_Bool)arg1;
- (void)beginPaging;
- (_Bool)isPaging;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setLoadingTipsText:(id)arg1;
- (void)touchAction:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

