//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class CLLocation, NSMutableDictionary;

@interface CKImageMetadata : NSObject
{
    NSMutableDictionary *metadata;
}

- (void).cxx_destruct;
- (id)EXIFRepresentation;
- (void)updateWithDictionary:(id)arg1;
- (void)setImageOrientation:(unsigned long long)arg1;
- (unsigned long long)imageOrientation;
- (id)metadataByReplacingImageOrientation:(unsigned long long)arg1;
@property(retain, nonatomic) CLLocation *location;
- (void)dealloc;
- (id)init;
- (id)initWithMetadata:(id)arg1;

@end

