//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMGroupAccessObject.h"

@interface MMFansGroupMessageAccessObject : MMGroupAccessObject
{
}

- (_Bool)deleteMessageWithParentChatId:(long long)arg1;
- (_Bool)saveMessage:(id)arg1 isApi:(_Bool)arg2;
- (void)updateFansGroupConversationWithMessage:(id)arg1 isApi:(_Bool)arg2;
- (void)handleFansGroupMessage:(id)arg1 isApi:(_Bool)arg2;
- (_Bool)saveOrUpdateChatWithMessage:(id)arg1 isApi:(_Bool)arg2;
- (_Bool)updateChatLatestMessageIdAfterDeleteChat:(long long)arg1;
- (_Bool)updateChatLatestMessageId:(long long)arg1;
- (_Bool)deleteFansGroupMeessageChat:(long long)arg1;
- (_Bool)deleteChat:(long long)arg1;
- (_Bool)deleteMessagesAttachments:(long long)arg1;
- (_Bool)deleteMessages:(long long)arg1;
- (id)queryChatsWithOffset:(int)arg1 limit:(int)arg2 parentType:(int)arg3;
- (long long)parentChatId;
- (int)chatType;

@end

