//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBCommonComment.h"

@class NSDate, NSString;

@interface MMMessageComment : WBCommonComment
{
    NSString *_reply_original_text;
    NSDate *_attitude_created_at;
}

@property(retain, nonatomic) NSDate *attitude_created_at; // @synthesize attitude_created_at=_attitude_created_at;
@property(retain, nonatomic) NSString *reply_original_text; // @synthesize reply_original_text=_reply_original_text;
- (void).cxx_destruct;
- (_Bool)updateWithDictionary:(id)arg1;

@end

