//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface MMServerNode : NSObject
{
    unsigned short _port;
    int _type;
    NSString *_host;
}

+ (id)nodeWithHost:(id)arg1 port:(unsigned short)arg2 type:(int)arg3;
@property(nonatomic) int type; // @synthesize type=_type;
@property(nonatomic) unsigned short port; // @synthesize port=_port;
@property(copy, nonatomic) NSString *host; // @synthesize host=_host;
- (void).cxx_destruct;
- (void)dealloc;

@end

