//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MovieSDKBaseKVOTableViewCell.h"

#import "MovieSDKTicketCellSubjectViewDelegate-Protocol.h"

@class MovieSDKTicketCellPulishTypeView, MovieSDKTicketCellSubjectView, MovieSDKTicketData, NSMutableArray, NSString, UIButton, UIImageView, UILabel, UIView;

@interface MovieSDKTicketCell : MovieSDKBaseKVOTableViewCell <MovieSDKTicketCellSubjectViewDelegate>
{
    UIImageView *_posterImageView;
    UILabel *_titleLabel;
    UILabel *_typeLabel;
    UILabel *_releaseTimeLabel;
    UILabel *_actorLabel;
    UILabel *_wantToSeeLabel;
    UIButton *_operationBtn;
    UIView *_splitLine;
    UIImageView *_playMark;
    MovieSDKTicketCellPulishTypeView *_pulishTypeView;
    MovieSDKTicketCellSubjectView *_subjectsView;
    MovieSDKTicketData *_data;
    UIView *_respondView;
    UIView *_animationView;
    NSMutableArray *_flagsView;
    UIImageView *_cashImageView;
}

+ (double)preferredHeightForData:(id)arg1 cellInfo:(id)arg2 fitWidth:(double)arg3;
@property(retain, nonatomic) UIImageView *cashImageView; // @synthesize cashImageView=_cashImageView;
@property(retain, nonatomic) NSMutableArray *flagsView; // @synthesize flagsView=_flagsView;
@property(retain, nonatomic) UIView *animationView; // @synthesize animationView=_animationView;
@property(retain, nonatomic) UIView *respondView; // @synthesize respondView=_respondView;
@property(retain, nonatomic) MovieSDKTicketData *data; // @synthesize data=_data;
@property(retain, nonatomic) MovieSDKTicketCellSubjectView *subjectsView; // @synthesize subjectsView=_subjectsView;
@property(retain, nonatomic) MovieSDKTicketCellPulishTypeView *pulishTypeView; // @synthesize pulishTypeView=_pulishTypeView;
@property(retain, nonatomic) UIImageView *playMark; // @synthesize playMark=_playMark;
@property(retain, nonatomic) UIView *splitLine; // @synthesize splitLine=_splitLine;
@property(retain, nonatomic) UIButton *operationBtn; // @synthesize operationBtn=_operationBtn;
@property(retain, nonatomic) UILabel *wantToSeeLabel; // @synthesize wantToSeeLabel=_wantToSeeLabel;
@property(retain, nonatomic) UILabel *actorLabel; // @synthesize actorLabel=_actorLabel;
@property(retain, nonatomic) UILabel *releaseTimeLabel; // @synthesize releaseTimeLabel=_releaseTimeLabel;
@property(retain, nonatomic) UILabel *typeLabel; // @synthesize typeLabel=_typeLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *posterImageView; // @synthesize posterImageView=_posterImageView;
- (void).cxx_destruct;
- (id)keypathsForKVObserver;
- (void)startBlinkAnimation;
- (void)clickOperationBtn:(id)arg1;
- (void)clickPreviewBtn:(id)arg1;
- (void)clickCell;
- (void)subjectDidClickWithData:(id)arg1;
- (void)observerObjectValueDidChangeForKeypath:(id)arg1;
- (void)bindData:(id)arg1 cellInfo:(id)arg2;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

