//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBTopNavigationWebViewController.h"

#import "MFMessageComposeViewControllerDelegate-Protocol.h"

@class NSString;

@interface RegisterWapWebViewController : WBTopNavigationWebViewController <MFMessageComposeViewControllerDelegate>
{
}

- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(long long)arg2;
- (void)saveRegisterUid:(id)arg1;
- (_Bool)wb_webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (_Bool)isOfferLocation;
- (_Bool)isOfferEquipment;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

