//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ULSViewController.h"

#import "UIScrollViewDelegate-Protocol.h"

@class NSString, UIButton, UIScrollView, UIView, ULSNavigationBar, ULSWBLoginModel;

@interface ULSPublishLiveViewController : ULSViewController <UIScrollViewDelegate>
{
    ULSNavigationBar *_navigationBar;
    UIView *_selectBottomView;
    UIView *_uploadAudioView;
    UIView *_headerView;
    UIButton *_selectedHeaderView;
    UIButton *_downloadButton;
    _Bool _isHDInstalled;
    _Bool _hasLoginHD;
    _Bool _hasLoginWK;
    ULSWBLoginModel *_loginModel;
    UIScrollView *_scrollView;
    UIView *_contentView;
    UIButton *_audioLiveButton;
    UIButton *_uploadAudioButton;
    UIView *_selectView;
    UIView *_hdView;
}

+ (id)attributedTextForDesc:(id)arg1;
@property(nonatomic) _Bool hasLoginWK; // @synthesize hasLoginWK=_hasLoginWK;
@property(nonatomic) _Bool hasLoginHD; // @synthesize hasLoginHD=_hasLoginHD;
@property(nonatomic) _Bool isHDInstalled; // @synthesize isHDInstalled=_isHDInstalled;
@property(retain, nonatomic) UIView *hdView; // @synthesize hdView=_hdView;
@property(retain, nonatomic) UIView *selectView; // @synthesize selectView=_selectView;
@property(retain, nonatomic) UIButton *uploadAudioButton; // @synthesize uploadAudioButton=_uploadAudioButton;
@property(retain, nonatomic) UIButton *audioLiveButton; // @synthesize audioLiveButton=_audioLiveButton;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) ULSWBLoginModel *loginModel; // @synthesize loginModel=_loginModel;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)getConfigMessage;
- (void)loginWK;
- (void)loginHD;
- (void)openHDAPPorDownLoad;
- (void)copyButtonCallback;
- (void)openAudioHistoryVC;
- (void)uploadAudioButtonCallback;
- (void)audioLiveButtonCallback;
- (void)initSubviews;
- (void)setupUploadView;
- (void)setupHDView;
- (void)setupSelectView;
- (void)setupNavigationBar;
- (void)setupScrollView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)applicationDidBecomeActiveNotification;
- (void)updateDownloadButtonTitle;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

