//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString;

@interface ULSTableSectionNode : NSObject
{
    NSMutableArray *_rowNodeArray;
    NSString *_headerTitle;
    NSString *_footerTitle;
    double _headerHeight;
    double _footerHeight;
}

@property(nonatomic) double footerHeight; // @synthesize footerHeight=_footerHeight;
@property(nonatomic) double headerHeight; // @synthesize headerHeight=_headerHeight;
@property(copy, nonatomic) NSString *footerTitle; // @synthesize footerTitle=_footerTitle;
@property(copy, nonatomic) NSString *headerTitle; // @synthesize headerTitle=_headerTitle;
@property(retain, nonatomic) NSMutableArray *rowNodeArray; // @synthesize rowNodeArray=_rowNodeArray;
- (void).cxx_destruct;
- (id)init;

@end

