//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface ULSUserDefaultsUtil : NSObject
{
}

+ (void)setDictionary:(id)arg1 key:(id)arg2;
+ (id)dictionaryForKey:(id)arg1;
+ (void)removeLocalDataForKey:(id)arg1;
+ (void)setLocalDataObject:(id)arg1 key:(id)arg2;
+ (id)getLocalDataObject:(id)arg1;
+ (void)setLocalDataBoolen:(_Bool)arg1 key:(id)arg2;
+ (_Bool)getLocalDataBoolen:(id)arg1;
+ (void)setLocalDataString:(id)arg1 key:(id)arg2;
+ (id)getLocalDataString:(id)arg1;

@end

