//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBViewController.h"

@class UITableView, ULSTableTarget;

@interface ULSViewController : WBViewController
{
    unsigned long long _ulstatusBarStyle;
}

@property(nonatomic) unsigned long long ulstatusBarStyle; // @synthesize ulstatusBarStyle=_ulstatusBarStyle;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;
- (void)uls_resizeTableViewHeader;
- (void)uls_reloadTableViewNormal:(id)arg1;
- (void)uls_reloadTableView:(id)arg1;
- (void)uls_setupTableView:(long long)arg1;
- (void)uls_setupTableTarget;
@property(nonatomic) __weak UITableView *tableView;
@property(retain, nonatomic) ULSTableTarget *tableTarget;

@end

