//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAShapeLayer, WB360ImageLayerAnimationProxy;

@interface WB360HeadingIndicatorInnerView : UIView
{
    float _widthScale;
    float _width;
    double _direction;
    double _scale;
    CAShapeLayer *_circleLayer;
    CAShapeLayer *_sectorLayer;
    CAShapeLayer *_triangleLayer;
    WB360ImageLayerAnimationProxy *_animationProxy;
}

@property(retain, nonatomic) WB360ImageLayerAnimationProxy *animationProxy; // @synthesize animationProxy=_animationProxy;
@property(retain, nonatomic) CAShapeLayer *triangleLayer; // @synthesize triangleLayer=_triangleLayer;
@property(retain, nonatomic) CAShapeLayer *sectorLayer; // @synthesize sectorLayer=_sectorLayer;
@property(retain, nonatomic) CAShapeLayer *circleLayer; // @synthesize circleLayer=_circleLayer;
@property(nonatomic) double scale; // @synthesize scale=_scale;
@property(nonatomic) double direction; // @synthesize direction=_direction;
- (void).cxx_destruct;
- (void)updateSector;
- (id)initWithFrame:(struct CGRect)arg1;

@end

