//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIActionSheet.h>

#import "UIActionSheetDelegate-Protocol.h"

@class NSMutableDictionary, NSString;
@protocol UIActionSheetDelegate;

@interface WBActionSheet : UIActionSheet <UIActionSheetDelegate>
{
    id <UIActionSheetDelegate> sheetDelegate;
    CDUnknownBlockType willPresentBlock;
    CDUnknownBlockType didPresentBlock;
    CDUnknownBlockType didCancelBlock;
    CDUnknownBlockType didClickButtonBlock;
    CDUnknownBlockType willDismissBlock;
    CDUnknownBlockType didDismissBlock;
    NSMutableDictionary *buttonBlocks;
    id userInfo;
    unsigned long long _clickBlockType;
}

+ (id)actionSheetWithTitle:(id)arg1;
@property(nonatomic) unsigned long long clickBlockType; // @synthesize clickBlockType=_clickBlockType;
@property(copy, nonatomic) CDUnknownBlockType didDismissBlock; // @synthesize didDismissBlock;
@property(copy, nonatomic) CDUnknownBlockType willDismissBlock; // @synthesize willDismissBlock;
@property(copy, nonatomic) CDUnknownBlockType didClickButtonBlock; // @synthesize didClickButtonBlock;
@property(copy, nonatomic) CDUnknownBlockType didCancelBlock; // @synthesize didCancelBlock;
@property(copy, nonatomic) CDUnknownBlockType didPresentBlock; // @synthesize didPresentBlock;
@property(copy, nonatomic) CDUnknownBlockType willPresentBlock; // @synthesize willPresentBlock;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo;
@property(nonatomic) __weak id <UIActionSheetDelegate> sheetDelegate; // @synthesize sheetDelegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)actionSheet:(id)arg1 willDismissWithButtonIndex:(long long)arg2;
- (void)didPresentActionSheet:(id)arg1;
- (void)willPresentActionSheet:(id)arg1;
- (void)actionSheetCancel:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (long long)addCancelButtonWithTitle:(id)arg1;
- (long long)addCancelButtonWithTitle:(id)arg1 clickBlock:(CDUnknownBlockType)arg2;
- (long long)addDestructiveButtonWithTitle:(id)arg1 clickBlock:(CDUnknownBlockType)arg2;
- (long long)addButtonWithTitle:(id)arg1 clickBlock:(CDUnknownBlockType)arg2;
- (void)setDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

