//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class WBContentImageView;

@interface WBArCaptureButtonInnerCircleView : UIView
{
    WBContentImageView *_imageView;
}

@property(retain, nonatomic) WBContentImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)beginProcessingAnimation;
- (void)beginTouchEndAnimation;
- (void)beginTouchDownAnimation;
- (void)resetUIElements;
- (void)updateButtonState:(unsigned long long)arg1;
- (void)updateHighlightedState:(_Bool)arg1;
- (void)setImageUrl:(id)arg1 placeholderImage:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

