//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBModelObject.h"

@class NSArray, NSString;

@interface WBCommentHeaderItem : WBModelObject
{
    int _showBulletinType;
    NSString *_title;
    NSString *_iconURLString;
    NSString *_iconName;
    NSString *_iconScheme;
    NSArray *_sortItems;
    _Bool *_isShouldShow;
    NSString *_textInfo;
}

@property(retain, nonatomic) NSString *textInfo; // @synthesize textInfo=_textInfo;
@property(nonatomic) _Bool *isShouldShow; // @synthesize isShouldShow=_isShouldShow;
@property(nonatomic) int showBulletinType; // @synthesize showBulletinType=_showBulletinType;
@property(retain, nonatomic) NSArray *sortItems; // @synthesize sortItems=_sortItems;
@property(retain, nonatomic) NSString *iconScheme; // @synthesize iconScheme=_iconScheme;
@property(retain, nonatomic) NSString *iconName; // @synthesize iconName=_iconName;
@property(retain, nonatomic) NSString *iconURLString; // @synthesize iconURLString=_iconURLString;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)setSelectedSortIndex:(unsigned long long)arg1;
- (_Bool)updateWithDictionary:(id)arg1;

@end

