//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WBComposeElementView-Protocol.h"

@class NSString, UIButton, WBComposeCheckElement, WBComposeElement;
@protocol WBComposeElementViewDelegate;

@interface WBComposeCheckElementView : UIView <WBComposeElementView>
{
    WBComposeCheckElement *_composeElement;
    id <WBComposeElementViewDelegate> _composeDelegate;
    UIButton *_checkBox;
}

@property(retain, nonatomic) UIButton *checkBox; // @synthesize checkBox=_checkBox;
@property(nonatomic) __weak id <WBComposeElementViewDelegate> composeDelegate; // @synthesize composeDelegate=_composeDelegate;
@property(nonatomic) __weak WBComposeElement *composeElement; // @synthesize composeElement=_composeElement;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (double)caculateWidth;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

