//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageFilterGroup.h"

@class GPUImagePicture;

@interface WBConfigurableFilter : GPUImageFilterGroup
{
    GPUImagePicture *_texture1;
    GPUImagePicture *_texture2;
    GPUImagePicture *_texture3;
    GPUImagePicture *_texture4;
    GPUImagePicture *_texture5;
}

@property(retain, nonatomic) GPUImagePicture *texture5; // @synthesize texture5=_texture5;
@property(retain, nonatomic) GPUImagePicture *texture4; // @synthesize texture4=_texture4;
@property(retain, nonatomic) GPUImagePicture *texture3; // @synthesize texture3=_texture3;
@property(retain, nonatomic) GPUImagePicture *texture2; // @synthesize texture2=_texture2;
@property(retain, nonatomic) GPUImagePicture *texture1; // @synthesize texture1=_texture1;
- (void).cxx_destruct;
- (id)initWithFilterModel:(id)arg1;
- (id)initWithVertexShaderString:(id)arg1 fragmentShaderString:(id)arg2 textureImages:(id)arg3;

@end

