//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBModelObject.h"

@class NSMutableArray, NSString;

@interface WBCommentMoreItem : WBModelObject
{
    _Bool _isLoading;
    _Bool _isShowSplitLine;
    _Bool _isInSubCommentView;
    NSString *_moreText;
    NSString *_rootID;
    double _height;
    unsigned long long _style;
    NSString *_scheme;
    NSString *_text;
    NSString *_highlightText;
    NSMutableArray *_userListArray;
    NSMutableArray *_nameList;
    NSMutableArray *_screenNameList;
}

+ (id)moreItemWithDict:(id)arg1;
@property(nonatomic) _Bool isInSubCommentView; // @synthesize isInSubCommentView=_isInSubCommentView;
@property(retain, nonatomic) NSMutableArray *screenNameList; // @synthesize screenNameList=_screenNameList;
@property(retain, nonatomic) NSMutableArray *nameList; // @synthesize nameList=_nameList;
@property(retain, nonatomic) NSMutableArray *userListArray; // @synthesize userListArray=_userListArray;
@property(retain, nonatomic) NSString *highlightText; // @synthesize highlightText=_highlightText;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSString *scheme; // @synthesize scheme=_scheme;
@property(nonatomic) _Bool isShowSplitLine; // @synthesize isShowSplitLine=_isShowSplitLine;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(nonatomic) double height; // @synthesize height=_height;
@property(retain, nonatomic) NSString *rootID; // @synthesize rootID=_rootID;
@property(retain, nonatomic) NSString *moreText; // @synthesize moreText=_moreText;
- (void).cxx_destruct;
- (id)init;

@end

