//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIWindow.h>

@interface WBCustomAlertOverlayWindow : UIWindow
{
    UIWindow *oldKeyWindow;
    double _customAlpha;
    struct CGPoint _customOS6FocusOffset;
}

@property(nonatomic) struct CGPoint customOS6FocusOffset; // @synthesize customOS6FocusOffset=_customOS6FocusOffset;
@property(nonatomic) double customAlpha; // @synthesize customAlpha=_customAlpha;
@property(retain, nonatomic) UIWindow *oldKeyWindow; // @synthesize oldKeyWindow;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)resignKeyWindow;
- (void)makeKeyAndVisible;

@end

