//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSMutableDictionary, NSTimer, SNHTTPRequestOperationWrapper;

@interface WBFeedGroupManager : NSObject
{
    NSMutableDictionary *feedGroups;
    NSMutableArray *sortedGroupKeys;
    NSMutableDictionary *hotGroups;
    NSMutableArray *hotSortedGroupKeys;
    NSMutableArray *allFeedGroups;
    NSMutableArray *hotSelectGroups;
    NSMutableArray *hotListGroups;
    _Bool loading;
    NSMutableDictionary *groupInfos;
    NSMutableArray *navigationDotArray;
    SNHTTPRequestOperationWrapper *groupInfoRequestWrapper;
    long long frequencyNumber;
    _Bool hasStartFetchGroupInfoTimer;
    NSTimer *groupInfoFetchTimer;
    id _responseObject;
}

+ (id)sharedManager;
+ (void)setDefaultGroupInfo:(id)arg1 forKey:(id)arg2;
+ (id)defaultGroupInfoForKey:(id)arg1;
@property(retain, nonatomic) id responseObject; // @synthesize responseObject=_responseObject;
@property(readonly, nonatomic) _Bool loading; // @synthesize loading;
@property(retain, nonatomic) NSTimer *groupInfoFetchTimer; // @synthesize groupInfoFetchTimer;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;
- (void)currentAccountDidChangeNotification:(id)arg1;
- (void)appLanguageDidChange:(id)arg1;
- (id)getTitlesArrayWithGroupType:(long long)arg1;
- (id)getGroupArrayWithGroupType:(long long)arg1;
- (void)loadFeedGroupsWithPara:(id)arg1 CompletionBlock:(CDUnknownBlockType)arg2;
- (void)loadNewHomeFeedGroupsCompletionBlock:(CDUnknownBlockType)arg1;
- (void)groupNameDidChanged:(id)arg1;
- (void)groupDidDeleted:(id)arg1;
- (void)fetchGroupInfo:(id)arg1;
- (void)startFetchGroupInfo;
- (void)groupDidRead:(id)arg1;
- (_Bool)hasHotDot;
- (_Bool)hasFeedDot;
- (void)setHotDot:(unsigned long long)arg1;
- (void)setFeedDot:(unsigned long long)arg1;
- (long long)defaultUnreadCount;
- (long long)unreadCountForGroup:(id)arg1;
- (id)groupInfoForGroup:(id)arg1;
- (id)groupWithType:(long long)arg1;
- (id)groupWithType:(long long)arg1 groupID:(id)arg2;
- (id)hotGroupWithID:(id)arg1;
- (id)feedGroupWithID:(id)arg1;
- (id)groupWithID:(id)arg1;
- (unsigned long long)defaultFeedGroupsCount;
- (long long)defaultServerSetHomeGroupType;
- (void)resetDefaultHomeGroupType:(long long)arg1;
- (long long)defaultHomeGroupType;
- (void)setForceGroup:(id)arg1;
- (id)forceGroup;
- (id)defaultGroup;
- (id)defaultUserHotGroup;
- (id)getDefaultHotGroup;
- (id)getDefaultFeedGroup;
- (id)allHotGroup;
- (id)allFeedGroup;
- (_Bool)isForceChangedGroup:(id)arg1;
- (void)groupUserSelected:(id)arg1;
- (void)groupDidSelected:(id)arg1 groupType:(long long)arg2;
- (void)hotGroupDidSelected:(id)arg1;
- (void)groupDidSelected:(id)arg1;
- (void)configSpecialGroupWithDictionary:(id)arg1;
- (void)resetFeedGroups;
- (id)hotListGroupsArray;
- (id)hotSelectGroupsArray;
- (id)allFeedGroupsArray;
- (id)hotGroupKeys;
- (id)allHotGroups;
- (id)groupKeys;
- (id)allFeedGroups;

@end

