//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "WBFAVPlayer-Protocol.h"
#import "WBFPlayerItemInternalDelegate-Protocol.h"

@class NSMutableArray, NSString, WBFPlayerItem;
@protocol WBFPlayerInternalDelegate;

@interface WBFPlayer : NSObject <WBFPlayerItemInternalDelegate, WBFAVPlayer>
{
    struct {
        unsigned int playing:1;
    } _flags;
    _Bool _muted;
    float _volume;
    double _pauseTimestamp;
    WBFPlayerItem *_currentItem;
    long long _status;
    NSMutableArray *_timeObservers;
    id <WBFPlayerInternalDelegate> _internalDelegate;
}

@property(nonatomic) __weak id <WBFPlayerInternalDelegate> internalDelegate; // @synthesize internalDelegate=_internalDelegate;
@property(retain, nonatomic) NSMutableArray *timeObservers; // @synthesize timeObservers=_timeObservers;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(retain, nonatomic) WBFPlayerItem *currentItem; // @synthesize currentItem=_currentItem;
@property(readonly, nonatomic) double pauseTimestamp; // @synthesize pauseTimestamp=_pauseTimestamp;
@property(nonatomic) float volume; // @synthesize volume=_volume;
@property(nonatomic, getter=isMuted) _Bool muted; // @synthesize muted=_muted;
- (void).cxx_destruct;
- (void)playerItem:(id)arg1 didUpdatePresentationSize:(struct CGSize)arg2;
- (void)playerItemDidPlayToEnd:(id)arg1;
- (void)playerItemDidFinishSeek:(id)arg1;
- (void)playerItemDidPerformSeek:(id)arg1;
- (void)playerItemDidRenderFirstVideoFrame:(id)arg1;
- (void)playerItem:(id)arg1 didUpdateStatus:(long long)arg2;
- (void)_prepareToPlay;
- (void)_stopPlaying;
- (void)_updateVolume:(float)arg1;
- (void)setVolume:(float)arg1 rampSec:(float)arg2;
- (void)callbackAllTimeObservers;
- (void)stopAllTimeObservers;
- (void)startAllTimeObservers;
- (void)removeTimeObserver:(id)arg1;
- (void)_addTimeObserver:(id)arg1;
- (id)addPeriodicTimeObserverForInterval:(CDStruct_1b6d18a9)arg1 queue:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (void)seekToTime:(CDStruct_1b6d18a9)arg1 toleranceBefore:(CDStruct_1b6d18a9)arg2 toleranceAfter:(CDStruct_1b6d18a9)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)seekToTime:(CDStruct_1b6d18a9)arg1;
- (_Bool)isSeeking;
- (void)pause;
- (void)play;
- (void)resetPropertiesWithPlayer:(id)arg1;
- (void)setRate:(float)arg1 force:(_Bool)arg2;
@property(nonatomic) float rate;
- (id)initWithPlayerItem:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

