//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, SNHTTPRequestOperationWrapper;

@interface WBGoodsEngine : NSObject
{
    SNHTTPRequestOperationWrapper *fetchRequestOperationWrapper;
    SNHTTPRequestOperationWrapper *deleteGoodsOperationWrapper;
    NSString *_goodsId;
}

@property(copy, nonatomic) NSString *goodsId; // @synthesize goodsId=_goodsId;
@property(retain, nonatomic) SNHTTPRequestOperationWrapper *deleteGoodsOperationWrapper; // @synthesize deleteGoodsOperationWrapper;
@property(retain, nonatomic) SNHTTPRequestOperationWrapper *fetchRequestOperationWrapper; // @synthesize fetchRequestOperationWrapper;
- (void).cxx_destruct;
- (void)deleteGoodsWithExtParams:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)loadGoodsWithExtParams:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)initWithGoodsId:(id)arg1;

@end

