//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WBLoginTagListViewDelegate-Protocol.h"

@class NSArray, NSDictionary, NSMutableArray, NSString, UIButton, UILabel, WBLoginTagListView;
@protocol WBGuestFeedTagsViewDelegate;

@interface WBGuestFeedTagsView : UIView <WBLoginTagListViewDelegate>
{
    NSMutableArray *_recommendOriginInterests;
    NSMutableArray *_recommendInterests;
    NSMutableArray *_selectedInterests;
    NSArray *_currentInterests;
    int _minimumSelectedNumber;
    _Bool _OrientationChange;
    id <WBGuestFeedTagsViewDelegate> _delegate;
    NSDictionary *_tagParams;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    WBLoginTagListView *_tagListView;
    UIButton *_changeBtn;
    UIButton *_stepBtn;
    UIView *_stepShadowLayer;
    NSMutableArray *_tagListArray;
    unsigned long long _currentCount;
}

+ (id)setupRecommendTagsView;
@property(nonatomic) _Bool OrientationChange; // @synthesize OrientationChange=_OrientationChange;
@property(nonatomic) unsigned long long currentCount; // @synthesize currentCount=_currentCount;
@property(retain, nonatomic) NSMutableArray *tagListArray; // @synthesize tagListArray=_tagListArray;
@property(retain, nonatomic) UIView *stepShadowLayer; // @synthesize stepShadowLayer=_stepShadowLayer;
@property(retain, nonatomic) UIButton *stepBtn; // @synthesize stepBtn=_stepBtn;
@property(retain, nonatomic) UIButton *changeBtn; // @synthesize changeBtn=_changeBtn;
@property(retain, nonatomic) WBLoginTagListView *tagListView; // @synthesize tagListView=_tagListView;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSDictionary *tagParams; // @synthesize tagParams=_tagParams;
@property(nonatomic) __weak id <WBGuestFeedTagsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)orientChange:(id)arg1;
- (void)selectedTagList:(id)arg1;
- (id)getParamsWithSelectedTags;
- (void)startButtonClicked:(id)arg1;
- (void)changeEvent:(id)arg1;
- (void)reloadData;
- (void)configViewsInfoWithContent:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

