//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString;

@interface WBIapStorageQueue : NSObject
{
    NSString *_cacheFileName;
    NSMutableArray *_queue;
}

@property(retain, nonatomic) NSMutableArray *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSString *cacheFileName; // @synthesize cacheFileName=_cacheFileName;
- (void).cxx_destruct;
- (_Bool)persistQueue:(id)arg1;
- (_Bool)persistDataWithCurrentItem:(id)arg1;
- (void)loadData;
- (_Bool)hasSameItem:(id)arg1;
- (_Bool)hasSameKindItem:(id)arg1;
- (long long)count;
- (void)clear;
- (id)pop;
- (void)insert:(id)arg1;
- (void)push:(id)arg1;
- (id)initWithCacheFileName:(id)arg1;

@end

