//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBIMBaseModel.h"

@class NSArray;

@interface WBIMPlaybackModel : WBIMBaseModel
{
    long long _startOffset;
    long long _endOffset;
    long long _segmentSize;
    NSArray *_messageList;
}

@property(retain, nonatomic) NSArray *messageList; // @synthesize messageList=_messageList;
@property(nonatomic) long long segmentSize; // @synthesize segmentSize=_segmentSize;
@property(nonatomic) long long endOffset; // @synthesize endOffset=_endOffset;
@property(nonatomic) long long startOffset; // @synthesize startOffset=_startOffset;
- (void).cxx_destruct;

@end

