//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBModelObject.h"

@class NSArray, NSString;

@interface WBInterestedContent : WBModelObject
{
    _Bool _enableSkip;
    _Bool _skipScheme;
    NSString *_topTitle;
    NSString *_subTitle;
    unsigned long long _limit;
    NSString *_scheme;
    NSString *_btnReadyText;
    NSArray *_tags;
}

@property(retain, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property(nonatomic) _Bool skipScheme; // @synthesize skipScheme=_skipScheme;
@property(copy, nonatomic) NSString *btnReadyText; // @synthesize btnReadyText=_btnReadyText;
@property(copy, nonatomic) NSString *scheme; // @synthesize scheme=_scheme;
@property(nonatomic) _Bool enableSkip; // @synthesize enableSkip=_enableSkip;
@property(nonatomic) unsigned long long limit; // @synthesize limit=_limit;
@property(copy, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(copy, nonatomic) NSString *topTitle; // @synthesize topTitle=_topTitle;
- (void).cxx_destruct;
- (_Bool)updateWithDictionary:(id)arg1;

@end

