//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface WBLogDBStorageModel : NSObject
{
    _Bool _in_database;
    _Bool _needSave;
    NSString *_domain;
    NSString *_identifier;
}

+ (id)_mutable_fields_map;
+ (void)initializeFields;
+ (_Bool)upgradeDBIfNeed:(id)arg1 fromVersion:(long long)arg2 toVersion:(long long)arg3;
+ (id)dbManager;
+ (id)tableName;
+ (id)fieldWithName:(id)arg1;
+ (id)fields_map;
+ (id)fields;
+ (id)createSqlCmd;
+ (id)quryWithSqlString:(id)arg1;
+ (id)query;
+ (id)modelWithDictionary:(id)arg1;
+ (void)registField:(id)arg1;
+ (id)modelwithDBtDict:(id)arg1;
+ (void)initialize;
@property _Bool needSave; // @synthesize needSave=_needSave;
@property(retain) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain) NSString *domain; // @synthesize domain=_domain;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (_Bool)updateWithDBDic:(id)arg1;
- (_Bool)isValidated;
- (_Bool)del;
- (_Bool)save;
- (void)dealloc;
- (id)initWithDBDict:(id)arg1;
- (id)init;
- (id)initWithDefaultValue;

@end

