//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBUserTableViewCell.h"

@class UIButton, WBMeyouInvitationButton;
@protocol WBMeyouInvitationCellDelegate;

@interface WBMeyouInvitationCell : WBUserTableViewCell
{
    _Bool _usesCheckbox;
    id <WBMeyouInvitationCellDelegate> _meyouDelegate;
    WBMeyouInvitationButton *_meyouButton;
    UIButton *_checkboxButton;
}

@property(retain, nonatomic) UIButton *checkboxButton; // @synthesize checkboxButton=_checkboxButton;
@property(nonatomic) _Bool usesCheckbox; // @synthesize usesCheckbox=_usesCheckbox;
@property(retain, nonatomic) WBMeyouInvitationButton *meyouButton; // @synthesize meyouButton=_meyouButton;
@property(nonatomic) id <WBMeyouInvitationCellDelegate> meyouDelegate; // @synthesize meyouDelegate=_meyouDelegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)updateCheckboxButton;
- (void)meyouButtonPressed:(id)arg1;
- (void)updateMeyouButton;
- (void)layoutSubviews;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

