//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, NSTimer, UIImageView, UILabel, UIVisualEffectView;

@interface WBMLVideoLiveBrightnessVolumeCustomView : UIView
{
    UIVisualEffectView *_toolbar;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    UIImageView *_icoView;
    UIView *_levelView;
    NSMutableArray *_tipsArray;
    unsigned long long _currentType;
    NSTimer *_timer;
}

@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) unsigned long long currentType; // @synthesize currentType=_currentType;
@property(retain, nonatomic) NSMutableArray *tipsArray; // @synthesize tipsArray=_tipsArray;
@property(retain, nonatomic) UIView *levelView; // @synthesize levelView=_levelView;
@property(retain, nonatomic) UIImageView *icoView; // @synthesize icoView=_icoView;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIVisualEffectView *toolbar; // @synthesize toolbar=_toolbar;
- (void).cxx_destruct;
- (void)cancelTimer;
- (void)startTimer;
- (void)reloadSubViewWithType:(unsigned long long)arg1;
- (void)updateProgressLevel:(double)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)volumeChanged:(id)arg1;
- (void)hiddenImmediately;
- (void)dismissIndicatorAnimation;
- (void)showIndicatorAnimationFor:(unsigned long long)arg1;
- (void)createTipsToLevelView;
- (void)createUI;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

