//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBUniversalNetworkClient.h"

@class NSString;

@interface WBNetworkClient : WBUniversalNetworkClient
{
    NSString *_streamValidatorKey;
    NSString *_encryptionKey;
}

+ (id)sharedTestClientForServer:(id)arg1;
+ (id)sharedClientWithModuleName:(id)arg1;
+ (id)freeTraficTypeString;
+ (id)generalRequestParams;
+ (void)setForceRequestProtocol:(unsigned long long)arg1;
+ (unsigned long long)forceRequestProtocol;
+ (void)addUrlChecksum:(id)arg1;
+ (id)serverSchemeFromSetting;
+ (id)networkType;
+ (void)checkEffectiveTimeOfBackupDomain;
+ (void)load;
+ (id)parseNetErrorCodeFromError:(id)arg1;
+ (id)serverBaseURLSuffix;
+ (id)antispamMaskI;
+ (id)ua;
+ (id)shared80TestClient;
+ (id)shared212TestClient;
+ (id)sharedTestClient;
@property(retain) NSString *encryptionKey; // @synthesize encryptionKey=_encryptionKey;
@property(retain) NSString *streamValidatorKey; // @synthesize streamValidatorKey=_streamValidatorKey;
- (void).cxx_destruct;
- (id)_domainInfoWithWrapper:(id)arg1;
- (id)initWithBaseURL:(id)arg1;
- (void)logFailureRequestWithPath:(id)arg1 parameters:(id)arg2 operationWrapper:(id)arg3 error:(id)arg4 method:(id)arg5 startRequestTime:(id)arg6 endRequestTime:(id)arg7;
- (void)logSuccessRequestWithPath:(id)arg1 parameters:(id)arg2 operationWrapper:(id)arg3 reulst:(id)arg4 method:(id)arg5 startRequestTime:(id)arg6 endRequestTime:(id)arg7;
- (id)extraParametersForHttpRequestOperationWrapper:(id)arg1 parameters:(id)arg2 isSeccess:(_Bool)arg3 method:(id)arg4 error:(id)arg5;
- (id)HTTPRequestOperationWithRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (_Bool)isDebugModeNeeded;
- (_Bool)isLogNeeded;
- (void)resetSkinParameters;
- (void)currentSkinDidChangeNotification:(id)arg1;
- (void)resetLanguageParameter;
- (void)appLanguageDidChange:(id)arg1;
- (void)accountCredentialUpdatedNotification:(id)arg1;
- (void)accountWillUpdateNotification:(id)arg1;
- (void)currentAccountWillChangeNotification:(id)arg1;
- (void)resetAccountAuthParametersWithAccount:(id)arg1;
- (void)resetAccountAuthParameters;
- (void)resetNetWorkSFlageValueWhenAppStateChanged;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)generateDefaultParameters;
- (void)resetAccountSystemBindingParameters;
- (void)handleWorkableBackupAPIFoundedNotification:(id)arg1;
- (void)handleError:(id)arg1 forWrapper:(id)arg2;
- (void)handleResponse:(id)arg1 forWrapper:(id)arg2;
- (void)handleAPIResponseUnusalErrorWithWrapper:(id)arg1;
- (void)handleAccountSystemBindingStateDidChangeNotification:(id)arg1;
- (void)generateNotificationHandlerOverwrite;
- (void)generateWbnetworkNotificationHandler;
- (void)generateNotificationHandler;
- (id)requestWithMethod:(id)arg1 path:(id)arg2 parameters:(id)arg3;
- (void)highDelayNotification:(id)arg1;
- (void)redirectUrlRequest:(id)arg1;
- (_Bool)setHttpHeaderWithRedirectUrlRequest:(id)arg1;
- (void)redirectUrlRequestToFreeTrafficServerIfNeeded:(id)arg1;
- (void)resetNetworkTypeParameters;
- (void)networkReachabilityChanged:(id)arg1;
- (id)backupBaseURL;
- (Class)errorHandlerClass;
- (_Bool)shouldEncrypt;
- (id)defaultServerHost;
- (id)hook_forVp_requestWithMethod:(id)arg1 path:(id)arg2 parameters:(id)arg3;
- (Class)errorHandlerClass;
- (id)postPath:(id)arg1 moduelID:(id)arg2 parameters:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)getPath:(id)arg1 moduelID:(id)arg2 parameters:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;

@end

