//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSMutableArray, UIImageView;

@interface WBNLConductCornerMarkTitleAvatorView : UIView
{
    _Bool _isOpen;
    _Bool _isRunning;
    NSMutableArray *_avatorImageViews;
    UIImageView *_avatorImageView1;
    UIImageView *_avatorImageView2;
    UIImageView *_avatorImageView3;
    NSArray *_dataSource;
    long long _index;
}

@property(nonatomic) long long index; // @synthesize index=_index;
@property(retain, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) _Bool isRunning; // @synthesize isRunning=_isRunning;
@property(nonatomic) _Bool isOpen; // @synthesize isOpen=_isOpen;
@property(retain, nonatomic) UIImageView *avatorImageView3; // @synthesize avatorImageView3=_avatorImageView3;
@property(retain, nonatomic) UIImageView *avatorImageView2; // @synthesize avatorImageView2=_avatorImageView2;
@property(retain, nonatomic) UIImageView *avatorImageView1; // @synthesize avatorImageView1=_avatorImageView1;
@property(retain, nonatomic) NSMutableArray *avatorImageViews; // @synthesize avatorImageViews=_avatorImageViews;
- (void).cxx_destruct;
- (void)initView;
- (void)initData;
- (void)refreshData;
- (void)close:(CDUnknownBlockType)arg1;
- (void)open;
- (id)initWithFrame:(struct CGRect)arg1;

@end

