//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WBMusicControlDelegate-Protocol.h"

@class NSString, UIButton, UILabel, WBContentImageView, WBMusicControl, WBPageBusinessDoubleCardItem, WBTimelineLargeCardTextView, WBVideoControl;

@interface WBPageCardBusinessDoubleViewItemView : UIView <WBMusicControlDelegate>
{
    WBContentImageView *photoImageView;
    WBMusicControl *musicControl;
    WBVideoControl *videoControl;
    WBContentImageView *cornerMarkImageView;
    WBTimelineLargeCardTextView *itemTitletextView;
    WBTimelineLargeCardTextView *picTitleTextView;
    WBContentImageView *picTitleBackgroundView;
    UILabel *descLabel;
    UILabel *priceLabel;
    UIButton *otherTouchButton;
    WBPageBusinessDoubleCardItem *_item;
}

+ (id)getContentText:(id)arg1;
+ (id)getPicContentText:(id)arg1;
+ (float)getTheItemScale:(id)arg1;
+ (double)heightOfDataObject:(id)arg1;
@property(retain, nonatomic) WBPageBusinessDoubleCardItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)otherTouchButtonMethod:(id)arg1;
- (void)didForbiddenMusic:(id)arg1;
- (_Bool)shouldForbidMusic:(id)arg1;
- (id)musicControlIdentifier:(id)arg1;
- (void)resetSubViewRects;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

