//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBModelObject.h"

@class NSDictionary, NSString, WBVideoItem;

@interface WBPagePhotosListCardItem : WBModelObject
{
    long long roundedCorner;
    NSString *pic;
    NSString *scheme;
    NSString *cornerMarkUrl;
    NSDictionary *actionLog;
    NSString *desc1;
    NSString *desc2;
    double _scaleFactor;
    unsigned long long _maxItemCount;
    WBVideoItem *_videoItem;
    NSString *_mediaType;
}

@property(retain, nonatomic) NSString *mediaType; // @synthesize mediaType=_mediaType;
@property(retain, nonatomic) WBVideoItem *videoItem; // @synthesize videoItem=_videoItem;
@property(nonatomic) unsigned long long maxItemCount; // @synthesize maxItemCount=_maxItemCount;
@property(nonatomic) double scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(retain, nonatomic) NSString *desc2; // @synthesize desc2;
@property(retain, nonatomic) NSString *desc1; // @synthesize desc1;
@property(retain, nonatomic) NSDictionary *actionLog; // @synthesize actionLog;
@property(retain, nonatomic) NSString *cornerMarkUrl; // @synthesize cornerMarkUrl;
@property(retain, nonatomic) NSString *scheme; // @synthesize scheme;
@property(retain, nonatomic) NSString *pic; // @synthesize pic;
@property(nonatomic, getter=isRoundedCorner) long long roundedCorner; // @synthesize roundedCorner;
- (void).cxx_destruct;
- (_Bool)updateWithDictionary:(id)arg1;
- (id)init;

@end

