//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBPageCard.h"

@class NSArray, NSString;

@interface WBPageProductInfoCard : WBPageCard
{
    NSString *_desc;
    NSArray *_labelArr;
}

@property(retain, nonatomic) NSArray *labelArr; // @synthesize labelArr=_labelArr;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)updateWithDictionary:(id)arg1;

@end

