//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBUniversialViewController.h"

#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "MFMessageComposeViewControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "WBComposeViewControllerDelegate-Protocol.h"
#import "WBContactRecentPickerViewControllerDelegate-Protocol.h"
#import "WBRetweetToFriendsViewDelegate-Protocol.h"

@class NSString, WBRetweetToFriendsManager, WBShareContent;

@interface WBRetweetToFriendsPopController : WBUniversialViewController <MFMessageComposeViewControllerDelegate, UINavigationControllerDelegate, MFMailComposeViewControllerDelegate, WBContactRecentPickerViewControllerDelegate, WBComposeViewControllerDelegate, WBRetweetToFriendsViewDelegate>
{
    WBShareContent *_content;
    WBRetweetToFriendsManager *_manager;
}

@property(nonatomic) __weak WBRetweetToFriendsManager *manager; // @synthesize manager=_manager;
@property(retain, nonatomic) WBShareContent *content; // @synthesize content=_content;
- (void).cxx_destruct;
- (void)shareToPrivateMessage:(id)arg1;
- (void)contactRecentPickerViewController:(id)arg1 shareToPrivateMessageWithUserTarget:(id)arg2;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

