//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIBezierPath, UIImageView;

@interface WBSlideShowThemeResourceLoading : UIView
{
    UIImageView *_cancelImageView;
    UIBezierPath *_outsideRingPath;
    UIBezierPath *_insideRingPath;
    double _insideRingRadius;
    struct CGPoint _insideRingCenter;
    double _progress;
}

@property(nonatomic) double progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

