//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBModelObject.h"

@class NSString;

@interface WBStoryItemSegmentRank : WBModelObject
{
    NSString *_icon;
    long long _style;
    NSString *_text;
    NSString *_scheme;
    NSString *_storyId;
    long long _aggreHeaderStyle;
}

@property(nonatomic) long long aggreHeaderStyle; // @synthesize aggreHeaderStyle=_aggreHeaderStyle;
@property(retain, nonatomic) NSString *storyId; // @synthesize storyId=_storyId;
@property(retain, nonatomic) NSString *scheme; // @synthesize scheme=_scheme;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic) long long style; // @synthesize style=_style;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
- (void).cxx_destruct;
- (_Bool)updateWithDictionary:(id)arg1;

@end

