//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SwipeViewDataSource-Protocol.h"
#import "SwipeViewDelegate-Protocol.h"
#import "WBStorySwipIndicatorViewDelegate-Protocol.h"

@class NSString, WBSegmentSwipeView, WBStoryRLTableView, WBStorySwipIndicatorView;

@interface WBStorySegmentSwiperIndicatorView : UIView <WBStorySwipIndicatorViewDelegate, SwipeViewDataSource, SwipeViewDelegate>
{
    _Bool _swipeViewDragging;
    CDUnknownBlockType _arrowPressBlock;
    CDUnknownBlockType _swiperViewDragingBlock;
    CDUnknownBlockType _swiperViewDidDragBlock;
    WBSegmentSwipeView *_bottomSwpipView;
    WBStorySwipIndicatorView *_topIndicatorView;
    WBStoryRLTableView *_commentTableView;
    WBStoryRLTableView *_viewersTableView;
    unsigned long long _displayType;
    unsigned long long _focusType;
}

@property(nonatomic) _Bool swipeViewDragging; // @synthesize swipeViewDragging=_swipeViewDragging;
@property(nonatomic) unsigned long long focusType; // @synthesize focusType=_focusType;
@property(nonatomic) unsigned long long displayType; // @synthesize displayType=_displayType;
@property(retain, nonatomic) WBStoryRLTableView *viewersTableView; // @synthesize viewersTableView=_viewersTableView;
@property(retain, nonatomic) WBStoryRLTableView *commentTableView; // @synthesize commentTableView=_commentTableView;
@property(retain, nonatomic) WBStorySwipIndicatorView *topIndicatorView; // @synthesize topIndicatorView=_topIndicatorView;
@property(retain, nonatomic) WBSegmentSwipeView *bottomSwpipView; // @synthesize bottomSwpipView=_bottomSwpipView;
@property(copy, nonatomic) CDUnknownBlockType swiperViewDidDragBlock; // @synthesize swiperViewDidDragBlock=_swiperViewDidDragBlock;
@property(copy, nonatomic) CDUnknownBlockType swiperViewDragingBlock; // @synthesize swiperViewDragingBlock=_swiperViewDragingBlock;
@property(copy, nonatomic) CDUnknownBlockType arrowPressBlock; // @synthesize arrowPressBlock=_arrowPressBlock;
- (void).cxx_destruct;
- (struct CGSize)swipeViewItemSize:(id)arg1;
- (void)swipeViewDidEndDecelerating:(id)arg1;
- (void)swipeViewDidEndScrollingAnimation:(id)arg1;
- (void)swipeViewDidScroll:(id)arg1;
- (void)swipeViewWillBeginDragging:(id)arg1;
- (id)swipeView:(id)arg1 viewForItemAtIndex:(long long)arg2 reusingView:(id)arg3;
- (long long)numberOfItemsInSwipeView:(id)arg1;
- (void)swipIndicatorView:(id)arg1 didTapDissmissButton:(id)arg2;
- (void)swipIndicatorView:(id)arg1 didSelectAtIndex:(unsigned long long)arg2;
- (_Bool)isSwipIndicatorViewScrolling;
- (void)setCurrentSegIndex:(long long)arg1;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1 segDisplayInfoType:(unsigned long long)arg2 segeFocusType:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

