//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class AVAudioPlayer, UIButton, WBContentImageView, WBSTCardHeaderModel, WBStoryMusicItem;

@interface WBSTCardMusicView : UIView
{
    CDStruct_df91ec73 _flags;
    WBContentImageView *_bgImageView;
    WBContentImageView *_contentImageView;
    WBContentImageView *_statusImageView;
    UIButton *_playButton;
    WBStoryMusicItem *_musicItem;
    WBSTCardHeaderModel *_headerModel;
    AVAudioPlayer *_audioPlayer;
}

@property(retain, nonatomic) AVAudioPlayer *audioPlayer; // @synthesize audioPlayer=_audioPlayer;
@property(retain, nonatomic) WBSTCardHeaderModel *headerModel; // @synthesize headerModel=_headerModel;
@property(retain, nonatomic) WBStoryMusicItem *musicItem; // @synthesize musicItem=_musicItem;
@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) WBContentImageView *statusImageView; // @synthesize statusImageView=_statusImageView;
@property(retain, nonatomic) WBContentImageView *contentImageView; // @synthesize contentImageView=_contentImageView;
@property(retain, nonatomic) WBContentImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
- (void).cxx_destruct;
- (void)resetStatus;
- (void)endLoading;
- (void)startLoading;
- (void)playAction:(id)arg1;
- (id)mediaInfoToMusicItem:(id)arg1;
- (void)updateWith:(id)arg1;
- (void)initConstrains;
- (void)kApplicationWillEnterBackgroundMethod:(id)arg1;
- (void)initSubViews;
- (void)dealloc;
- (void)didMoveToWindow;
- (id)initWithFrame:(struct CGRect)arg1;

@end

