//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class UIImageView, UILabel;

@interface WBStoryAdHintView : UIControl
{
    UILabel *_hintLabel;
    UIImageView *_unfoldImg;
    UIImageView *_unfoldUpImg;
}

@property(retain, nonatomic) UIImageView *unfoldUpImg; // @synthesize unfoldUpImg=_unfoldUpImg;
@property(retain, nonatomic) UIImageView *unfoldImg; // @synthesize unfoldImg=_unfoldImg;
@property(retain, nonatomic) UILabel *hintLabel; // @synthesize hintLabel=_hintLabel;
- (void).cxx_destruct;
- (void)initAninationState;
- (void)doAnimation;
- (void)setAdText:(id)arg1;
- (void)initConstraints;
- (void)initSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

