//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIView, WBStoryStickersView;

@protocol WBStoryStickersViewDelegate <NSObject>
- (void)storyStickersViewDidSwipeUp:(WBStoryStickersView *)arg1;
- (void)storyStickersViewTapBlank:(WBStoryStickersView *)arg1;
- (void)storyStickersViewDidEditTextView:(UIView *)arg1;
- (void)storyStickersViewEndEditing:(WBStoryStickersView *)arg1;
- (void)storyStickersViewBeginEditing:(WBStoryStickersView *)arg1;
@end

