//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CAAnimationDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString;
@protocol WBSwipeStackViewDataSource, WBSwipeStackViewDelegate;

@interface WBSwipeStackView : UIView <UIGestureRecognizerDelegate, CAAnimationDelegate>
{
    struct {
        unsigned int didSwipWithOffset:1;
        unsigned int willSwipTo:1;
        unsigned int didSwipTo:1;
        unsigned int didCancelSwip:1;
    } _delegateResponds;
    NSMutableDictionary *_reusedCells;
    NSMutableArray *_cells;
    UIView *cellContainerView;
    _Bool _isNeedGesture;
    id <WBSwipeStackViewDelegate> _delegate;
    id <WBSwipeStackViewDataSource> _dataSource;
    long long _currentIndex;
    unsigned long long _visibleCellCount;
    double _customTopForCells;
    double _cellStackOffset;
    double _cellPaddingScale;
    double _cellEscapeDistance;
    struct CGPoint _centerForCells;
}

@property(nonatomic) double cellEscapeDistance; // @synthesize cellEscapeDistance=_cellEscapeDistance;
@property(nonatomic) double cellPaddingScale; // @synthesize cellPaddingScale=_cellPaddingScale;
@property(nonatomic) double cellStackOffset; // @synthesize cellStackOffset=_cellStackOffset;
@property(nonatomic) struct CGPoint centerForCells; // @synthesize centerForCells=_centerForCells;
@property(nonatomic) double customTopForCells; // @synthesize customTopForCells=_customTopForCells;
@property(nonatomic) _Bool isNeedGesture; // @synthesize isNeedGesture=_isNeedGesture;
@property(nonatomic) unsigned long long visibleCellCount; // @synthesize visibleCellCount=_visibleCellCount;
@property(readonly, nonatomic) long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(nonatomic) __weak id <WBSwipeStackViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <WBSwipeStackViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutCellsWithPanTranslation:(struct CGPoint)arg1 ignoreTop:(_Bool)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)handlePanGesture:(id)arg1;
- (id)centreTopCell;
- (id)dismissTopCellWithAnimated:(_Bool)arg1;
- (id)popTopCellToRight;
- (id)popTopCellToDown;
- (id)popTopCellToUp;
- (id)popTopCellToLeft;
- (id)popTopCellWithDirection:(long long)arg1;
- (id)popTopCellWithDirection:(long long)arg1 options:(unsigned long long)arg2 rotate:(_Bool)arg3;
- (struct CGPoint)centerForCell:(id)arg1 atIndex:(long long)arg2 offsetPercent:(double)arg3;
- (double)alphaForCellAtIndex:(long long)arg1 offsetPerCent:(double)arg2;
- (struct CGAffineTransform)transformForCellAtIndex:(long long)arg1 offsetPercent:(double)arg2;
- (void)loadCellIfNeedAnimated:(_Bool)arg1;
- (void)removeAllCells;
- (void)reloadDataAnimated:(_Bool)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)_switchStackShowAnimation:(id)arg1;
- (void)startStackShowAnimation;
- (void)reloadData;
- (unsigned long long)maxVisualCellIndex;
- (void)saveReusedCell:(id)arg1;
- (id)visibleCells;
- (double)cellHeight;
- (id)dequeueReusableCellWithIdentifier:(id)arg1;
- (struct CGRect)topCellFrame;
- (id)topCell;
- (_Bool)blockDrawerGesture:(id)arg1 withTouch:(id)arg2;
- (void)layoutSubviews;
- (id)allCellsInStacks;
- (void)setHidden:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

