//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WBTimelineActionButtonsConfig : NSObject
{
    double _height;
}

@property double height; // @synthesize height=_height;
- (id)initWithIPadScreen;
- (id)initWithIPhone6PlusScreen;
- (id)initWithIPhone6Screen;
- (id)initWithIPhone5Screen;

@end

