//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBTimelineContentImageViewLayouter.h"

@interface WBTimelineContentImageViewItemLayouter : WBTimelineContentImageViewLayouter
{
}

- (struct CGRect)contentView:(id)arg1 imageFrameForRow:(unsigned long long)arg2 column:(unsigned long long)arg3;
- (unsigned long long)contentView:(id)arg1 numberOfColumnsInRow:(unsigned long long)arg2;
- (unsigned long long)numberOfGridImagesRowsIn:(id)arg1;

@end

