//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBModelObject.h"

@class NSDictionary, NSMutableDictionary, NSString, WBCommonButtonModel;

@interface WBTimelineExtraMenuModel : WBModelObject
{
    NSString *_name;
    NSString *_enName;
    NSString *_twName;
    NSDictionary *_params;
    NSMutableDictionary *_actionlog;
    NSString *_scheme;
    unsigned long long _type;
    WBCommonButtonModel *_buttonModel;
}

+ (id)objectWithJSONDictionary:(id)arg1;
+ (_Bool)isValidForDictionary:(id)arg1;
+ (id)objectWithDictionary:(id)arg1;
@property(retain, nonatomic) WBCommonButtonModel *buttonModel; // @synthesize buttonModel=_buttonModel;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *scheme; // @synthesize scheme=_scheme;
@property(retain, nonatomic) NSMutableDictionary *actionlog; // @synthesize actionlog=_actionlog;
@property(retain, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(retain, nonatomic) NSString *twName; // @synthesize twName=_twName;
@property(retain, nonatomic) NSString *enName; // @synthesize enName=_enName;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)buttonTitle;
- (id)menuTypeString;
- (unsigned long long)menuTypeOfDict:(id)arg1;
- (_Bool)updateWithJSONDictionary:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;
- (id)dictionaryRepresentation;
- (_Bool)updateWithDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1;

// Remaining properties
@property(nonatomic) __weak id parentObject;

@end

