//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@class DACircularProgressView, NSMutableDictionary, NSString, UIButton, UILongPressGestureRecognizer, UITapGestureRecognizer, UIView;
@protocol WBUserProfileEditItemDelegate;

@interface WBUserProfileEditItem : UIImageView
{
    UILongPressGestureRecognizer *longGesture;
    UITapGestureRecognizer *tapGesture;
    UIView *backgroundShadow;
    _Bool _isEditing;
    id <WBUserProfileEditItemDelegate> _delegate;
    UIButton *_deleteButton;
    long long _status;
    DACircularProgressView *_progressView;
    UIImageView *_progressBgImageView;
    UIImageView *_loadFailImage;
    NSString *_url;
    NSString *_originUrl;
    NSString *_pid;
    long long _flag;
    NSString *_filePath;
    NSMutableDictionary *_userInfo;
}

@property(retain, nonatomic) NSMutableDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(nonatomic) long long flag; // @synthesize flag=_flag;
@property(copy, nonatomic) NSString *pid; // @synthesize pid=_pid;
@property(copy, nonatomic) NSString *originUrl; // @synthesize originUrl=_originUrl;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) UIImageView *loadFailImage; // @synthesize loadFailImage=_loadFailImage;
@property(retain, nonatomic) UIImageView *progressBgImageView; // @synthesize progressBgImageView=_progressBgImageView;
@property(retain, nonatomic) DACircularProgressView *progressView; // @synthesize progressView=_progressView;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(nonatomic) _Bool isEditing; // @synthesize isEditing=_isEditing;
@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(nonatomic) id <WBUserProfileEditItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)deleteBtnClick:(id)arg1;
- (void)itemClick:(id)arg1;
- (void)loadFailImageDidClick;
- (void)longPress:(id)arg1;
- (void)layoutSubviews;
- (void)loadOriginImage;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

