//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSError, UIView, WBVideoItem, WBVideoPlayerController;
@protocol WBFAVPlayerItem, WBVideoPlayerSourceView;

@protocol WBVideoPlaybackEventListener <NSObject>

@optional
- (void)videoPlayerControllerDidChangeMuteState:(WBVideoPlayerController *)arg1;
- (void)videoPlayerControllerUserSeekDone:(WBVideoPlayerController *)arg1;
- (void)videoPlayerControllerUserWillStartSeek:(WBVideoPlayerController *)arg1;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 didMoveToSourceView:(UIView<WBVideoPlayerSourceView> *)arg2;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 didExitFullscreenAnimated:(_Bool)arg2;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 didEnterFullscreenAnimated:(_Bool)arg2;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 willExitFullscreenAnimated:(_Bool)arg2;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 willEnterFullscreenAnimated:(_Bool)arg2;
- (void)videoPlayerControllerWillToggleFullScreenState:(WBVideoPlayerController *)arg1;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 didReceiveOrientationChangeNotificationWithOrientation:(long long)arg2;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 playerSeekfinished:(_Bool)arg2;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 playerSeekStart:(CDStruct_1b6d18a9)arg2 isResume:(_Bool)arg3;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 playerWillStartSeek:(_Bool)arg2;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 didPerformPauseWithReason:(long long)arg2 reasonApplied:(_Bool)arg3;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 willPerformPauseWithReason:(long long)arg2;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 didPerformPlayWithReason:(long long)arg2 reasonApplied:(_Bool)arg3;
- (void)videoPlayerControllerDidFinishPlayback:(WBVideoPlayerController *)arg1;
- (void)videoPlayerControllerDidPlayToEnd:(WBVideoPlayerController *)arg1;
- (void)videoPlayerControllerPlaybackLikelyToKeepUp:(WBVideoPlayerController *)arg1;
- (void)videoPlayerControllerDidStallPlayback:(WBVideoPlayerController *)arg1;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 didUpdateCurrentTime:(CDStruct_1b6d18a9)arg2;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 didTransitionFromPlaybackState:(long long)arg2 toPlaybackState:(long long)arg3;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 didFailWithError:(NSError *)arg2;
- (void)videoPlayerControllerIsReady:(WBVideoPlayerController *)arg1;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 didChangeVideoPlayerItem:(id <WBFAVPlayerItem>)arg2;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 queryPlayerItemFinishedWithError:(NSError *)arg2 extraParams:(NSDictionary *)arg3;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 didRequestPlaybackForVideoItem:(WBVideoItem *)arg2;
@end

