//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBVideoPlayerControllerDelegate-Protocol.h"

@class UIButton, WBVideoPlayerController;

@protocol WBVideoTimelinePlayerControllerDelegate <WBVideoPlayerControllerDelegate>

@optional
- (_Bool)videoPlayerController:(WBVideoPlayerController *)arg1 shouldEnterFullscreenByPressingFullScreenButton:(UIButton *)arg2;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 didPressMutebutton:(_Bool)arg2;
- (void)videoPlayerController:(WBVideoPlayerController *)arg1 didUpdateActiveState:(_Bool)arg2;
- (void)videoPlayerControllerUserDidTapOnBlankArea:(WBVideoPlayerController *)arg1;
@end

