//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIView, WBVideoGradientColorView;

@interface WBVideoPluginViewBottomProgressView : UIButton
{
    double _progress;
    UIView *_progressView;
    UIView *_placeHolderProgressView;
    double _progressViewHeight;
    unsigned long long _type;
    WBVideoGradientColorView *_gradientView;
}

@property(retain, nonatomic) WBVideoGradientColorView *gradientView; // @synthesize gradientView=_gradientView;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) double progressViewHeight; // @synthesize progressViewHeight=_progressViewHeight;
@property(retain, nonatomic) UIView *placeHolderProgressView; // @synthesize placeHolderProgressView=_placeHolderProgressView;
@property(retain, nonatomic) UIView *progressView; // @synthesize progressView=_progressView;
@property(nonatomic) double progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (void)setShouldHideShadowView:(_Bool)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithProgressViewType:(unsigned long long)arg1;

@end

