//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBWebLocalResource.h"

@class WBImageEditorCache;

@interface WBWebLocalImageResource : WBWebLocalResource
{
    WBImageEditorCache *_imageCache;
}

@property(retain, nonatomic) WBImageEditorCache *imageCache; // @synthesize imageCache=_imageCache;
- (void).cxx_destruct;
- (void)retriveData:(CDUnknownBlockType)arg1;
- (id)mimeType;
- (id)initWithImageEditorCache:(id)arg1;
- (void)dealloc;

@end

