//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray;

@interface WGChatModel : NSObject
{
    _Bool _isGroupChat;
    NSMutableArray *_dataSource;
    NSMutableArray *_dataInfoSource;
}

@property(nonatomic) _Bool isGroupChat; // @synthesize isGroupChat=_isGroupChat;
@property(retain, nonatomic) NSMutableArray *dataInfoSource; // @synthesize dataInfoSource=_dataInfoSource;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (id)getCustomDateWithHour:(long long)arg1 minute:(long long)arg2;
- (_Bool)operateTime;
- (void)addOtherItem:(id)arg1 sending:(_Bool)arg2 sended:(_Bool)arg3;
- (void)addSpecifiedItem:(id)arg1 sending:(_Bool)arg2 sended:(_Bool)arg3;
- (void)addFixedReplyItem:(id)arg1;
- (int)customSerViceId;
- (void)populateRandomDataSource;
- (float)totalHeight;

@end

