//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YXModel.h"

@class NSNumber, NSString;

@interface YXLiveAdvUpdateModel : YXModel
{
    NSString *_img;
    NSString *_text1;
    NSString *_text2;
    NSString *_text3;
    NSString *_color1;
    NSString *_color2;
    NSString *_color3;
    NSNumber *_offset_y;
}

@property(retain, nonatomic) NSNumber *offset_y; // @synthesize offset_y=_offset_y;
@property(retain, nonatomic) NSString *color3; // @synthesize color3=_color3;
@property(retain, nonatomic) NSString *color2; // @synthesize color2=_color2;
@property(retain, nonatomic) NSString *color1; // @synthesize color1=_color1;
@property(retain, nonatomic) NSString *text3; // @synthesize text3=_text3;
@property(retain, nonatomic) NSString *text2; // @synthesize text2=_text2;
@property(retain, nonatomic) NSString *text1; // @synthesize text1=_text1;
@property(retain, nonatomic) NSString *img; // @synthesize img=_img;
- (void).cxx_destruct;

@end

