//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YXBaseView.h"

#import "YXLiveEventListener-Protocol.h"
#import "YXLiveNativeAlertCashDelegate-Protocol.h"
#import "YXLiveNativeAlertOutOfGameDelegate-Protocol.h"
#import "YXLiveNativeAnswerViewDelegate-Protocol.h"

@class NSString, YXLiveNativeAlertBaseView, YXLiveNativeAnswerView;
@protocol YXLiveMillionScreenPluginDelegate;

@interface YXLiveMillionScreenPlugin : YXBaseView <YXLiveNativeAlertCashDelegate, YXLiveNativeAlertOutOfGameDelegate, YXLiveNativeAnswerViewDelegate, YXLiveEventListener>
{
    id <YXLiveMillionScreenPluginDelegate> _delegate;
    NSString *_scid;
    YXLiveNativeAnswerView *_answerView;
    YXLiveNativeAlertBaseView *_presentAlert;
}

@property(retain, nonatomic) YXLiveNativeAlertBaseView *presentAlert; // @synthesize presentAlert=_presentAlert;
@property(retain, nonatomic) YXLiveNativeAnswerView *answerView; // @synthesize answerView=_answerView;
@property(copy, nonatomic) NSString *scid; // @synthesize scid=_scid;
@property(nonatomic) __weak id <YXLiveMillionScreenPluginDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)yxLiveNativeAlertOutOfGameShouldShareWithType:(long long)arg1 andQuestionId:(id)arg2 andQud:(id)arg3;
- (void)yxLiveNativeAlertCashShouldShareWithType:(long long)arg1 andGoldCoinCount:(float)arg2;
- (void)answerViewWillAppear;
- (void)answerViewDidSelectAtIndex:(unsigned long long)arg1 withKey:(id)arg2;
- (void)answerViewDidRemoveFormSuperViewWithType:(unsigned long long)arg1;
- (void)showAlert:(id)arg1;
- (void)didGetYXMillionEventTypeBarrageEvent:(id)arg1;
- (void)didGetYXMillionEventTypeAchieveCashEvent:(id)arg1;
- (void)didGetYXMillionEventTypeAchieveGoldCoinEvent:(id)arg1;
- (void)didGetYXMillionEventTypeKnockOutEvent:(id)arg1;
- (void)didGetYXMillionEventTypeResurgenceEvent;
- (void)didGetYXMillionEventTypeFaildEvent;
- (void)didGetYXMillionEventTypeLateEvent;
- (void)didGetYXMillionEventTypeAnswerEvent:(id)arg1;
- (void)didGetYXMillionEventTypeQuestionEvent:(id)arg1;
- (void)announcerOnEvent:(id)arg1 fromSender:(id)arg2 userInfo:(id)arg3;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)penetrate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

