//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YXLiveBaseModule.h"

@class UILabel, UIView, YXMyAwardDayTaskLookSonView;

@interface YXMyAwardDayTaskLookModule : YXLiveBaseModule
{
    CDUnknownBlockType _awardDayTaskLookModule_taskLookSonTask_Block;
    UIView *_lineView;
    UILabel *_awardDayTaskLook_name_label;
    UILabel *_awardDayTaskLook_describe_label;
    YXMyAwardDayTaskLookSonView *_awardDayTaskLook_sonBackView;
}

@property(retain, nonatomic) YXMyAwardDayTaskLookSonView *awardDayTaskLook_sonBackView; // @synthesize awardDayTaskLook_sonBackView=_awardDayTaskLook_sonBackView;
@property(retain, nonatomic) UILabel *awardDayTaskLook_describe_label; // @synthesize awardDayTaskLook_describe_label=_awardDayTaskLook_describe_label;
@property(retain, nonatomic) UILabel *awardDayTaskLook_name_label; // @synthesize awardDayTaskLook_name_label=_awardDayTaskLook_name_label;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(copy, nonatomic) CDUnknownBlockType awardDayTaskLookModule_taskLookSonTask_Block; // @synthesize awardDayTaskLookModule_taskLookSonTask_Block=_awardDayTaskLookModule_taskLookSonTask_Block;
- (void).cxx_destruct;
- (void)setData:(id)arg1;
- (void)setupViewWithDataArray:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 withDataArray:(id)arg2;

@end

