//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YXTrueLoveBaseModel.h"

@class NSString;

@interface YXTrueLoveTopHeaderModel : YXTrueLoveBaseModel
{
    _Bool _isFromMine;
    NSString *_truelove_avatar;
    NSString *_truelove_medal;
    NSString *_truelove_groupName;
    long long _truelove_currLevel;
    long long _truelove_upgradeLevel;
    long long _truelove_currPopularity;
    long long _truelove_upgradePopularity;
    long long _truelove_totalLiveTime;
    long long _truelove_fansRanking;
    long long _truelove_rankingGap;
    NSString *_truelove_AnchorMemberid;
    NSString *_truelove_UserNikename;
    NSString *_trueLove_GroupAnchorNickname;
    long long _truelove_Status;
    long long _truelove_NeedTime;
}

+ (id)testModel;
@property(nonatomic) _Bool isFromMine; // @synthesize isFromMine=_isFromMine;
@property(nonatomic) long long truelove_NeedTime; // @synthesize truelove_NeedTime=_truelove_NeedTime;
@property(nonatomic) long long truelove_Status; // @synthesize truelove_Status=_truelove_Status;
@property(retain, nonatomic) NSString *trueLove_GroupAnchorNickname; // @synthesize trueLove_GroupAnchorNickname=_trueLove_GroupAnchorNickname;
@property(retain, nonatomic) NSString *truelove_UserNikename; // @synthesize truelove_UserNikename=_truelove_UserNikename;
@property(retain, nonatomic) NSString *truelove_AnchorMemberid; // @synthesize truelove_AnchorMemberid=_truelove_AnchorMemberid;
@property(nonatomic) long long truelove_rankingGap; // @synthesize truelove_rankingGap=_truelove_rankingGap;
@property(nonatomic) long long truelove_fansRanking; // @synthesize truelove_fansRanking=_truelove_fansRanking;
@property(nonatomic) long long truelove_totalLiveTime; // @synthesize truelove_totalLiveTime=_truelove_totalLiveTime;
@property(nonatomic) long long truelove_upgradePopularity; // @synthesize truelove_upgradePopularity=_truelove_upgradePopularity;
@property(nonatomic) long long truelove_currPopularity; // @synthesize truelove_currPopularity=_truelove_currPopularity;
@property(nonatomic) long long truelove_upgradeLevel; // @synthesize truelove_upgradeLevel=_truelove_upgradeLevel;
@property(nonatomic) long long truelove_currLevel; // @synthesize truelove_currLevel=_truelove_currLevel;
@property(retain, nonatomic) NSString *truelove_groupName; // @synthesize truelove_groupName=_truelove_groupName;
@property(retain, nonatomic) NSString *truelove_medal; // @synthesize truelove_medal=_truelove_medal;
@property(retain, nonatomic) NSString *truelove_avatar; // @synthesize truelove_avatar=_truelove_avatar;
- (void).cxx_destruct;

@end

