//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface AWERedPacketRecordManager : NSObject
{
    NSMutableDictionary *_redPacketRecordDict;
}

+ (_Bool)hasRecordedRedPacket:(id)arg1;
+ (id)recordedRedPacketContent:(id)arg1;
+ (void)updateRedPacketRecordWithItemID:(id)arg1 redPacketContent:(id)arg2;
+ (id)sharedManager;
@property(retain, nonatomic) NSMutableDictionary *redPacketRecordDict; // @synthesize redPacketRecordDict=_redPacketRecordDict;
- (void).cxx_destruct;
- (void)_retriveRecord;
- (void)_saveRecord;
- (id)_redPacketContentWithKey:(id)arg1;
- (void)_addRedPacketRecordWithKey:(id)arg1 redPacketContent:(id)arg2;
- (id)init;

@end

