//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "TTAdSplashControllerViewDelegate-Protocol.h"

@class NSString, TTAdSplashControllerView, TTAdSplashDownloader;

@interface TTAdSplashManager : NSObject <TTAdSplashControllerViewDelegate>
{
    double _latelyDidBecomeActiveTimeInterval;
    _Bool _adWillShow;
    _Bool _isAdShowing;
    _Bool _ignoreFirstLaunch;
    TTAdSplashDownloader *_splashDownloadManager;
    long long _splashADShowType;
    long long _resouceType;
    TTAdSplashControllerView *_controllerView;
}

+ (id)recentlySSADTrackInfoList;
+ (void)saveSSADRecentlyTrackInfoList:(id)arg1;
+ (id)recentlySSADTrackInfo;
+ (void)saveSSADRecentlyTrackInfo:(id)arg1;
+ (double)recentlySSADEnterBackgroundTime;
+ (void)clearSSADRecentlyEnterBackgroundTime;
+ (void)saveSSADRecentlyEnterBackgroundTime;
+ (double)recentlySSADShowSplashTime;
+ (void)clearSSADRecentlyShowSplashTime;
+ (void)saveSSADRecentlyShowSplashADTime;
+ (id)getSplashModels;
+ (id)getADControlInfoModelsForSaveKey:(id)arg1;
+ (void)updateADControlInfoModels:(id)arg1 modelSaveKey:(id)arg2;
+ (void)clearTodayShowCount;
+ (_Bool)checkoutFirstSplashEnable;
+ (void)setFirstLaunch;
+ (_Bool)checkoutFirstLaunch;
+ (void)clearResouceCache;
+ (float)resouceCacheSize;
+ (id)resouceCachePath;
+ (_Bool)isCacheExistWithADModel:(id)arg1 readyType:(long long *)arg2;
+ (_Bool)isCacheExistForADModel:(id)arg1;
+ (_Bool)isSuitableADModel:(id)arg1 readyType:(long long *)arg2;
+ (id)pickKindOfModel:(id)arg1 with:(id)arg2 area:(CDUnknownBlockType)arg3;
+ (id)checkoutFirstLaunchModel:(id)arg1 with:(id)arg2;
+ (id)checkoutNonfirstLaunchModel:(id)arg1 with:(id)arg2;
+ (id)checkoutNormalLaunchModel:(id)arg1 with:(id)arg2;
+ (id)splashModel;
+ (id)pickedFitSplashModelWithTrackInfoList:(id)arg1;
+ (id)shareInstance;
+ (void)initialize;
@property(retain, nonatomic) TTAdSplashControllerView *controllerView; // @synthesize controllerView=_controllerView;
@property(nonatomic) _Bool ignoreFirstLaunch; // @synthesize ignoreFirstLaunch=_ignoreFirstLaunch;
@property(nonatomic) _Bool isAdShowing; // @synthesize isAdShowing=_isAdShowing;
@property(nonatomic) _Bool adWillShow; // @synthesize adWillShow=_adWillShow;
@property(nonatomic) long long resouceType; // @synthesize resouceType=_resouceType;
@property(nonatomic) long long splashADShowType; // @synthesize splashADShowType=_splashADShowType;
@property(retain, nonatomic) TTAdSplashDownloader *splashDownloadManager; // @synthesize splashDownloadManager=_splashDownloadManager;
- (void).cxx_destruct;
- (_Bool)discardAd:(id)arg1;
- (_Bool)isNowOrientationShowSpalsh;
- (void)setSplashResouceType:(id)arg1;
- (void)didEnterBackground;
- (void)updateADControlInfoForSplashModels:(id)arg1;
- (_Bool)remainShowCount;
- (long long)todayShowCount;
- (void)setTodaySplashShowTimes;
- (void)splashControllerViewShowFinished:(id)arg1 animation:(_Bool)arg2;
- (void)performActionForSplashADModel:(id)arg1 index:(long long)arg2;
- (void)splashViewWithAction:(id)arg1 nineBoxIndex:(long long)arg2;
- (void)splashControllerViewClickBackgroundAction:(id)arg1;
- (void)splashControllerViewWithAction:(id)arg1;
- (void)showSplashControllerViewOnKeyWindow:(id)arg1 model:(id)arg2;
- (void)fetchADControlInfoWithExtraParameters:(id)arg1;
- (_Bool)displaySplashOnWindow:(id)arg1 splashShowType:(long long)arg2;
- (void)registerDelegate:(id)arg1 paramsBlock:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (void)addNotifications;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

