//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UMANBaseEvent.h"

@class NSString;

@interface UMANError : UMANBaseEvent
{
    NSString *_context;
}

@property(copy, nonatomic) NSString *context; // @synthesize context=_context;
- (void)outputUMLog;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)attributes;
- (id)init;
- (void)dealloc;

@end

