//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMSceneLayer.h"

@class FM2DParticleEffectFilter;

@interface FM2DParticleEffectSceneLayer : FMSceneLayer
{
    FM2DParticleEffectFilter *_particleFilter;
}

+ (id)sceneWithResource:(id)arg1 materialProvider:(id)arg2 layerName:(id)arg3;
@property(retain, nonatomic) FM2DParticleEffectFilter *particleFilter; // @synthesize particleFilter=_particleFilter;
- (void).cxx_destruct;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2 touchPosition:(struct CGPoint)arg3;
- (void)dealloc;
- (void)setHandGestureInfo:(id)arg1;
- (void)setCacheMananger:(void *)arg1;
- (void)setPoseFeature:(id)arg1;
- (void)setFaces:(id)arg1;
- (void)setAudioRealTimeSchedule:(double)arg1;
- (id)sceneFilter;
- (void)setCurrentTime:(double)arg1;
- (void)clear;
- (_Bool)faceRequired;

@end

