//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface FMDebugFilterPerformanceDetector : NSObject
{
    NSString *_filterName;
    double _preTime;
    double _costTime;
    NSMutableDictionary *_statsDic;
}

@property(retain, nonatomic) NSMutableDictionary *statsDic; // @synthesize statsDic=_statsDic;
@property(nonatomic) double costTime; // @synthesize costTime=_costTime;
@property(nonatomic) double preTime; // @synthesize preTime=_preTime;
@property(retain, nonatomic) NSString *filterName; // @synthesize filterName=_filterName;
- (void).cxx_destruct;
- (id)currentStats;
- (void)stopTimer:(id)arg1;
- (void)startTimer;
- (id)initWithName:(id)arg1;

@end

