//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FMPoseFeature : NSObject
{
    _Bool _valid;
    CDStruct_49799e90 _pose;
}

@property(nonatomic) CDStruct_49799e90 pose; // @synthesize pose=_pose;
@property(nonatomic) _Bool valid; // @synthesize valid=_valid;
- (CDStruct_49799e90 *)poseAddr;

@end

