//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "KCBaseThreadManagerDelegate-Protocol.h"

@class KCOpenThreadManager, NSString, XFMulticastDelegate;
@protocol KMThreadManagerDelegate;

@interface KMThreadManager : NSObject <KCBaseThreadManagerDelegate>
{
    KCOpenThreadManager *_openManager;
    XFMulticastDelegate<KMThreadManagerDelegate> *_multiDelegate;
}

@property(retain, nonatomic) XFMulticastDelegate<KMThreadManagerDelegate> *multiDelegate; // @synthesize multiDelegate=_multiDelegate;
@property(readonly, nonatomic) KCOpenThreadManager *openManager; // @synthesize openManager=_openManager;
- (void).cxx_destruct;
- (void)threadManager:(id)arg1 didReloadWithNewThreads:(id)arg2 pThreadID:(id)arg3;
- (void)threadManager:(id)arg1 didRemoveThreads:(id)arg2 pThreadID:(id)arg3;
- (void)threadManager:(id)arg1 didUpdateThreads:(id)arg2 pThreadID:(id)arg3;
- (void)sync;
- (void)removeDelegate:(id)arg1;
- (void)addDelegate:(id)arg1 delegateQueue:(id)arg2;
- (_Bool)updateLocalExtWithString:(id)arg1 ofThread:(id)arg2 andType:(int)arg3;
- (unsigned long long)getUnreadSumWhere:(id)arg1;
- (void)removeThread:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)cleanUnreadCountForThread:(id)arg1;
- (void)loadThreadsEailerThanThread:(id)arg1 parentThread:(id)arg2 countLimit:(unsigned int)arg3 completion:(CDUnknownBlockType)arg4;
- (id)initWithOpenThreadManager:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

