//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface KSAtlasEditShareConfig : NSObject
{
    _Bool _forceOpenMusicTag;
    NSString *_initialCaptain;
}

+ (id)config;
@property(nonatomic) _Bool forceOpenMusicTag; // @synthesize forceOpenMusicTag=_forceOpenMusicTag;
@property(retain, nonatomic) NSString *initialCaptain; // @synthesize initialCaptain=_initialCaptain;
- (void).cxx_destruct;

@end

