//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface KSFaceDetectionControllerConfig : NSObject
{
    double _minFaceDetectionInterval;
    unsigned long long _priority;
    CDStruct_87cc2293 _detectorConfig;
}

@property(readonly, nonatomic) unsigned long long priority; // @synthesize priority=_priority;
@property(readonly, nonatomic) CDStruct_87cc2293 detectorConfig; // @synthesize detectorConfig=_detectorConfig;
@property(readonly, nonatomic) double minFaceDetectionInterval; // @synthesize minFaceDetectionInterval=_minFaceDetectionInterval;
- (id)initWithMinFaceDetectionInterval:(double)arg1 detectorConfig:(CDStruct_87cc2293)arg2 priority:(unsigned long long)arg3;

@end

