//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KSFeedToolBar.h"

@class KSExtensionButton, UIButton, UIImage;
@protocol KSFeedHorizontalToolBarDelegate;

@interface KSFeedHorizontalToolBar : KSFeedToolBar
{
    id <KSFeedHorizontalToolBarDelegate> _delegate;
    UIButton *_commentButton;
    UIButton *_likeButton;
    KSExtensionButton *_shareButton;
    UIImage *_opacityLikeImage;
}

@property(retain, nonatomic) UIImage *opacityLikeImage; // @synthesize opacityLikeImage=_opacityLikeImage;
@property(retain, nonatomic) KSExtensionButton *shareButton; // @synthesize shareButton=_shareButton;
@property(retain, nonatomic) UIButton *likeButton; // @synthesize likeButton=_likeButton;
@property(retain, nonatomic) UIButton *commentButton; // @synthesize commentButton=_commentButton;
- (void).cxx_destruct;
- (_Bool)_needShowCommentButton;
- (double)_marginBetweenButtons;
- (void)_updateLayoutForTitleAndImageForButton:(id)arg1;
- (void)_setupCommentButton;
- (void)_setupLikeButton;
- (void)_setupShareButton;
- (void)_setupSubviews;
- (id)likeAnimationImageNameFormat;
- (id)commentText;
- (id)likeText;
- (void)commentsInfoChanged;
- (void)likeStateChanged:(_Bool)arg1 showAnimation:(_Bool)arg2;
@property(nonatomic) __weak id <KSFeedHorizontalToolBarDelegate> delegate; // @dynamic delegate;

@end

