//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class KSLiveUserProfileViewModel, NSMutableArray, UIButton;

@interface KSLiveUserOperationView : UIView
{
    CDUnknownBlockType _liveUserOperation;
    KSLiveUserProfileViewModel *_profileViewModel;
    UIButton *_profileButton;
    UIButton *_followButton;
    UIButton *_chatButton;
    UIButton *_homeButton;
    UIButton *_atButton;
    NSMutableArray *_operationButtons;
    NSMutableArray *_hairlines;
}

@property(retain, nonatomic) NSMutableArray *hairlines; // @synthesize hairlines=_hairlines;
@property(retain, nonatomic) NSMutableArray *operationButtons; // @synthesize operationButtons=_operationButtons;
@property(retain, nonatomic) UIButton *atButton; // @synthesize atButton=_atButton;
@property(retain, nonatomic) UIButton *homeButton; // @synthesize homeButton=_homeButton;
@property(retain, nonatomic) UIButton *chatButton; // @synthesize chatButton=_chatButton;
@property(retain, nonatomic) UIButton *followButton; // @synthesize followButton=_followButton;
@property(retain, nonatomic) UIButton *profileButton; // @synthesize profileButton=_profileButton;
@property(retain, nonatomic) KSLiveUserProfileViewModel *profileViewModel; // @synthesize profileViewModel=_profileViewModel;
@property(copy, nonatomic) CDUnknownBlockType liveUserOperation; // @synthesize liveUserOperation=_liveUserOperation;
- (void).cxx_destruct;
- (void)_initUI;
- (id)_createActionButtonWithTitle:(id)arg1 opereaion:(unsigned long long)arg2;
- (void)userProfileUpdated;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

