//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KSLiveMoreActionsTileView.h"

@class UIButton, UIView;

@interface KSLiveAnchorMoreActionsView : KSLiveMoreActionsTileView
{
    UIButton *_musicEffectButton;
    UIButton *_liveQuizButton;
    UIButton *_beautifyButton;
    UIButton *_settingButton;
    UIButton *_mirrorButton;
    UIButton *_shareButton;
    UIButton *_replayMsgButton;
    UIButton *_magicFaceSwitchButton;
    UIButton *_redpacketButton;
    UIView *_shareBadgeView;
    UIView *_settingBadgeView;
}

@property(retain, nonatomic) UIView *settingBadgeView; // @synthesize settingBadgeView=_settingBadgeView;
@property(retain, nonatomic) UIView *shareBadgeView; // @synthesize shareBadgeView=_shareBadgeView;
@property(retain, nonatomic) UIButton *redpacketButton; // @synthesize redpacketButton=_redpacketButton;
@property(retain, nonatomic) UIButton *magicFaceSwitchButton; // @synthesize magicFaceSwitchButton=_magicFaceSwitchButton;
@property(retain, nonatomic) UIButton *replayMsgButton; // @synthesize replayMsgButton=_replayMsgButton;
@property(retain, nonatomic) UIButton *shareButton; // @synthesize shareButton=_shareButton;
@property(retain, nonatomic) UIButton *mirrorButton; // @synthesize mirrorButton=_mirrorButton;
@property(retain, nonatomic) UIButton *settingButton; // @synthesize settingButton=_settingButton;
@property(retain, nonatomic) UIButton *beautifyButton; // @synthesize beautifyButton=_beautifyButton;
@property(retain, nonatomic) UIButton *liveQuizButton; // @synthesize liveQuizButton=_liveQuizButton;
@property(retain, nonatomic) UIButton *musicEffectButton; // @synthesize musicEffectButton=_musicEffectButton;
- (void).cxx_destruct;
- (id)badgeView;
- (void)setHidden:(_Bool)arg1;
- (id)initWithMirrorEnabled:(_Bool)arg1 switchMagicFaceEnabled:(_Bool)arg2 redPackEnabled:(_Bool)arg3 beautifyFaceEnabled:(_Bool)arg4 quizEnabled:(_Bool)arg5;

@end

