//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface KSLoginLogNode : NSObject
{
    KSLoginLogNode *_prevNode;
    KSLoginLogNode *_nextNode;
    NSString *_identifier;
}

@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) __weak KSLoginLogNode *nextNode; // @synthesize nextNode=_nextNode;
@property(nonatomic) __weak KSLoginLogNode *prevNode; // @synthesize prevNode=_prevNode;
- (void).cxx_destruct;
- (void)fillContentPackage:(id)arg1;
- (id)init;

@end

