//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIColor, UIFont;

@interface KSMediaEditRulerStyle : NSObject
{
    UIColor *_longLineColor;
    UIColor *_shortLineColor;
    UIColor *_titleColor;
    UIFont *_titleFont;
    double _spaceBetweenTitleAndLongLine;
    struct CGSize _longLineSize;
    struct CGSize _shortLineSize;
}

+ (id)oldRulerStyle;
+ (id)defaultRulerStyle;
@property(nonatomic) double spaceBetweenTitleAndLongLine; // @synthesize spaceBetweenTitleAndLongLine=_spaceBetweenTitleAndLongLine;
@property(retain, nonatomic) UIFont *titleFont; // @synthesize titleFont=_titleFont;
@property(retain, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(retain, nonatomic) UIColor *shortLineColor; // @synthesize shortLineColor=_shortLineColor;
@property(retain, nonatomic) UIColor *longLineColor; // @synthesize longLineColor=_longLineColor;
@property(nonatomic) struct CGSize shortLineSize; // @synthesize shortLineSize=_shortLineSize;
@property(nonatomic) struct CGSize longLineSize; // @synthesize longLineSize=_longLineSize;
- (void).cxx_destruct;

@end

