//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LYWComponent.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class KSMPreviewPlayer, KSMTextureItem, NSArray, NSMutableArray, NSObject, NSString, UITapGestureRecognizer, UIView;
@protocol KSAdvTextureEdit;

@interface KSMediaEditTextureCanvasComponent : LYWComponent <UIGestureRecognizerDelegate>
{
    KSMPreviewPlayer *_player;
    UIView *_canvas;
    NSString *_originCurrentTimeKVOKey;
    NSMutableArray *_lastTextures;
    UITapGestureRecognizer *_canvasTapRecognizer;
    NSArray *_addingTextureItems;
    KSMTextureItem<KSAdvTextureEdit> *_replacingTextureItem;
    unsigned long long _replacingIndex;
    NSArray *_removingTextureItems;
    NSObject<KSAdvTextureEdit> *_editingTextureItem;
}

@property(retain, nonatomic) NSObject<KSAdvTextureEdit> *editingTextureItem; // @synthesize editingTextureItem=_editingTextureItem;
@property(retain, nonatomic) NSArray *removingTextureItems; // @synthesize removingTextureItems=_removingTextureItems;
@property(nonatomic) unsigned long long replacingIndex; // @synthesize replacingIndex=_replacingIndex;
@property(retain, nonatomic) KSMTextureItem<KSAdvTextureEdit> *replacingTextureItem; // @synthesize replacingTextureItem=_replacingTextureItem;
@property(retain, nonatomic) NSArray *addingTextureItems; // @synthesize addingTextureItems=_addingTextureItems;
@property(retain, nonatomic) UITapGestureRecognizer *canvasTapRecognizer; // @synthesize canvasTapRecognizer=_canvasTapRecognizer;
@property(retain, nonatomic) NSMutableArray *lastTextures; // @synthesize lastTextures=_lastTextures;
@property(retain, nonatomic) NSString *originCurrentTimeKVOKey; // @synthesize originCurrentTimeKVOKey=_originCurrentTimeKVOKey;
@property(retain, nonatomic) UIView *canvas; // @synthesize canvas=_canvas;
@property(retain, nonatomic) KSMPreviewPlayer *player; // @synthesize player=_player;
- (void).cxx_destruct;
- (void)_setUserInteractionEnabledIfNeedWithNewState:(id)arg1;
- (void)_configCanvasWithNewState:(id)arg1;
- (void)_setItemOnEditingIfNeed:(id)arg1;
- (void)_removeItemIfNeedWithNewState:(id)arg1;
- (void)_replaceItemIfNeedWithNewState:(id)arg1;
- (void)_addItemIfNeedWithNewState:(id)arg1;
- (void)_addTextureItems:(id)arg1;
- (void)_replaceTextureItem:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)_removeTextureItems:(id)arg1;
- (void)_setOnEditingWithItem:(id)arg1;
- (void)_reloadCurrentTextures;
- (void)_updateCanvasTransforms;
- (void)_updateCanvasConstraints;
- (void)didTapCanvas:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)newState:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithStore:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

