//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class KSPortMessage, NSData, NSString;
@protocol KSPortDelegate;

@protocol KSPortProtocol <NSObject>
@property(nonatomic) __weak id <KSPortDelegate> delegate;
@property(getter=isActive) _Bool active;
@property(readonly, nonatomic) unsigned short port;
@property(readonly, nonatomic) NSString *host;
- (void)sendData:(NSData *)arg1 withType:(unsigned int)arg2;

@optional
- (void)sendPortMessage:(KSPortMessage *)arg1;
@end

