//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "KSLiveQuizSelectSheetDataItem-Protocol.h"

@class NSArray, NSNumber, NSString, UIColor;

@interface KSQuizSheet : NSObject <KSLiveQuizSelectSheetDataItem>
{
    NSString *_id;
    NSString *_title;
    NSNumber *_type;
    NSNumber *_status;
    NSNumber *_ksCoin;
    NSNumber *_questionCount;
    NSArray *_questions;
}

+ (id)mj_objectClassInArray;
@property(retain, nonatomic) NSArray *questions; // @synthesize questions=_questions;
@property(retain, nonatomic) NSNumber *questionCount; // @synthesize questionCount=_questionCount;
@property(retain, nonatomic) NSNumber *ksCoin; // @synthesize ksCoin=_ksCoin;
@property(retain, nonatomic) NSNumber *status; // @synthesize status=_status;
@property(retain, nonatomic) NSNumber *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (_Bool)_isApproved;
@property(readonly, nonatomic) _Bool canBeSelected;
@property(readonly, nonatomic) UIColor *previewButtonColor;
@property(readonly, nonatomic) NSString *previewButtonTitle;
@property(readonly, nonatomic) _Bool previewButtonUserinterfaceEnabled;
@property(readonly, nonatomic) UIColor *countColor;
@property(readonly, nonatomic) UIColor *descColor;
@property(readonly, nonatomic) UIColor *prizeColor;
@property(readonly, nonatomic) UIColor *titleColor;
@property(readonly, nonatomic) NSString *prizeInfo;
@property(readonly, nonatomic) NSString *countInfo;
@property(nonatomic) _Bool selected;
@property(readonly, nonatomic) NSString *desc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

