//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface KSResourceManager : NSObject
{
    NSMutableDictionary *_resourceConfigs;
    NSString *_resourceCategory;
}

+ (id)imageResourceWithResourceID:(id)arg1;
+ (id)sharedManager;
@property(retain, nonatomic) NSString *resourceCategory; // @synthesize resourceCategory=_resourceCategory;
@property(copy, nonatomic) NSMutableDictionary *resourceConfigs; // @synthesize resourceConfigs=_resourceConfigs;
- (void).cxx_destruct;
- (void)setupDefaultConfigs;
- (id)resourceConfig;
- (id)init;

@end

