//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KSPageModel.h"

#import "KSSectionModelProtocol-Protocol.h"

@class NSArray, NSString;

@interface KSSectionPageModel : KSPageModel <KSSectionModelProtocol>
{
    NSArray *_sections;
}

- (void).cxx_destruct;
- (void)setOutput:(id)arg1;
- (id)itemForSection:(long long)arg1 row:(long long)arg2;
- (id)itemsForSection:(long long)arg1;
- (long long)numberOfRowsInSection:(long long)arg1;
- (long long)numberOfSections;
- (id)sectionsForData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

