//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface KSShareViewControllerVideoSource : NSObject
{
    _Bool _isTemporary;
    NSString *_originalVideoPath;
    NSString *_depthVideoPath;
    NSString *_captureVideoKey;
    NSString *_videoPath;
}

@property(nonatomic) _Bool isTemporary; // @synthesize isTemporary=_isTemporary;
@property(retain, nonatomic) NSString *videoPath; // @synthesize videoPath=_videoPath;
@property(retain, nonatomic) NSString *captureVideoKey; // @synthesize captureVideoKey=_captureVideoKey;
@property(retain, nonatomic) NSString *depthVideoPath; // @synthesize depthVideoPath=_depthVideoPath;
@property(retain, nonatomic) NSString *originalVideoPath; // @synthesize originalVideoPath=_originalVideoPath;
- (void).cxx_destruct;

@end

