//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface KSUBaseResponse : NSObject
{
    int _result;
    NSString *_msg;
    NSString *_error_msg;
    NSString *_error_url;
    id _originalResponse;
}

+ (id)mj_ignoredPropertyNames;
@property(retain, nonatomic) id originalResponse; // @synthesize originalResponse=_originalResponse;
@property(retain, nonatomic) NSString *error_url; // @synthesize error_url=_error_url;
@property(retain, nonatomic) NSString *error_msg; // @synthesize error_msg=_error_msg;
@property(retain, nonatomic) NSString *msg; // @synthesize msg=_msg;
@property(nonatomic) int result; // @synthesize result=_result;
- (void).cxx_destruct;
- (id)mj_setKeyValues:(id)arg1 context:(id)arg2;
@property(readonly, nonatomic) _Bool success;

@end

