//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KS_user_info.h"

@class NSNumber, NSString;

@interface KSUserPrivilege : KS_user_info
{
    NSString *_ban_reason;
    NSNumber *_user_banned;
    NSNumber *_ban_disallow_appeal;
    NSString *_ban_text;
    NSNumber *_ban_type;
    NSString *_verified_url;
}

@property(retain, nonatomic) NSString *verified_url; // @synthesize verified_url=_verified_url;
@property(retain, nonatomic) NSNumber *ban_type; // @synthesize ban_type=_ban_type;
@property(retain, nonatomic) NSString *ban_text; // @synthesize ban_text=_ban_text;
@property(retain, nonatomic) NSNumber *ban_disallow_appeal; // @synthesize ban_disallow_appeal=_ban_disallow_appeal;
@property(retain, nonatomic) NSNumber *user_banned; // @synthesize user_banned=_user_banned;
@property(retain, nonatomic) NSString *ban_reason; // @synthesize ban_reason=_ban_reason;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

