//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface KwaiDecodeProfileCollector : NSObject
{
    _Bool _shouldProfile;
    NSMutableArray *_statistic;
}

+ (id)sharedInstance;
@property(retain) NSMutableArray *statistic; // @synthesize statistic=_statistic;
@property _Bool shouldProfile; // @synthesize shouldProfile=_shouldProfile;
- (void).cxx_destruct;
- (void)addDecodeMs:(double)arg1;
- (id)init;

@end

