//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (Blend)
+ (id)ks_imageNamed:(id)arg1 alpha:(double)arg2;
+ (id)ks_alphaImageCache;
- (long long)ks_imageCost;
- (id)ks_imageWithAlphaComponent:(double)arg1;
- (id)ks_blurImage;
- (id)imageBlendedWithImage:(id)arg1 blendMode:(int)arg2 alpha:(double)arg3;
@end

