//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBFaceApiModel.h"

@class NSString;

@interface WBFaceActiveReqeustModel : WBFaceApiModel
{
    NSString *_csrfToken;
    NSString *_deviceInfo;
    NSString *_version;
    NSString *_clientIp;
    NSString *_orderNo;
    NSString *_name;
    NSString *_idType;
    NSString *_idNo;
}

@property(copy, nonatomic) NSString *idNo; // @synthesize idNo=_idNo;
@property(copy, nonatomic) NSString *idType; // @synthesize idType=_idType;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *orderNo; // @synthesize orderNo=_orderNo;
@property(copy, nonatomic) NSString *clientIp; // @synthesize clientIp=_clientIp;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *deviceInfo; // @synthesize deviceInfo=_deviceInfo;
@property(copy, nonatomic) NSString *csrfToken; // @synthesize csrfToken=_csrfToken;
- (void).cxx_destruct;

@end

