//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AMapRESTRequestReformer.h"

@class NSMutableDictionary, NSString;

@interface AMapPOIRequestReformer : AMapRESTRequestReformer
{
    NSMutableDictionary *_parameters;
    NSString *_subPath;
}

- (void).cxx_destruct;
- (id)initWithPOISearchRequest:(id)arg1;
- (id)parameters;
- (id)URLPath;
- (id)baseURL;
- (id)method;

@end

