//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GMSx_PBGeneratedMessage.h"

@class GMSx_PBMutableArray, NSString;

@interface GMSx_GMMFeatureMapProto : GMSx_PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GMSx_PBMutableArray *featureArray; // @dynamic featureArray;
@property(nonatomic) _Bool hasFeatureArray; // @dynamic hasFeatureArray;
@property(nonatomic) _Bool hasRaster; // @dynamic hasRaster;
@property(retain, nonatomic) NSString *raster; // @dynamic raster;

@end

