//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GXPushServer;

@interface GXAliasManager : NSObject
{
    GXPushServer *pServer_;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)genAliasErrorInfo:(int)arg1;
- (void)handleAliasResult:(id)arg1;
- (void)unBindAlias:(id)arg1 seqNum:(id)arg2 isSelf:(_Bool)arg3;
- (void)bindAlias:(id)arg1 seqNum:(id)arg2;
- (_Bool)isValidBaseValue:(id)arg1 appid:(id)arg2 cid:(id)arg3;
- (void)setPushServer:(id)arg1;

@end

