//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MBKComponent, NSString, UIView;

@protocol MBKComponentContextTransitioning <NSObject>

@optional
@property(nonatomic) long long operation;
@property(readonly, nonatomic) __weak UIView *containerView;
- (MBKComponent *)componentForKey:(NSString *)arg1;
- (void)completeComponentTransition:(_Bool)arg1;
@end

