//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MBKDriverToUserPositionModel, NSTimer, UIImageView, UILabel;

@interface MBKCallOutView : UIView
{
    MBKDriverToUserPositionModel *_carInfo;
    NSTimer *_countDownTimer;
    long long _secondsCountDown;
    UIImageView *_backImageView;
    UIImageView *_downArrow;
    UILabel *_contextLabel;
}

@property(retain, nonatomic) UILabel *contextLabel; // @synthesize contextLabel=_contextLabel;
@property(retain, nonatomic) UIImageView *downArrow; // @synthesize downArrow=_downArrow;
@property(retain, nonatomic) UIImageView *backImageView; // @synthesize backImageView=_backImageView;
@property(nonatomic) long long secondsCountDown; // @synthesize secondsCountDown=_secondsCountDown;
@property(retain, nonatomic) NSTimer *countDownTimer; // @synthesize countDownTimer=_countDownTimer;
@property(retain, nonatomic) MBKDriverToUserPositionModel *carInfo; // @synthesize carInfo=_carInfo;
- (void).cxx_destruct;
- (id)fomatterTime:(long long)arg1;
- (void)stopTimer;
- (void)startTimer;
- (void)countDownAction;
- (id)init;

@end

