//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MBKBaseViewController.h"

#import "MBKMainToScanQRTransitionAnimationProtocol-Protocol.h"
#import "MBKNavigationTabSliderDataSource-Protocol.h"
#import "MBKNavigationTabSliderDelegate-Protocol.h"
#import "MMMapContextDelegate-Protocol.h"

@class MBKHomeViewControllerTab, MBKNavigationTabSlider, NSArray, NSDate, NSString, UIView, UIViewController;

@interface MBKHomeViewController : MBKBaseViewController <MBKMainToScanQRTransitionAnimationProtocol, MMMapContextDelegate, MBKNavigationTabSliderDelegate, MBKNavigationTabSliderDataSource>
{
    NSArray *_tabs;
    MBKHomeViewControllerTab *_currentTab;
    UIView *_naviBarGrayMask;
    UIView *_edgeView;
    MBKNavigationTabSlider *_navigationTabSlider;
    NSDate *_lastSwitchTime;
}

@property(retain, nonatomic) NSDate *lastSwitchTime; // @synthesize lastSwitchTime=_lastSwitchTime;
@property(retain, nonatomic) MBKNavigationTabSlider *navigationTabSlider; // @synthesize navigationTabSlider=_navigationTabSlider;
@property(retain, nonatomic) UIView *edgeView; // @synthesize edgeView=_edgeView;
@property(retain, nonatomic) UIView *naviBarGrayMask; // @synthesize naviBarGrayMask=_naviBarGrayMask;
@property(retain, nonatomic) MBKHomeViewControllerTab *currentTab; // @synthesize currentTab=_currentTab;
@property(retain, nonatomic) NSArray *tabs; // @synthesize tabs=_tabs;
- (void).cxx_destruct;
- (id)tabTitlesForTabSlider:(id)arg1;
- (void)tabSlider:(id)arg1 didSelectTabAtIndex:(long long)arg2;
- (_Bool)tabSlider:(id)arg1 canSwitchToTabAtIndex:(long long)arg2;
- (id)messageNaviButtonImage;
@property(readonly, nonatomic) NSArray *subViewControllers;
- (id)personalCenterViewController;
- (_Bool)menuIsShowed;
@property(readonly, nonatomic) double navigationBarHeight;
- (void)showMenu;
- (void)presentLoginViewController;
- (void)presentLoginViewControllerAnimated:(_Bool)arg1;
- (void)actionEdgePanGestureRecognizer:(id)arg1;
- (void)activateViewControllerAtIndex:(long long)arg1;
- (void)setupTabbar;
- (void)setupSubviews;
- (void)manuallyAddSpockTabIfNeeded;
- (void)switchToTab:(id)arg1 animated:(_Bool)arg2 forcely:(_Bool)arg3;
- (void)switchToTab:(id)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) UIViewController *currentViewController;
- (long long)preferredStatusBarStyle;
- (id)childViewControllerForStatusBarHidden;
- (id)childViewControllerForStatusBarStyle;
- (_Bool)shouldHideNavigationBarShadow;
- (void)viewDidLayoutSubviews;
- (id)createNavigationBar;
- (void)addNavigationBar;
- (void)viewDidLoad;
- (id)init;
- (id)snapshotOfUnlockButtonView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

