//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MBKMobikeRequest.h"

@class NSString;

@interface MBKHomeLaunchRequest : MBKMobikeRequest
{
    NSString *_cityCode;
    NSString *_lastSelectedId;
    double _scale;
}

@property(nonatomic) double scale; // @synthesize scale=_scale;
@property(copy, nonatomic) NSString *lastSelectedId; // @synthesize lastSelectedId=_lastSelectedId;
@property(copy, nonatomic) NSString *cityCode; // @synthesize cityCode=_cityCode;
- (void).cxx_destruct;
- (id)init;

@end

