//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MBKBaseViewController.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class MBKImproveUserInfoViewModel, NSString, UIButton, UIImageView, UILabel, UITextField, UIView;

@interface MBKImproveUserInfoViewController : MBKBaseViewController <UITextFieldDelegate, UINavigationControllerDelegate, UIImagePickerControllerDelegate, UIActionSheetDelegate>
{
    UILabel *_topTipLabel;
    UIView *_centerContentView;
    UIImageView *_avatarImageView;
    UITextField *_nicknameTextField;
    UIView *_nicknameTextFieldBottomLine;
    UIButton *_femaleButton;
    UIButton *_maleButton;
    UIButton *_weChatInfoButton;
    UILabel *_bottomTipLabel;
    MBKImproveUserInfoViewModel *_improveUserInfoViewModel;
}

+ (void)load;
@property(retain, nonatomic) MBKImproveUserInfoViewModel *improveUserInfoViewModel; // @synthesize improveUserInfoViewModel=_improveUserInfoViewModel;
@property(retain, nonatomic) UILabel *bottomTipLabel; // @synthesize bottomTipLabel=_bottomTipLabel;
@property(retain, nonatomic) UIButton *weChatInfoButton; // @synthesize weChatInfoButton=_weChatInfoButton;
@property(retain, nonatomic) UIButton *maleButton; // @synthesize maleButton=_maleButton;
@property(retain, nonatomic) UIButton *femaleButton; // @synthesize femaleButton=_femaleButton;
@property(retain, nonatomic) UIView *nicknameTextFieldBottomLine; // @synthesize nicknameTextFieldBottomLine=_nicknameTextFieldBottomLine;
@property(retain, nonatomic) UITextField *nicknameTextField; // @synthesize nicknameTextField=_nicknameTextField;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) UIView *centerContentView; // @synthesize centerContentView=_centerContentView;
@property(retain, nonatomic) UILabel *topTipLabel; // @synthesize topTipLabel=_topTipLabel;
- (void).cxx_destruct;
- (void)refreshUserInfo;
- (void)openImagePickerControllerWith:(long long)arg1;
- (void)addMasConstraints;
- (void)setupView;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)addNavigationBar;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

