//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMPointAnnotation.h"

@class MBKMoCarOpenCityInfo;

@interface MBKMoCarOpenCityAnnotation : MMPointAnnotation
{
    _Bool _selected;
    MBKMoCarOpenCityInfo *_info;
}

@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(retain, nonatomic) MBKMoCarOpenCityInfo *info; // @synthesize info=_info;
- (void).cxx_destruct;

@end

