//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MBKUserPaymentBonus;

@interface MBKPaymentManager : NSObject
{
    MBKUserPaymentBonus *_paymentBonus;
}

+ (id)sharedInstance;
@property(copy, nonatomic) MBKUserPaymentBonus *paymentBonus; // @synthesize paymentBonus=_paymentBonus;
- (void).cxx_destruct;
- (void)updatePaymentBonusWithSuccessBlock:(CDUnknownBlockType)arg1 failureBlock:(CDUnknownBlockType)arg2;
- (void)updatePaymentBonus;
- (id)init;

@end

