//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MBKOBViewController.h"

@class MBKGrayTextFieldModel, MBKPasswordGrayTextFieldView, NSString, UIButton, UILabel;

@interface MBKPasswordCollectViewController : MBKOBViewController
{
    _Bool _isRegister;
    UILabel *_messageLabel;
    MBKGrayTextFieldModel *_textFieldModel;
    MBKPasswordGrayTextFieldView *_textField;
    UIButton *_confirmButton;
    NSString *_passwordString;
}

+ (void)load;
@property(copy, nonatomic) NSString *passwordString; // @synthesize passwordString=_passwordString;
@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) MBKPasswordGrayTextFieldView *textField; // @synthesize textField=_textField;
@property(retain, nonatomic) MBKGrayTextFieldModel *textFieldModel; // @synthesize textFieldModel=_textFieldModel;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(nonatomic) _Bool isRegister; // @synthesize isRegister=_isRegister;
- (void).cxx_destruct;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)updateConfirmButtonState;
- (void)confirmButtonClicked:(id)arg1;
- (void)setupViews;
- (void)viewDidLoad;

@end

