//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAttributedString, NSDate;

@interface MBKTimeSelectLineViewModel : NSObject
{
    NSAttributedString *_timeString;
    NSDate *_date;
}

@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(copy, nonatomic) NSAttributedString *timeString; // @synthesize timeString=_timeString;
- (void).cxx_destruct;
- (id)attributeWithString:(id)arg1;
- (void)resetDate;
- (id)init;

@end

