//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@interface UILabel (Wonderful)
+ (void)setAnotherFont:(id)arg1;
+ (void)setAnotherColor:(id)arg1;
- (id)addAttributeString:(id)arg1 withArray:(id)arg2 type:(long long)arg3;
- (id)scanBeginStr:(id)arg1 endStr:(id)arg2 inText:(id *)arg3;
- (void)setColorFontText:(id)arg1;
- (void)setFontText:(id)arg1;
- (void)setColorText:(id)arg1;
@end

