//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface ArkAppRSASign : NSObject
{
    struct __SecKey *pubkeyRef;
}

- (_Bool)verify:(id)arg1 withSign:(id)arg2;
- (_Bool)loadPublicKey:(id)arg1;
- (_Bool)isKeyLoaded;
- (void)dealloc;
- (id)init;

@end

