//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <QQMainProject/IAsynDownloadImageObserver-Protocol.h>

@class NSMutableArray, NSString;
@protocol AVFunExpressionMgrDelegate;

@interface AVFunExpressionMgr : NSObject <IAsynDownloadImageObserver>
{
    struct dispatch_queue_s *_queue;
    NSMutableArray *_downloadList;
    id <AVFunExpressionMgrDelegate> _multiExpDelegate;
    id <AVFunExpressionMgrDelegate> _multiDecDelegate;
    NSMutableArray *_totalArray;
    NSMutableArray *_mulScreenArray;
}

+ (_Bool)isPackageExist:(id)arg1;
+ (void)deletePackage;
+ (id)itemArrayFrom:(id)arg1;
+ (id)zipPath:(id)arg1;
+ (id)packagePath:(id)arg1;
+ (id)mulScreenConfigPath;
+ (id)configPath;
+ (id)basicPath;
+ (void)preDownload:(id)arg1;
+ (void)forceDownloadAssets:(id)arg1 md5:(id)arg2 source:(long long)arg3 cachePath:(id)arg4 successBlock:(CDUnknownBlockType)arg5 failBlock:(CDUnknownBlockType)arg6;
+ (void)clearOldMulScreenCache:(id)arg1;
+ (void)clearOldCache:(id)arg1;
+ (id)getMulScreenConfigFromCache;
+ (id)getConfigFromCache;
+ (void)saveMulConfigureation:(id)arg1;
+ (void)saveConfigureation:(id)arg1;
+ (id)getInstance;
@property(retain, nonatomic) NSMutableArray *mulScreenArray; // @synthesize mulScreenArray=_mulScreenArray;
@property(retain, nonatomic) NSMutableArray *totalArray; // @synthesize totalArray=_totalArray;
@property(nonatomic) id <AVFunExpressionMgrDelegate> multiDecDelegate; // @synthesize multiDecDelegate=_multiDecDelegate;
@property(nonatomic) id <AVFunExpressionMgrDelegate> multiExpDelegate; // @synthesize multiExpDelegate=_multiExpDelegate;
- (void)setDownloadFinished:(id)arg1;
- (void)unZipPacket:(id)arg1;
- (void)didDownloadFail:(id)arg1;
- (void)startDownload:(id)arg1;
- (id)localConfig;
- (id)getMulScreenExpressionArrayWithIconPrepared:(_Bool)arg1 multiType:(id)arg2;
- (id)getMulScreenExpressionArrayWithIconPrepared:(_Bool)arg1;
- (id)getExpressionArrayWithIconPrepared:(_Bool)arg1;
- (void)removeAllExpression;
- (void)downloadImageFinished:(id)arg1;
- (struct dispatch_queue_s *)getCustomQueue;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

