//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface AVLiveUrl : NSObject
{
    long long _type;
    NSString *_playUrl;
    unsigned long long _rateType;
}

@property(nonatomic) unsigned long long rateType; // @synthesize rateType=_rateType;
@property(retain, nonatomic) NSString *playUrl; // @synthesize playUrl=_playUrl;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

