//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/BasePicUploadResp.h>

@class NSString;

@interface C2CPicUploadResp : BasePicUploadResp
{
    NSString *_fileResid;
    NSString *_oldUuid;
}

- (void)dealloc;

// Remaining properties
@property(retain, nonatomic) NSString *fileResid; // @dynamic fileResid;
@property(retain, nonatomic) NSString *oldUuid; // @dynamic oldUuid;

@end

