//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/SingleLineEditViewController.h>

#import <QQMainProject/IDiscussGroupEditNameView-Protocol.h>
#import <QQMainProject/IEditViewControllerObserver-Protocol.h>

@class NSString;

@interface DiscussGroupEditNameViewController : SingleLineEditViewController <IEditViewControllerObserver, IDiscussGroupEditNameView>
{
    long long _discussUin;
    NSString *_oldName;
}

@property(retain, nonatomic) NSString *oldName; // @synthesize oldName=_oldName;
- (void)modifyDiscussNameTimeOut:(long long)arg1;
- (void)modifyDiscussNameFail:(long long)arg1;
- (void)modifyDiscussNameSuccess:(long long)arg1;
- (void)quitDelayAction;
- (_Bool)textFieldShouldReturn:(id)arg1 value:(id)arg2;
- (_Bool)onChangeDiscussName:(id)arg1;
- (_Bool)onEditViewCancel:(id)arg1 value:(id)arg2;
- (_Bool)onEditViewModifyValue:(id)arg1 value:(id)arg2;
- (id)getDiscussUin;
- (void)dealloc;
- (id)initWithGroupName:(long long)arg1 discussName:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

