//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/FAListMgrBase.h>

@class NSMutableArray, NSObject;
@protocol OS_dispatch_queue;

@interface FAListMgrPeer : FAListMgrBase
{
    struct FAListInfo _listInfo;
    NSMutableArray *_fileListCache;
    NSObject<OS_dispatch_queue> *_loadQueue;
}

- (void)onAccountLogout;
- (void)onAccountChanged;
- (unsigned short)getMaxRecentRecordNumber;
- (_Bool)isModelOther:(id)arg1;
- (_Bool)isModelDoc:(id)arg1;
- (void)deleteRecentFile:(id)arg1;
- (void)categoryFileList:(id)arg1 info:(struct FAListInfo)arg2;
- (void)getFileCategoryList:(struct FAListInfo)arg1;
- (void)clearFileList;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

