//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/NSObject-Protocol.h>

@class FullScreenVideoTableViewCell, NSDictionary, UIImage;

@protocol FullScreenVideoCellDelegate <NSObject>
- (void)removeViewVideoCell:(FullScreenVideoTableViewCell *)arg1;
- (_Bool)isMiddleCell:(FullScreenVideoTableViewCell *)arg1;
- (NSDictionary *)getReportDicForCell:(FullScreenVideoTableViewCell *)arg1;
- (void)tableViewVideoCell:(FullScreenVideoTableViewCell *)arg1 didGetVideoNatureSize:(struct CGSize)arg2;
- (_Bool)isLightedUpForCell:(FullScreenVideoTableViewCell *)arg1;
- (void)tableViewVideoCell:(FullScreenVideoTableViewCell *)arg1 didChangeState:(int)arg2;
- (void)tableViewVideoCell:(FullScreenVideoTableViewCell *)arg1 didShowVideoErrorCode:(long long)arg2;
- (void)tableViewVideoCell:(FullScreenVideoTableViewCell *)arg1 fullScreenWillActivated:(_Bool)arg2;
- (void)didEndPlayVideoForCell:(FullScreenVideoTableViewCell *)arg1;
- (void)tableViewVideoCell:(FullScreenVideoTableViewCell *)arg1 didStopPlayVideoAtTime:(double)arg2 withImage:(UIImage *)arg3 articleID:(unsigned long long)arg4;
- (void)didStartPlayVideoForCell:(FullScreenVideoTableViewCell *)arg1;
- (void)willStopPlayVideoForCell:(FullScreenVideoTableViewCell *)arg1;
- (void)willStartPlayVideoForCell:(FullScreenVideoTableViewCell *)arg1;
- (_Bool)shouldPlayVideoForCell:(FullScreenVideoTableViewCell *)arg1;
@end

