//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface GroupComposeVideoConfig : NSObject
{
}

+ (id)VideoContentConfigKeyNameWithType:(id)arg1;
+ (id)sharedInstance;
- (id)JSONValue:(id)arg1;
- (int)getConfigureVersion;
- (void)setConfigureVersion:(int)arg1;
- (id)parserComposeVideoConfigureData:(id)arg1;
- (id)groupComposeVideoConfigurationForType:(id)arg1;
- (void)setGrpComposeVideoConfigureContent:(id)arg1;

@end

