//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <QQMainProject/NSCoding-Protocol.h>

@class NSDictionary;

@interface MQWebOfflineCfg : NSObject <NSCoding>
{
    NSDictionary *_webOfflineCfg;
}

+ (id)parseWebOfflineCfg:(id)arg1;
@property(retain, nonatomic) NSDictionary *webOfflineCfg; // @synthesize webOfflineCfg=_webOfflineCfg;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)getWebOfflineCfg:(id)arg1;

@end

