//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <QQMainProject/MQZoneVideoRangeSliderViewDelegate-Protocol.h>

@class MQZoneVideoRangeSliderView, NSString, UIButton, UILabel;
@protocol MQZoneVideoEditVideoClipViewDelegate;

@interface MQZoneVideoEditVideoClipView : UIView <MQZoneVideoRangeSliderViewDelegate>
{
    UILabel *_timeLabel;
    MQZoneVideoRangeSliderView *_sliderView;
    double _startTime;
    double _stopTime;
    UIButton *_playButton;
    id <MQZoneVideoEditVideoClipViewDelegate> _delegate;
    double _minTime;
}

@property(nonatomic) double minTime; // @synthesize minTime=_minTime;
@property(nonatomic) __weak id <MQZoneVideoEditVideoClipViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)videoRange:(id)arg1 didClipedEndedLeftPosition:(double)arg2 rightPosition:(double)arg3;
- (void)videoRange:(id)arg1 didClipingLeftPosition:(double)arg2 rightPosition:(double)arg3;
- (void)showPlayButton;
- (void)confirmButtonClick:(id)arg1;
- (void)cancelButtonClick:(id)arg1;
- (void)playButtonClick:(id)arg1;
- (id)createButtonWithFrame:(struct CGRect)arg1 Title:(id)arg2 image:(id)arg3 action:(SEL)arg4;
- (void)addSliderView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 videoUrl:(id)arg2 startTime:(double)arg3 stopTime:(double)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

