//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface MultiMsgForwardPBLoader : NSObject
{
}

+ (_Bool)removeMultiMsgForwardBDHPostDataViaUuid:(id)arg1;
+ (_Bool)saveMultiMsgForwardBDHPostData:(id)arg1 viaUuid:(id)arg2;
+ (id)getMMFBDHPostDataFilePathViaUuid:(id)arg1;
+ (_Bool)isMultiMsgForwardFileExsit:(id)arg1;
+ (void)removeExpiredMultiMsgForwardData;
+ (void)removeAllMultiMsgForwardData;
+ (void)removeMultiMsgForwardDataViaUuid:(id)arg1;
+ (_Bool)saveMultiMsgForwardData:(id)arg1 viaUuid:(id)arg2;
+ (id)getMultiMsgForwardViaUuid:(id)arg1;
+ (_Bool)saveMultiMsgForward:(id)arg1 viaUuid:(id)arg2;
+ (id)getMMFDataFilePathViaUuid:(id)arg1;
+ (id)getMultiMsgForwardFromFile:(id)arg1;
+ (_Bool)saveMultiMsgForward:(id)arg1 toFile:(id)arg2;

@end

