//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface NearbyEntranceComponent : NSObject
{
}

+ (void)saveFriendNick:(id)arg1 witUIN:(id)arg2;
+ (id)friendNick:(id)arg1;
+ (id)getInstance;
- (id)getNowLiveViewController;
- (id)getSquareViewController;
- (id)getHotChatController;
- (id)getNearbyMore;
- (id)getNearbyEntrance;
- (void)showNearbyEntranceWithEntry:(long long)arg1;
- (void)showNearbyEntrance;

@end

