//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/NSObject-Protocol.h>

@class NSString, QQImageView;

@protocol PAPhotoViewDelegate <NSObject>
- (void)reportZoomImageEvent:(NSString *)arg1 zoomType:(unsigned long long)arg2;
- (void)QQImageViewScrollViewDidEndZooming:(QQImageView *)arg1 andScale:(double)arg2;
- (void)QQImageViewSingleTapDetected:(QQImageView *)arg1;
- (void)QQImageViewScrollViewWillBeginZooming:(QQImageView *)arg1;
@end

