//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@protocol AudioDataReceiveDelegate, RedGiftAudioDataReceiveDelegate;

@interface QAVAudioManager : NSObject
{
    id <AudioDataReceiveDelegate> _audioDelegate;
    id <RedGiftAudioDataReceiveDelegate> _redGiftAudioDelegate;
}

+ (id)getShareInstance;
@property(nonatomic) id <RedGiftAudioDataReceiveDelegate> redGiftAudioDelegate; // @synthesize redGiftAudioDelegate=_redGiftAudioDelegate;
@property(nonatomic) id <AudioDataReceiveDelegate> audioDelegate; // @synthesize audioDelegate=_audioDelegate;
- (long long)audioDataReceive:(id)arg1 type:(long long)arg2;
- (long long)SetOutputFormatSrc:(int)arg1 sample:(int)arg2 channel:(int)arg3 bit:(int)arg4;
- (long long)unregisterDAudioDataCallbackAll;
- (long long)unregisterDAudioDataCallback:(long long)arg1;
- (long long)registerDAudioDataCallback:(long long)arg1 isNeedMix:(_Bool)arg2;
- (id)init;

@end

