//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/QQControlBaseManager.h>

@class NSMutableArray;

@interface QimLastestStoryFeedEngine : QQControlBaseManager
{
    NSMutableArray *_cacheDataArr;
}

+ (id)convertMsgModel2StoryFeedModel:(id)arg1;
+ (id)convertStoryFeedModel2MsgModel:(id)arg1;
+ (id)GetInstance;
- (void).cxx_destruct;
- (id)onSaveCache;
- (void)onClearCache;
- (void)doReceviceData:(id)arg1;
- (void)onReceviceData:(id)arg1;
- (id)getQimStoryFeedMsgModelForUin:(long long)arg1;
- (id)getQimStoryFeedModelForUin:(long long)arg1;
- (void)deletQimStoryFeedModelForUin:(long long)arg1;
- (void)checkInit;
- (void)onReceviceData:(const void *)arg1 DataLen:(int)arg2 fromUin:(long long)arg3;
- (id)loadCache:(long long)arg1;
- (id)fileNameForCacheData;
- (id)init;

@end

