//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary;

@interface QOFPacketPathMapModel : NSObject
{
    long long _bid;
    long long _version;
    NSDictionary *_url2PathMap;
    int _xo;
}

- (void)dealloc;

// Remaining properties
@property(nonatomic) long long bid; // @dynamic bid;
@property(retain, nonatomic) NSDictionary *url2PathMap; // @dynamic url2PathMap;
@property(nonatomic) long long version; // @dynamic version;

@end

