//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/NSObject-Protocol.h>

@protocol QQDoutuViewDelegate <NSObject>
- (_Bool)isShowingBannerTips;
- (_Bool)isShowingGroupRibbon;
- (_Bool)isShowingDiscussRibbon;
- (_Bool)isShowingMagicFace;
- (_Bool)isShowingSpriteAction;
- (_Bool)isShowingFlappyEgg;
- (_Bool)isShowingPokeAnimation;
- (_Bool)isShowingGroupFlowerAnimation;
@end

