//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/QQModel.h>

@class NSString;

@interface QQDraftModel : QQModel
{
    _Bool _babyQArkTag;
    int _time;
    NSString *_text;
    NSString *_quoteText;
    long long _quoteSeq;
}

@property(nonatomic) _Bool babyQArkTag; // @synthesize babyQArkTag=_babyQArkTag;
@property(nonatomic) long long quoteSeq; // @synthesize quoteSeq=_quoteSeq;
@property(retain, nonatomic) NSString *quoteText; // @synthesize quoteText=_quoteText;
@property(nonatomic) int time; // @synthesize time=_time;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (_Bool)isQuoteDraft;

@end

