//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/QQPbMsgSenderBase.h>

#import <QQMainProject/IC2CTypeMsgRemoveDuplicateRelateMarkGenerator-Protocol.h>

@class NSString;

@interface QQF2FMessageSender : QQPbMsgSenderBase <IC2CTypeMsgRemoveDuplicateRelateMarkGenerator>
{
    int _lastRandom;
    short _lastDivSeq;
}

+ (id)getInstance;
- (void)GenRemoveDuplicateRelateMark:(struct _C2C_DUPLICATE_RELATEMARK *)arg1 GenInputParam:(struct _C2C_DUPLICATE_RELATEMARK_GEN_INPUT_PARAM *)arg2;
- (struct RoutingHead *)genRoutingHead:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

