//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/QQView.h>

#import <QQMainProject/QQCollectionViewDataSource-Protocol.h>
#import <QQMainProject/QQCollectionViewDelegate-Protocol.h>

@class FlowCollectionViewLayout, NSArray, NSDictionary, NSIndexPath, NSString, QQCollectionView, UIButton;
@protocol QQGroupFlashPictureViewDelegate;

@interface QQGroupFlashPictureView : QQView <QQCollectionViewDelegate, QQCollectionViewDataSource>
{
    QQCollectionView *_collectionViewForEffectPicture;
    FlowCollectionViewLayout *_layout;
    NSIndexPath *_selectedIdx;
    UIButton *_buttonForSend;
    NSArray *_arrayForImageUrl;
    NSArray *_arrayForTitles;
    _Bool _useDefaultIndex;
    id <QQGroupFlashPictureViewDelegate> _delegate;
    NSDictionary *_itemsDic;
    NSArray *_productIdArray;
}

@property(retain, nonatomic) NSArray *productIdArray; // @synthesize productIdArray=_productIdArray;
@property(retain, nonatomic) NSDictionary *itemsDic; // @synthesize itemsDic=_itemsDic;
@property(nonatomic) __weak id <QQGroupFlashPictureViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)refreshButton;
- (void)layoutSubviews;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)numberOfItemInCollectionView:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (void)setEffectImageArray:(id)arg1 EffectTitleArray:(id)arg2;
- (void)clickSendBtn;
- (void)initViews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

