//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <QQMainProject/IEngineDispatchDelegate-Protocol.h>

@class NSMutableArray, NSString;

@interface qqha1sacdb : NSObject <IEngineDispatchDelegate>
{
    struct _QQSecDtHandler *_ha4g12jlad;
    NSMutableArray *_llc34ja21d;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *llc34ja21d; // @synthesize llc34ja21d=_llc34ja21d;
@property(nonatomic) struct _QQSecDtHandler *ha4g12jlad; // @synthesize ha4g12jlad=_ha4g12jlad;
- (void).cxx_destruct;
- (void)notifyError:(id)arg1;
- (void)didRecievedMsg:(CDStruct_7895f40e)arg1;
- (void)lmg11ta5:(id)arg1;
- (void)ac2da7fc;
- (void)ta9bcd32:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

