//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/TCSignalChannelService.h>

@interface QQProtoBuffService : TCSignalChannelService
{
}

+ (id)GetInstance;
+ (id)RegisteredCommands;
- (void)notifyError:(id)arg1;
- (void)didRecievedMsg:(CDStruct_7895f40e)arg1;
- (void)commAccRespPushPBBuffer:(const void *)arg1 size:(int)arg2;
- (void)commAccNotifyRespPBBuffer:(const void *)arg1 size:(int)arg2 result:(int)arg3;
- (void)commAccReqPBBuffer:(char **)arg1 buffEnd:(char **)arg2;
- (_Bool)sendPbMsg:(struct MessageLite *)arg1 withCmd:(id)arg2 pSeq:(int *)arg3 immediately:(_Bool)arg4 timeOut:(int)arg5 answerFlag:(BOOL)arg6;
- (id)init;

@end

