//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <QQMainProject/UITableViewDataSource-Protocol.h>
#import <QQMainProject/UITableViewDelegate-Protocol.h>

@class NSArray, NSString;
@protocol PPCustomMenuDelegate;

@interface QQPublicPlatformPopMenu : UIView <UITableViewDelegate, UITableViewDataSource>
{
    NSArray *_dataSubMenu;
    id <PPCustomMenuDelegate> _delegate;
    double _arrowX;
    int _xo;
}

- (void)dealloc;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithTag:(long long)arg1 frame:(struct CGRect)arg2 customParam:(id)arg3 delegate:(id)arg4;

// Remaining properties
@property(nonatomic) double arrowX; // @dynamic arrowX;
@property(retain, nonatomic) NSArray *dataSubMenu; // @dynamic dataSubMenu;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) id <PPCustomMenuDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

