//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/QQSMItemElementBaseView.h>

@class QQProgressBar;

@interface QQSMItemElementProgressView : QQSMItemElementBaseView
{
    QQProgressBar *_progress;
}

+ (struct CGSize)layoutElements:(id)arg1 withMaxSize:(struct CGSize)arg2;
+ (id)createQQSMItemElementProgressView:(id)arg1 withFrame:(struct CGRect)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (_Bool)shouldReuse;
- (void)setProgress:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

