//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/QQViewController.h>

#import <QQMainProject/MQZoneTableFootLoadingViewDelegate-Protocol.h>
#import <QQMainProject/MulMemSelBusiProcessDelegate-Protocol.h>
#import <QQMainProject/QQStorySGFeatureCellDelegate-Protocol.h>
#import <QQMainProject/QQStorySGHotVideoCellDelegate-Protocol.h>
#import <QQMainProject/QQStorySGPrivateInvitorViewDelegate-Protocol.h>
#import <QQMainProject/QQStorySGTopCellDelegate-Protocol.h>
#import <QQMainProject/QQStorySGVideoCollectionCellDelegate-Protocol.h>
#import <QQMainProject/QQVideoCaptureViewControllerDelegate-Protocol.h>
#import <QQMainProject/TBBizNetworkLogicDelegate-Protocol.h>
#import <QQMainProject/TBShareGroupJumpDelegate-Protocol.h>
#import <QQMainProject/TBStoryVideoPlayViewControllerDataSource-Protocol.h>
#import <QQMainProject/UIActionSheetDelegate-Protocol.h>
#import <QQMainProject/UITableViewDataSource-Protocol.h>
#import <QQMainProject/UITableViewDelegate-Protocol.h>

@class MQZoneTableFootLoadingView, NSArray, NSDictionary, NSMutableDictionary, NSString, ODRefreshControl, QQAlertView, QQStorySGDataProvider, QQStorySGDisbandView, QQStorySGFeatureCell, QQStorySGMoreOptionsHandler, QQStorySGPrivateInvitorView, QQStorySGTableView, QQStorySGTopCell, TBStoryVideoPlayViewController, UIButton, UserSummaryNavigationBar;

@interface QQStoryShareGroupViewController : QQViewController <QQVideoCaptureViewControllerDelegate, UIActionSheetDelegate, TBBizNetworkLogicDelegate, QQStorySGPrivateInvitorViewDelegate, UITableViewDataSource, UITableViewDelegate, MQZoneTableFootLoadingViewDelegate, QQStorySGTopCellDelegate, QQStorySGVideoCollectionCellDelegate, TBStoryVideoPlayViewControllerDataSource, TBShareGroupJumpDelegate, QQStorySGFeatureCellDelegate, QQStorySGHotVideoCellDelegate, MulMemSelBusiProcessDelegate>
{
    _Bool _isPlayMode;
    _Bool _dragToBack;
    _Bool _showShareGroupLoading;
    _Bool _navigationContentHidden;
    _Bool _joinedFriListIsLoading;
    _Bool _needRefresh;
    _Bool _hasRepExp;
    unsigned long long _entry;
    unsigned long long _pageType;
    NSString *_groupID;
    unsigned long long _groupCode;
    NSString *_privateShareGroupInvitor;
    TBStoryVideoPlayViewController *_playViewController;
    QQStorySGDataProvider *_dataProvider;
    NSDictionary *_deletedDic;
    QQStorySGTableView *_tableView;
    QQAlertView *_alert;
    QQStorySGMoreOptionsHandler *_moreOptionsHandler;
    QQStorySGPrivateInvitorView *_invitorView;
    ODRefreshControl *_refresh;
    MQZoneTableFootLoadingView *_loadMoreFooter;
    unsigned long long _seq;
    NSMutableDictionary *_cellLastScrollPosition;
    QQStorySGTopCell *_topCell;
    UserSummaryNavigationBar *_userNavigationBar;
    QQStorySGFeatureCell *_featureCell;
    QQStorySGDisbandView *_disbandView;
    NSArray *_joinedFriList;
    UIButton *_storyBtn;
}

@property(nonatomic) _Bool hasRepExp; // @synthesize hasRepExp=_hasRepExp;
@property(nonatomic) _Bool needRefresh; // @synthesize needRefresh=_needRefresh;
@property(retain, nonatomic) UIButton *storyBtn; // @synthesize storyBtn=_storyBtn;
@property(nonatomic) _Bool joinedFriListIsLoading; // @synthesize joinedFriListIsLoading=_joinedFriListIsLoading;
@property(retain, nonatomic) NSArray *joinedFriList; // @synthesize joinedFriList=_joinedFriList;
@property(retain, nonatomic) QQStorySGDisbandView *disbandView; // @synthesize disbandView=_disbandView;
@property(retain, nonatomic) QQStorySGFeatureCell *featureCell; // @synthesize featureCell=_featureCell;
@property(retain, nonatomic) UserSummaryNavigationBar *userNavigationBar; // @synthesize userNavigationBar=_userNavigationBar;
@property(nonatomic, getter=isNavigationContentHidden) _Bool navigationContentHidden; // @synthesize navigationContentHidden=_navigationContentHidden;
@property(retain, nonatomic) QQStorySGTopCell *topCell; // @synthesize topCell=_topCell;
@property(retain, nonatomic) NSMutableDictionary *cellLastScrollPosition; // @synthesize cellLastScrollPosition=_cellLastScrollPosition;
@property(nonatomic) unsigned long long seq; // @synthesize seq=_seq;
@property(retain, nonatomic) MQZoneTableFootLoadingView *loadMoreFooter; // @synthesize loadMoreFooter=_loadMoreFooter;
@property(retain, nonatomic) ODRefreshControl *refresh; // @synthesize refresh=_refresh;
@property(retain, nonatomic) QQStorySGPrivateInvitorView *invitorView; // @synthesize invitorView=_invitorView;
@property(nonatomic, getter=isShowShareGroupLoading) _Bool showShareGroupLoading; // @synthesize showShareGroupLoading=_showShareGroupLoading;
@property(retain, nonatomic) QQStorySGMoreOptionsHandler *moreOptionsHandler; // @synthesize moreOptionsHandler=_moreOptionsHandler;
@property(retain, nonatomic) QQAlertView *alert; // @synthesize alert=_alert;
@property(nonatomic, getter=isDragToBack) _Bool dragToBack; // @synthesize dragToBack=_dragToBack;
@property(retain, nonatomic) QQStorySGTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSDictionary *deletedDic; // @synthesize deletedDic=_deletedDic;
@property(retain, nonatomic) QQStorySGDataProvider *dataProvider; // @synthesize dataProvider=_dataProvider;
@property(nonatomic) __weak TBStoryVideoPlayViewController *playViewController; // @synthesize playViewController=_playViewController;
@property(nonatomic) _Bool isPlayMode; // @synthesize isPlayMode=_isPlayMode;
@property(retain, nonatomic) NSString *privateShareGroupInvitor; // @synthesize privateShareGroupInvitor=_privateShareGroupInvitor;
@property(nonatomic) unsigned long long groupCode; // @synthesize groupCode=_groupCode;
@property(copy, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
@property(nonatomic) unsigned long long pageType; // @synthesize pageType=_pageType;
@property(nonatomic) unsigned long long entry; // @synthesize entry=_entry;
- (void).cxx_destruct;
- (void)onBusinessProcessPopCancelMulMemSelector:(id)arg1 currentViewControllerClass:(id)arg2 selectedMember:(id)arg3;
- (void)onBusinessProcessCancelMulMemSelector:(id)arg1 currentViewControllerClass:(id)arg2 selectedMember:(id)arg3;
- (void)onBusinessProcessWithSelectedMems:(id)arg1 currentViewControllerClass:(id)arg2 currentViewController:(id)arg3;
- (void)openInvitePage;
- (void)requestJoinedFriList;
- (void)shareGroupRemoveMembersNotification:(id)arg1;
- (void)onVideoDidView:(id)arg1;
- (void)onVideoDidLike:(id)arg1;
- (void)onVideoDelete:(id)arg1;
- (void)timeZoneChanged:(id)arg1;
- (void)onFreeSpaceEmptyNotification:(id)arg1;
- (void)onDragToGoBackEnable:(id)arg1;
- (void)sgVideoCellChangeChannelToHot:(id)arg1;
- (id)getGroupIDWithHotVideoCell:(id)arg1;
- (void)hotVideoCell:(id)arg1 didClickPlayModel:(id)arg2 coverView:(id)arg3;
- (void)sgfeatureCellChangeChannel:(id)arg1;
- (void)shareGroupJumpDidCancel:(id)arg1;
- (void)shareGroupJump:(id)arg1 didFinishAddVideo:(id)arg2;
- (void)opneStoryVideoSelect;
- (void)opneStoryCaptureView;
- (void)captureBtnAction:(id)arg1;
- (void)handleGetGroupStoryInfo:(id)arg1;
- (_Bool)hasMoreDataFordataKey:(id)arg1 direction:(long long)arg2;
- (void)requestNextBatchVideo:(id)arg1 direction:(long long)arg2;
- (void)postQuitCircleNotification;
- (void)exitShareGroup;
- (void)collectionCell:(id)arg1 playStoryWithFeedID:(id)arg2 stoyID:(id)arg3 withCoverView:(id)arg4;
- (void)storyShareGroupCell:(id)arg1 joinShareGroup:(id)arg2;
- (void)storyShareGroupCell:(id)arg1 inviteFriend:(id)arg2;
- (void)storyShareGroupCell:(id)arg1 updateGroupName:(id)arg2;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)changeGroupName:(id)arg1;
- (void)handleEmptyData;
- (void)handleDateVideoCollectionList:(id)arg1;
- (void)handleHotRankList:(id)arg1;
- (void)handleShareGroupStoryInfoModel:(id)arg1;
- (void)handleJoinOrExitShareGroupRsp:(id)arg1 requestModel:(id)arg2;
- (void)didRequestFail:(unsigned long long)arg1 requestModel:(id)arg2 error:(id)arg3;
- (void)didReceivedData:(unsigned long long)arg1 requestModel:(id)arg2 classModel:(id)arg3;
- (void)failedToConnect;
- (void)loadMoreData;
- (void)reloadCacheDataForHotMode;
- (void)reloadCacheData;
- (void)stopLoadingWithErr:(_Bool)arg1;
- (void)tableFootLoadingViewDidTriggerLoading:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)stopRefreshCtrlAnimate:(_Bool)arg1 isShowFailedTips:(_Bool)arg2;
- (void)refreshDataRequest;
- (void)saveVisibleCellScrollPosition;
- (void)refreshTimeLineLayer;
@property(nonatomic, getter=isEnd) _Bool end;
- (void)configTableView;
- (void)joinShareGroup;
- (_Bool)netAvailable;
- (id)backItemTitle;
- (_Bool)isSupportRightDragToGoBack;
- (void)removeCustomNavigationBar;
- (void)addCustomNavigationBar;
- (void)initNotification;
- (void)refreshNavigationBarForPublicShareGroup;
- (void)configNormalCustomNavgationBar;
- (id)captureButtonWithFrame:(struct CGRect)arg1;
- (void)showCaptureButton;
- (void)checkModeForShareGroup;
- (void)initUIForGroup;
- (void)initUIAndData;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithEntry:(unsigned long long)arg1 pageType:(unsigned long long)arg2 groupID:(id)arg3 withHotMode:(_Bool)arg4;
- (id)initWithEntry:(unsigned long long)arg1 pageType:(unsigned long long)arg2 groupID:(id)arg3;
- (void)sgChangeHotStoryViewCount:(id)arg1 count:(int)arg2;
- (void)sgChangeHotStoryLikeCount:(id)arg1 count:(int)arg2;
- (void)sgHandleGetGroupStoryInfo:(id)arg1;
- (_Bool)sgHotHasMoreDataFordataKey:(id)arg1 direction:(long long)arg2;
- (void)sgHotRequestNextBatchVideo:(id)arg1 direction:(long long)arg2;
- (_Bool)sgHasMoreDataFordataKey:(id)arg1 direction:(long long)arg2;
- (void)_requestVideoBasicInfoListForDateMode:(id)arg1 direction:(long long)arg2;
- (void)_requestDateStoryPlayListForDateMode:(id)arg1 direction:(long long)arg2;
- (void)sgRequestNextBatchVideo:(id)arg1 direction:(long long)arg2;
- (id)_getStoryIDListWithStoryInfoList:(id)arg1;
- (id)_getDateVideoStoryIDListCache:(id)arg1;
- (id)_getPureVideoCollectionList;
- (id)sgGetPureLastVideoCollection;
- (void)sgInsertTodayData;
- (void)sgSortCollectionList;
- (void)sgAppendCollectionModelList:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

