//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString;

@interface QQStorySGDataProvider : NSObject
{
    _Bool _isHotMode;
    _Bool _hotEnd;
    _Bool _dayEnd;
    NSMutableArray *_list;
    NSString *_hotCookie;
    unsigned long long _hotSeq;
    NSMutableArray *_hotMutList;
    NSString *_dayCookie;
    unsigned long long _daySeq;
    NSMutableArray *_dayMutList;
}

@property(retain, nonatomic) NSMutableArray *dayMutList; // @synthesize dayMutList=_dayMutList;
@property(nonatomic) _Bool dayEnd; // @synthesize dayEnd=_dayEnd;
@property(nonatomic) unsigned long long daySeq; // @synthesize daySeq=_daySeq;
@property(copy, nonatomic) NSString *dayCookie; // @synthesize dayCookie=_dayCookie;
@property(retain, nonatomic) NSMutableArray *hotMutList; // @synthesize hotMutList=_hotMutList;
@property(nonatomic) _Bool hotEnd; // @synthesize hotEnd=_hotEnd;
@property(nonatomic) unsigned long long hotSeq; // @synthesize hotSeq=_hotSeq;
@property(copy, nonatomic) NSString *hotCookie; // @synthesize hotCookie=_hotCookie;
@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
@property(nonatomic) _Bool isHotMode; // @synthesize isHotMode=_isHotMode;
@property(nonatomic) unsigned long long seq;
@property(copy, nonatomic) NSString *cookie;
@property(nonatomic, getter=isEnd) _Bool end;
- (void)dealloc;
- (long long)numberOfSections;
- (long long)numberOfRowsInSection:(long long)arg1;
- (id)itemForIndexPath:(id)arg1;
- (id)initWithGroupID:(id)arg1;

@end

