//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/QQMessageViewCell.h>

@class NSString;

@interface QQSystemMessageCell : QQMessageViewCell
{
    NSString *_fromUin;
    NSString *_groupCode;
}

@property(retain, nonatomic) NSString *groupCode; // @synthesize groupCode=_groupCode;
@property(retain, nonatomic) NSString *fromUin; // @synthesize fromUin=_fromUin;
- (void)setData:(id)arg1;
- (void)dealloc;

@end

