//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/QQWalletTask.h>

@class NSString;

@interface QQWalletGotoViewTask : QQWalletTask
{
    CDUnknownBlockType _completionBlock;
    NSString *_gotoViewName;
}

@property(copy, nonatomic) NSString *gotoViewName; // @synthesize gotoViewName=_gotoViewName;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
- (void).cxx_destruct;

@end

