//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface QQWalletSkinDownloadTask : NSObject
{
    _Bool _isSkin;
    NSString *_aioUrl;
    NSString *_popUrl;
    NSString *_aniUrl;
    NSString *_aioPath;
    NSString *_popPath;
    NSString *_aniPath;
    CDUnknownBlockType _skinBlock;
    CDUnknownBlockType _aniBlock;
}

@property(copy, nonatomic) CDUnknownBlockType aniBlock; // @synthesize aniBlock=_aniBlock;
@property(copy, nonatomic) CDUnknownBlockType skinBlock; // @synthesize skinBlock=_skinBlock;
@property(retain, nonatomic) NSString *aniPath; // @synthesize aniPath=_aniPath;
@property(retain, nonatomic) NSString *popPath; // @synthesize popPath=_popPath;
@property(retain, nonatomic) NSString *aioPath; // @synthesize aioPath=_aioPath;
@property(retain, nonatomic) NSString *aniUrl; // @synthesize aniUrl=_aniUrl;
@property(retain, nonatomic) NSString *popUrl; // @synthesize popUrl=_popUrl;
@property(retain, nonatomic) NSString *aioUrl; // @synthesize aioUrl=_aioUrl;
@property(nonatomic) _Bool isSkin; // @synthesize isSkin=_isSkin;
- (void).cxx_destruct;

@end

