//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString;

@interface QRBatchChapterGroupCellData : NSObject
{
    NSString *_title;
    _Bool _isFold;
    _Bool _isSelected;
    NSMutableArray *_chapters;
    _Bool _fileExists;
    int _xo;
}

- (void).cxx_destruct;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *chapters; // @dynamic chapters;
@property(nonatomic) _Bool fileExists; // @dynamic fileExists;
@property(nonatomic) _Bool isFold; // @dynamic isFold;
@property(nonatomic) _Bool isSelected; // @dynamic isSelected;
@property(copy, nonatomic) NSString *title; // @dynamic title;

@end

