//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TlibDy/JceObjectV2.h>

@class NSString;

@interface QZJOperationImageSummary : JceObjectV2
{
    int _jcev2_p_3_o_source_id;
    NSString *_jcev2_p_0_r_imageId;
    NSString *_jcev2_p_1_o_url;
    NSString *_jcev2_p_2_o_bubbleUrl;
}

+ (id)jceType;
@property(nonatomic, getter=jce_source_id, setter=setJce_source_id:) int jcev2_p_3_o_source_id; // @synthesize jcev2_p_3_o_source_id=_jcev2_p_3_o_source_id;
@property(retain, nonatomic, getter=jce_bubbleUrl, setter=setJce_bubbleUrl:) NSString *jcev2_p_2_o_bubbleUrl; // @synthesize jcev2_p_2_o_bubbleUrl=_jcev2_p_2_o_bubbleUrl;
@property(retain, nonatomic, getter=jce_url, setter=setJce_url:) NSString *jcev2_p_1_o_url; // @synthesize jcev2_p_1_o_url=_jcev2_p_1_o_url;
@property(retain, nonatomic, getter=jce_imageId, setter=setJce_imageId:) NSString *jcev2_p_0_r_imageId; // @synthesize jcev2_p_0_r_imageId=_jcev2_p_0_r_imageId;
- (void).cxx_destruct;
- (id)init;

@end

