//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <QQMainProject/QAVAppChannel-Protocol.h>

@class NSString;

@interface QZLVAppChannelImplement : NSObject <QAVAppChannel>
{
}

+ (id)sharedInstance;
- (void)logToAPP:(id)arg1 level:(int)arg2;
- (void)logToReport:(id)arg1 level:(int)arg2;
- (int)maxFileSize;
- (int)getLogLevel;
- (id)getLogPath;
- (_Bool)identifierToTinyId:(id)arg1 ret:(CDUnknownBlockType)arg2;
- (_Bool)tinyIDToIdentifier:(id)arg1 ret:(CDUnknownBlockType)arg2;
- (_Bool)requestAppCmd:(id)arg1 roomId:(unsigned int)arg2 result:(CDUnknownBlockType)arg3;
- (_Bool)requestAppCmd:(id)arg1 result:(CDUnknownBlockType)arg2;
- (_Bool)requestInfoCmd:(id)arg1 result:(CDUnknownBlockType)arg2;
- (_Bool)requestCmd:(id)arg1 cmdName:(id)arg2 result:(CDUnknownBlockType)arg3;
- (_Bool)requestCmdInner:(id)arg1 cmdName:(id)arg2 result:(CDUnknownBlockType)arg3;
- (unsigned long long)getTinyId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

