//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface QZLVQRRetCodeModel : NSObject
{
    long long _event;
    long long _eventIndex;
    long long _retCode;
}

+ (id)makeWithEvent:(long long)arg1 index:(long long)arg2 retCode:(long long)arg3;
@property(nonatomic) long long retCode; // @synthesize retCode=_retCode;
@property(nonatomic) long long eventIndex; // @synthesize eventIndex=_eventIndex;
@property(nonatomic) long long event; // @synthesize event=_event;

@end

