//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/QZBaseEngine.h>

@class NSMutableDictionary, NSRecursiveLock;

@interface QZPushEngine : QZBaseEngine
{
    NSMutableDictionary *_pushCache;
    NSRecursiveLock *_lock;
    _Bool _dataChange;
}

+ (id)instance;
- (void).cxx_destruct;
- (void)pushACK:(unsigned long long)arg1;
- (id)decodePushData:(id)arg1;
- (id)decodeUpdateData:(id)arg1;
- (void)onApplicationEnterBackground:(id)arg1;
- (void)saveCache;
- (void)loadCache;
- (id)init;

@end

