//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <QQMainProject/AVCaptureAudioDataOutputSampleBufferDelegate-Protocol.h>

@class AVCaptureAudioDataOutput, AVCaptureDevice, AVCaptureDeviceInput, AVCaptureSession, NSString;
@protocol OS_dispatch_queue, QZTTARAudioSessionDelegate;

@interface QZTTARAudioSession : NSObject <AVCaptureAudioDataOutputSampleBufferDelegate>
{
    AVCaptureSession *_session;
    AVCaptureDevice *_inputMicrophone;
    AVCaptureDeviceInput *_audioInput;
    AVCaptureAudioDataOutput *_audioOutput;
    NSObject<OS_dispatch_queue> *audioBufferQueue;
    NSObject<OS_dispatch_queue> *audioProcessingQueue;
    id <QZTTARAudioSessionDelegate> _delegate;
}

@property(nonatomic) id <QZTTARAudioSessionDelegate> delegate; // @synthesize delegate=_delegate;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

