//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSDictionary, QQAvatarView, UIButton, UIImageView, UILabel;
@protocol SayHonestCardViewDelegate;

@interface SayHonestCardView : UIView
{
    QQAvatarView *_iconImageView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UILabel *_totalCountLabel;
    UIImageView *_rightArrow;
    _Bool _showRightArrow;
    UIButton *_backgroundButton;
    id <SayHonestCardViewDelegate> _delegate;
    NSDictionary *_confessDictionary;
}

@property(retain, nonatomic) NSDictionary *confessDictionary; // @synthesize confessDictionary=_confessDictionary;
@property(nonatomic) __weak id <SayHonestCardViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIButton *backgroundButton; // @synthesize backgroundButton=_backgroundButton;
@property(nonatomic) _Bool showRightArrow; // @synthesize showRightArrow=_showRightArrow;
- (void).cxx_destruct;
- (id)addSeperatorForString:(id)arg1;
- (void)backgroundButtonDidClick;
- (void)cacheCurrentShowCount:(int)arg1;
- (_Bool)needUpdateCount;
- (void)reloadAppearance;
- (void)updateColor;
- (void)setupViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

