//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface ScheduleCalenderOptionModel : NSObject
{
    short _optionType;
    NSString *_scheduleId;
}

@property(nonatomic) short optionType; // @synthesize optionType=_optionType;
@property(copy, nonatomic) NSString *scheduleId; // @synthesize scheduleId=_scheduleId;
- (id)initModel;

@end

