//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString, SpriteCheckGameRspModel;

@interface SpriteGameModel : NSObject
{
    _Bool _isShowOnPanel;
    _Bool _needOpenKey;
    _Bool _isSupportStandby;
    _Bool _isDisableGameMsg;
    _Bool _hasOwnArk;
    int _appId;
    int _playMode;
    int _screenMode;
    int _currentSrc;
    int _viewMode;
    NSString *_idStr;
    NSString *_name;
    NSString *_version;
    NSString *_actionIdStr;
    NSString *_gameStartVersion;
    NSMutableArray *_gameBtnArray;
    NSMutableArray *_hotChatBtnArray;
    NSString *_hotChatCode;
    NSString *_listCoverUrl;
    NSString *_bigCoverUrl;
    NSString *_bigCoverBgColor;
    NSString *_toolUrl;
    SpriteCheckGameRspModel *_rspModel;
    NSMutableArray *_homeButtonAction;
    NSString *_activityUrl;
    NSString *_entranceUrl;
}

@property(retain, nonatomic) NSString *entranceUrl; // @synthesize entranceUrl=_entranceUrl;
@property(nonatomic) int viewMode; // @synthesize viewMode=_viewMode;
@property(nonatomic) int currentSrc; // @synthesize currentSrc=_currentSrc;
@property(nonatomic) _Bool hasOwnArk; // @synthesize hasOwnArk=_hasOwnArk;
@property(retain, nonatomic) NSString *activityUrl; // @synthesize activityUrl=_activityUrl;
@property(retain, nonatomic) NSMutableArray *homeButtonAction; // @synthesize homeButtonAction=_homeButtonAction;
@property(nonatomic) int screenMode; // @synthesize screenMode=_screenMode;
@property(retain, nonatomic) SpriteCheckGameRspModel *rspModel; // @synthesize rspModel=_rspModel;
@property(nonatomic) int playMode; // @synthesize playMode=_playMode;
@property(copy, nonatomic) NSString *toolUrl; // @synthesize toolUrl=_toolUrl;
@property(nonatomic) _Bool isDisableGameMsg; // @synthesize isDisableGameMsg=_isDisableGameMsg;
@property(nonatomic) _Bool isSupportStandby; // @synthesize isSupportStandby=_isSupportStandby;
@property(nonatomic) int appId; // @synthesize appId=_appId;
@property(nonatomic) _Bool needOpenKey; // @synthesize needOpenKey=_needOpenKey;
@property(retain, nonatomic) NSString *bigCoverBgColor; // @synthesize bigCoverBgColor=_bigCoverBgColor;
@property(retain, nonatomic) NSString *bigCoverUrl; // @synthesize bigCoverUrl=_bigCoverUrl;
@property(retain, nonatomic) NSString *listCoverUrl; // @synthesize listCoverUrl=_listCoverUrl;
@property(retain, nonatomic) NSString *hotChatCode; // @synthesize hotChatCode=_hotChatCode;
@property(retain, nonatomic) NSMutableArray *hotChatBtnArray; // @synthesize hotChatBtnArray=_hotChatBtnArray;
@property(retain, nonatomic) NSMutableArray *gameBtnArray; // @synthesize gameBtnArray=_gameBtnArray;
@property(nonatomic) _Bool isShowOnPanel; // @synthesize isShowOnPanel=_isShowOnPanel;
@property(retain, nonatomic) NSString *gameStartVersion; // @synthesize gameStartVersion=_gameStartVersion;
@property(retain, nonatomic) NSString *actionIdStr; // @synthesize actionIdStr=_actionIdStr;
@property(retain, nonatomic) NSString *version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *idStr; // @synthesize idStr=_idStr;
- (void)dealloc;
- (id)gameLocalPathOfDownload;
- (id)initWithDict:(id)arg1;

@end

