//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/NIAttributedLabel.h>

@interface TBStoryNIAttrLabel : NIAttributedLabel
{
}

- (void)shouldAdjustLineOrigin:(struct CGContext *)arg1 lines:(struct __CFArray *)arg2 currLine:(struct __CTLine *)arg3 currIndex:(long long)arg4 currLineOrigin:(struct CGPoint)arg5;

@end

