//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSData, NSString;

@interface TCSignalChannelMessage : NSObject
{
    NSString *_serviceCmd;
    int _seq;
    NSData *_origBuff;
    int _xo;
    id data;
}

@property(retain, nonatomic) id data; // @synthesize data;
- (void)dealloc;

// Remaining properties
@property(retain, nonatomic) NSData *origBuff; // @dynamic origBuff;
@property(nonatomic) int seq; // @dynamic seq;
@property(retain, nonatomic) NSString *serviceCmd; // @dynamic serviceCmd;

@end

