//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (Position)
@property(nonatomic) double bottom; // @dynamic bottom;
@property(nonatomic) double right; // @dynamic right;
@property(nonatomic) double height; // @dynamic height;
@property(nonatomic) double width; // @dynamic width;
@property(nonatomic) double top; // @dynamic top;
@property(nonatomic) double left; // @dynamic left;
@end

