//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QQMainProject/QQModel.h>

@class NSData, NSMutableArray, NSString;

@interface USPersonalTagLabelInfo : QQModel
{
    unsigned int _addTime;
    unsigned int _labelCategory;
    unsigned int _praiseCount;
    unsigned int _photoCount;
    unsigned int _unreadPraise;
    unsigned int _modifyTime;
    unsigned int _praiseFlag;
    unsigned long long _labelId;
    NSString *_text;
    NSString *_fgColor;
    NSString *_bgColor;
    NSString *_coverPhotoUrl;
    NSMutableArray *_photos;
    NSData *_photoCookie;
    NSMutableArray *_praiseUserInfoArray;
}

@property(retain, nonatomic) NSMutableArray *praiseUserInfoArray; // @synthesize praiseUserInfoArray=_praiseUserInfoArray;
@property(nonatomic) unsigned int praiseFlag; // @synthesize praiseFlag=_praiseFlag;
@property(nonatomic) unsigned int modifyTime; // @synthesize modifyTime=_modifyTime;
@property(nonatomic) unsigned int unreadPraise; // @synthesize unreadPraise=_unreadPraise;
@property(retain, nonatomic) NSData *photoCookie; // @synthesize photoCookie=_photoCookie;
@property(retain, nonatomic) NSMutableArray *photos; // @synthesize photos=_photos;
@property(nonatomic) unsigned int photoCount; // @synthesize photoCount=_photoCount;
@property(nonatomic) unsigned int praiseCount; // @synthesize praiseCount=_praiseCount;
@property(copy, nonatomic) NSString *coverPhotoUrl; // @synthesize coverPhotoUrl=_coverPhotoUrl;
@property(copy, nonatomic) NSString *bgColor; // @synthesize bgColor=_bgColor;
@property(copy, nonatomic) NSString *fgColor; // @synthesize fgColor=_fgColor;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic) unsigned int labelCategory; // @synthesize labelCategory=_labelCategory;
@property(nonatomic) unsigned long long labelId; // @synthesize labelId=_labelId;
@property(nonatomic) unsigned int addTime; // @synthesize addTime=_addTime;
- (void).cxx_destruct;
- (id)description;

@end

